<?php
// Meta Tags
$meta_title = "KYTS 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita Patha in English - ClickVedicAstro";
$meta_description = "Full KYTS 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita Patha lyrics in English with meaning. Collection of Spiritual and Devotional L...";
$meta_keywords = "KYTS 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita Patha, English Stotras, Devotional Hymns, Hindu Slokas, ClickVedicAstro"; 
$meta_url = "https://www.clickvedicastro.com/en/kyts-22-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha-english.php";

// Include Header (session_start is already here)
include "../includes/header.php";
?>

<main id="content" role="main" class="main-content pt-0 pb-0">
<!-- breadcrumb -->
<div class="page-breadcrumb bg-white py-0">
    <div class="container">
        <div class="my-3">
            <ul class="list">
                <li><a href="<?php echo $base_url; ?>/index.php">Home</a></li>
                <li><a href="<?php echo $base_url; ?>/en/" title="Stotras in English">Stotras in English</a></li>
                <li><a href="<?php echo $base_url; ?>/en/others-stotras">Others Stotras</a></li>
                <li>KYTS 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita Patha</li>
            </ul>
        </div>
    </div>
</div>

    <!-- Ad Promotion Template: For my Website -->
    <div class="adpromotion mt-5">
    <?php include "../includes/ad-promotion2.php"; ?>
    </div>

<section class="devotional-content pt-5">
<div class="container">
    <?php include "../includes/language-table-birth.php"; ?><!-- Language Birth Template-->
    <h1 class="stotra-title">KYTS 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita Patha</h1>

    <article class="stotra-content">
      
<div class="mcontainer">

<br/>
</div>

<br/>
</div>
<div id="search">
<input id="searchbar" placeholder="Search for Stotram..." type="text"/>
</div>
<div id="stotramheader">
<div class="pdfLinks">
<a href="../meaning/english/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Meaning</a>, <a href="../media/english/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Multimedia</a> </div>
<div class="languageView">View this in:</div>
<table><tr>
<td class="languageText">| <a href="../english/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">English</a></td>
<td class="languageText">| <a href="../devanagari/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Devanagari</a></td>
<td class="languageText">| <a href="../telugu/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Telugu</a></td>
<td class="languageText">| <a href="../tamil/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Tamil</a></td>
<td class="languageText">| <a href="../kannada/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Kannada</a></td>
<td class="languageText">| <a href="../malayalam/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Malayalam</a></td>
<td class="languageText">| <a href="../gujarati/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Gujarati</a></td>
<td class="languageText">| <a href="../odia/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Odia</a></td>
<td class="languageText">| <a href="../bengali/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Bengali</a></td>
<td class="languageText"> |</td></tr> </table>
<table><tr>
<td class="languageText">| <a href="../marathi/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Marathi</a></td>
<td class="languageText">| <a href="../assamese/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Assamese</a></td>
<td class="languageText">| <a href="../punjabi/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Punjabi</a></td>
<td class="languageText">| <a href="../hindi/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Hindi</a></td>
<td class="languageText">| <a href="../samskritam/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Samskritam</a></td>
<td class="languageText">| <a href="../konkani/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Konkani</a></td>
<td class="languageText">| <a href="../nepali/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Nepali</a></td>
<td class="languageText">| <a href="../sinhala/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Sinhala</a></td>
<td class="languageText">| <a href="../grantha/kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">Grantha</a></td>
<td class="languageText"> |</td></tr> </table>
<div class="languagePrefix">
This document is in romanized sanskrit according to <b><a href="https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration">IAST</a></b> standard.			</div>
<br/>
</div>
<table>
<!-- <thead><tr><td>
			  <div class="header-space">&nbsp;</div>
			</td></tr></thead> -->
<tbody>
<tr>
<td>
<div id="stotramcontent">
<div id="pageFooter">  </div>
<p class="stotramtitle" id="stitle">
								KYTS 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita Patha
							</p>
<div class="stotramtext" id="stext">
<span>
<span style="font-family:NotoSans; line-height:250%;font-size: 22px;">
<p>ká¹á¹£á¹a yajurvÄdÄ«ya taittirÄ«ya saá¹hitÄyÄ-ndvitÄ«yakÄá¹á¸Ä dvitÄ«yaá¸¥ praÅnaá¸¥ - iá¹£á¹­ividhÄnaá¹</p>
<p>Å-nnamaá¸¥ paramÄtmanÄ, ÅrÄ« mahÄgaá¹apatayÄ namaá¸¥, <br/>
ÅrÄ« gurubhyÅ namaá¸¥ à¥¤ haÌ riÌ á¸¥ Åm à¥¥</p>
<p>praÌ jÄpatiÌá¸¥ praÌ jÄ aÌsá¹jataÌ  tÄ-ssá¹Ì á¹£á¹­ÄÌ  indrÄÌ gnÄ« apÄÌgÅ«hatÄÌ gá¹Ì  sÅÌ-'chÄya-tpraÌ jÄpaÌtirindrÄÌ gnÄ« vai mÄÌ praÌ jÄ apÄÌghuká¹£atÄÌ mitiÌ  sa ÄÌ tamaiÌmdrÄÌ gna- mÄkÄÌdaÅakapÄla-mapaÅyaÌ -tta-nniraÌvapaÌ -ttÄvaÌsmai praÌ jÄá¸¥ prÄsÄÌdhayatÄ- mindrÄÌ gnÄ« vÄ ÄÌ tasyaÌ praÌ jÄmapaÌ gÅ«hatÅÌ  yÅ-'laá¹Ì praÌ jÄyaiÌ  sa-npraÌ jÄ-nna viÌ ndataÌ aindrÄÌ gna-mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄt-praÌ jÄkÄÌma indrÄÌ gnÄ«  [  ]  1</p>
<p>ÄÌ va svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  tÄvÄÌ vÄsmaiÌ praÌ jÄ-mpra sÄÌdhayatÅ viÌ ndatÄÌ praÌ jÄ-maiÌmdrÄÌ gna-mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄÌ -thspardhaÌmÄnaÌ á¸¥, ká¹£ÄtrÄÌ vÄ sajÄÌ tÄá¹£uÌ vÄndrÄÌ gnÄ« ÄÌ va svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  tÄbhyÄÌmÄÌ vÄndriÌ yaá¹ à¤vÄ«Ì ryaÌ-mbhrÄtá¹Ìvyasya vá¹á¹ktÄÌ  vi pÄÌ pmanÄÌ  bhrÄtá¹ÌvyÄá¹a jayaÌ tÄ-'paÌ  vÄ ÄÌ tasmÄÌdindriÌ yaá¹ vÄ«Ì ryaÌ-á¹krÄmatiÌ  ya-ssaÌgrÄÌ mma-muÌpapraÌ yÄtyaiÌmdrÄÌ gna-mÄkÄÌdaÅakapÄlaÌ -nni- [-mÄkÄÌdaÅakapÄlaÌ -nniá¸¥, vaÌ pÄÌ -thsaÌ á¹grÄÌ ma-]  2</p>
<p>-rvaÌpÄ-thsaá¹grÄÌ ma-muÌpaprayÄÌ sya-nniÌndrÄÌ gnÄ« ÄÌ va svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  tÄvÄÌ vÄsmiÌ-nnindriÌ yaá¹ vÄ«Ì ryaÌ-ndhatta-ssaÌ hÄndriÌ yÄá¹aÌ vÄ«Ì ryÄÌá¹ÅpaÌ  pra yÄÌtiÌ  jayaÌtiÌ  tagá¹ saÌgrÄÌ mmaá¹ vi vÄ ÄÌ á¹£a iÌndriÌ yÄá¹aÌ vÄ«Ì ryÄÌá¹ardhyatÄÌ  ya-ssaÌgrÄÌ mma-Ã±jayaÌtyaindrÄÌ gna-mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄ-thsaá¹grÄÌ ma-Ã±jiÌ tvÄndrÄÌ gnÄ« ÄÌ va svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  tÄvÄÌ vÄsmiÌ-nnidriÌ yaá¹ vÄ«Ì ryaÌn- [vÄ«Ì ryaÌm, dhaÌ ttÅÌ  nÄndriÌ yÄá¹aÌ]  3</p>
<p>-dhattÅÌ  nÄndriÌ yÄá¹aÌ vÄ«Ì ryÄÌá¹aÌ  vyá¹ÌddhyaÌ tÄ-'paÌ  vÄ ÄÌ tasmÄÌdindriÌ yaá¹ vÄ«Ì ryaÌ-á¹krÄmatiÌ  ya ÄtiÌ jaÌ natÄÌmaindrÄÌ gna-mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄ-jjaÌ natÄÌmÄÌ á¹£ya-nniÌndrÄÌ gnÄ« ÄÌ va svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  tÄvÄÌ vÄsmiÌ-nnindriÌ yaá¹ vÄ«Ì ryaÌ-ndhatta-ssaÌ hÄndriÌ yÄá¹aÌ vÄ«Ì ryÄÌá¹a jaÌ natÄÌmÄti pauÌ á¹£á¹a-Ã±chaÌ rumanuÌ  nirvaÌpÄ-tpÅ«Ì á¹£Ä vÄ iÌndriÌ yasyaÌ vÄ«Ì ryaÌsyÄ-'nupradÄÌ tÄ pÅ«Ì á¹£aá¹aÌmÄÌ va [  ]  4</p>
<p>svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄsmÄÌ indriÌ yaá¹ vÄ«Ì ryaÌmanuÌ  prayaÌchChati ká¹£aitrapaÌ tya-Ã±chaÌ ru-nnirvaÌpÄ-jjaÌ natÄÌ-mÄÌ gatyÄÌ yaá¹ vai ká¹£ÄtraÌsyaÌ  patiÌraÌ syÄmÄÌ va pratiÌ tiá¹£á¹­hatyaindrÄÌ gna-mÄkÄÌdaÅakapÄla-muÌ pariÌá¹£á¹­ÄÌ -nnirvaÌpÄdaÌ syÄmÄÌ va praÌtiÌ á¹£á¹­hÄyÄÌmdriÌ yaá¹ vÄ«Ì ryaÌ-muÌ pariÌá¹£á¹­Ä-dÄÌ tma-ndhaÌttÄ à¥¥ 5 à¥¥<br/>
<b>(praÌ jÄkÄÌma indrÄÌ gnÄ« - uÌpapraÌ yÄtyaiÌmdrÄÌ gnamÄkÄÌdaÅakapÄlaÌ -nni- rvÄ«Ì ryaá¹Ì - pÅ«Ì á¹£aá¹aÌmÄÌ  vai - kÄÌ nnachaÌtvÄriÌ gá¹Ì ÅachchaÌ ) (a. 1)</b></p>
<p>aÌ gnayÄÌ pathiÌ ká¹tÄÌ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ dyÅ daÌrâÅapÅ«rá¹amÄsayÄÌ jÄ« sannaÌmÄvÄÌ syÄÌá¹ vÄ paurá¹amÄÌ sÄ«á¹ vÄÌ-'tipÄÌ dayÄÌ-tpaÌ thÅ vÄ ÄÌ á¹£ÅddhyapaÌthÄnaitiÌ  yÅ daÌrâÅapÅ«rá¹amÄsayÄÌ jÄ« sannaÌmÄvÄÌ syÄÌá¹ vÄ paurá¹amÄÌ sÄ«á¹ vÄÌtipÄÌ dayaÌtyaÌ gnimÄÌ va paÌthiÌ ká¹taÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vainaÌ mapaÌthÄÌ -tpanthÄÌ mapiÌ nayatyanaÌ á¸vÄ-ndaká¹£iÌá¹Ä vaÌ hÄ« hyÄÌá¹£a samá¹ÌddhyÄ aÌ gnayÄÌ vraÌ tapaÌtayÄ [vraÌ tapaÌtayÄ, puÌ rÅÌ á¸ÄÅaÌ-]  6</p>
<p>purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ dya ÄhiÌtÄgniÌ -ssannaÌvraÌ tyamiÌvaÌ  charÄÌdaÌ gnimÄÌ va vraÌ tapaÌtiÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vainaÌá¹ vraÌ tamÄ laÌbhaá¹yatiÌ  vratyÅÌ bhavatyaÌ gnayÄÌ raká¹£ÅÌ ghnÄ puÌrÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ dyagá¹ raká¹£Ägá¹ÌsiÌ  sachÄÌrannaÌ gnimÄÌ va raÌká¹£ÅÌ haá¹aÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄsmÄÌ -draká¹£ÄÌ gÌ syapaÌ hantiÌ  niÅiÌtÄyÄÌ -nnirvaÌpÄÌ - [nirvaÌpÄt, niÅiÌtÄyÄÌ gá¹Ì  hi]  7</p>
<p>-nniÅiÌtÄyÄÌ gá¹Ì  hi raká¹£Ägá¹Ìsi prÄÌ ratÄÌ saÌ prÄá¹rá¹ÄÌnyÄÌ vainÄÌni hantiÌ  pariÌÅritÄ yÄjayÄÌ -draká¹£aÌsÄÌ -manaÌnvavachÄrÄya raká¹£ÅÌ ghnÄ« yÄÌjyÄnuvÄÌ kyÄÌ bhavatÅÌ  raká¹£aÌsÄÌ gÌ  stá¹tyÄÌ aÌ gnayÄÌ ruÌ dravaÌtÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄ-dabhiÌ charaÌ-nnÄÌ á¹£Ä vÄ aÌsya ghÅÌ rÄ taÌ nÅ«rya-druÌ drastasmÄÌ ÄÌ vainaÌ mÄvá¹ÌÅchati tÄÌ jagÄrtiÌ -mÄrchChaÌtyaÌ gnayÄÌ surabhiÌ matÄÌ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ dyasyaÌ  gÄvÅÌ vÄÌ  puruÌá¹£Ä [vÄÌ  puruÌá¹£Äá¸¥, vÄÌ  praÌ mÄ«yÄÌraÌ nÌ ]  8</p>
<p>vÄ praÌ mÄ«yÄÌraÌ nÌ  yÅ vÄÌ bibhÄ«Ì yÄdÄÌ á¹£Ä vÄ aÌsya bhÄá¹£aÌ jyÄÌ taÌ nÅ«rya-thsuÌrabhiÌ matÄ«Ì -tayaiÌ vÄ-'smaiÌ bhÄá¹£aÌ ja-á¹kaÌrÅti surabhiÌ matÄÌ bhavati pÅ«tÄ«gaÌ ndhasyÄ-'paÌhatyÄ aÌ gnayÄÌ  ká¹£ÄmaÌvatÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄ-thsaá¹grÄÌ mÄ saá¹yaÌttÄ bhÄgaÌ dhÄyÄÌnaiÌ vainagá¹Ì ÅamayiÌ tvÄ parÄÌnaÌ bhi nirdiÌÅatiÌ  yamavaÌrÄá¹£ÄÌ á¹ viddhyaÌntiÌ  jÄ«vaÌtiÌ  sa ya-mparÄÌá¹£ÄÌ -mpra sa mÄ«ÌyatÄÌ  jayaÌtiÌ  tagá¹ saÌá¹grÄÌ ma- [tagá¹ saÌá¹grÄÌ mam, aÌ bhi vÄ ÄÌ á¹£a]  9</p>
<p>-maÌ bhi vÄ ÄÌ á¹£a ÄÌ tÄnuÌchyatiÌ  yÄá¹£ÄÌ-mpÅ«rvÄpaÌ rÄ aÌ nvaÃ±chaÌá¸¥ praÌ mÄ«yaÌntÄ puruá¹£ÄhuÌ tir-hyaÌsya priÌ yataÌmÄÌ -'gnayÄÌ  ká¹£ÄmaÌvatÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄ-dbhÄgaÌ dhÄyÄÌnaiÌ vainagá¹Ì ÅamayatiÌ  naiá¹£ÄÌ-mpuÌ rÄ-''yuÌ á¹£Å-'paÌraÌ á¸¥ pramÄ«ÌyatÄÌ -'bhi vÄ ÄÌ á¹£a ÄÌ tasyaÌ gá¹Ì hÄnuÌchyatiÌ  yasyaÌ gá¹Ì hÄ-ndahaÌtyaÌ gnayÄÌ  ká¹£ÄmaÌvatÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄ-dbhÄgaÌ dhÄyÄÌnaiÌ vainagá¹Ì ÅamayatiÌ  nÄ-'syÄpaÌra-á¹gá¹Ì hÄ-ndaÌhati à¥¥ 10 à¥¥<br/>
<b>(vraÌ tapaÌtayÄÌ  - niÅiÌtÄyÄÌ -nnirvaÌpÄÌ t - puruÌá¹£Äá¸¥ - saá¹grÄÌ maá¹ - na - chaÌ tvÄriÌ cha) (a. 2)</b></p>
<p>aÌ gnayÄÌ  kÄmÄÌya purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ dya-á¹kÄmÅÌ  nÅpaÌ namÄÌ-daÌ gnimÄÌ va kÄmaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vainaÌ -á¹kÄmÄÌnaÌ  samaÌrdhayaÌ tyupaiÌnaÌ -á¹kÄmÅÌ namatyaÌ gnayÄÌ  ya viÌá¹£á¹­hÄya purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ -thspardhaÌmÄnaÌ á¸¥, ká¹£ÄtrÄÌ vÄ sajÄÌ tÄá¹£uÌ vÄÌ -'gnimÄÌ va yaviÌá¹£á¹­haÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  tÄnaiÌ vÄndriÌ yaá¹ vÄ«Ì ryaÌ-mbhrÄtá¹Ìvyasya [bhrÄtá¹Ìvyasya, yuÌ vaÌ tÄÌ  vipÄÌ pmanÄÌ ]  11</p>
<p>yuvatÄÌ  vipÄÌ pmanÄÌ  bhrÄtá¹ÌvyÄá¹a jayatÄÌ -'gnayÄÌ  yaviÌá¹£á¹­hÄya purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄ-dabhichaÌ ryamÄÌá¹ÅÌ  'gnimÄÌ va yaviÌá¹£á¹­haÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄsmÄÌ -draká¹£Ägá¹Ìsi yavayatiÌ  nainaÌ-mabhiÌ charanÌ-thstá¹á¹utÄÌ -'gnayaÌ  ÄyuÌá¹£matÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ dyaá¸¥ kÄÌ mayÄÌtaÌ  sarvaÌ -mÄyuÌ-riyÄÌ -mityaÌ gni- mÄÌ vÄ-''yuÌá¹£mantaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄ-'smiÌ - [ÄÌ vÄ-'sminnÌ, ÄyuÌrdadhÄtiÌ ]  12</p>
<p>-nnÄyuÌrdadhÄtiÌ  sarvaÌ mÄyuÌ-rÄtyaÌ gnayÄÌ jÄÌ tavÄÌdasÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ -dbhÅ«tiÌkÄmÅÌ -'gnimÄÌ va jÄÌ tavÄÌdasaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vainaÌ -mbhÅ«tiÌ-á¹gamayatiÌ  bhavaÌtyÄÌ vÄgnayÄÌ  rukmaÌtÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ -drukkÄÌmÅÌ -'gnimÄÌ va rukmaÌntaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄsmiÌ -nruchaÌ-ndadhÄtiÌ -rÅchaÌta ÄÌ vÄgnayÄÌ  tÄjaÌsvatÄ purÅÌ á¸ÄÅaÌ- [purÅÌ á¸ÄÅaÌm, aÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ t]  13</p>
<p>-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ -ttÄjaÌskÄmÅÌ -'gnimÄÌ va tÄjaÌsvantaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄsmiÌ -ntÄjÅÌ dadhÄti tÄjaÌ svyÄÌva bhaÌvatyaÌ gnayÄÌ sÄhaÌ ntyÄyaÌ purÅÌ á¸ÄÅaÌmaÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ -thsÄ«ká¹£aÌmÄá¹ÅÌ  'gnimÄÌ va sÄÌhaÌ ntyaggâ svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  tÄnaiÌ va saÌhatÄÌ  yagá¹ sÄ«ká¹£aÌtÄ à¥¥ 14 à¥¥<br/>
<b>(bhrÄtá¹ÌvyasyÄ -smiÌ n - tÄjaÌsvatÄ purÅÌ á¸aÅaÌ - maÌ á¹£á¹­Ätrigá¹ÌÅachcha) (a. 3)</b></p>
<p>aÌ gnayÄ-'nnaÌvatÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ dyaá¸¥ kÄÌ mayÄÌ tÄ-'nnaÌvÄn-thsyÄÌ mityaÌ gni-mÄÌ vÄ-nnaÌvantaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vainaÌ mannaÌvanta-á¹karÅÌ tyannaÌvÄnÄÌ va bhaÌvatyaÌ gnayÄÌ-'nnÄÌ dÄyaÌ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ dyaá¸¥ kÄÌ mayÄÌtÄ-'nnÄÌ da-ssyÄÌ mityaÌ gni-mÄÌ vÄnnÄÌ daggâ svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vainaÌ-mannÄÌ da-á¹kaÌrÅtyannÄÌ da - [-kaÌrÅtyannÄÌ daá¸¥, ÄÌ va bhaÌvatyaÌ gnayÄ-'nnaÌpatayÄ]  15</p>
<p>ÄÌ va bhaÌvatyaÌ gnayÄ-'nnaÌpatayÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ dyaá¸¥-kÄÌ mayÄÌ tÄ-'nnaÌpati-ssyÄÌ -mityaÌ gni-mÄÌ vÄ-'nnaÌpatiÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vainaÌ -mannaÌpati-á¹karÅÌ tyannaÌpati-rÄÌ va bhaÌvatyaÌ gnayÄÌ  pavaÌmÄnÄya purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄdaÌ gnayÄÌ pÄvaÌ kÄyÄÌ gnayÄÌ  ÅuchaÌyÄÌ  jyÅgÄÌmayÄvÄ«Ì  yadaÌ gnayÄÌ  pavaÌmÄnÄya niÌ rvapaÌti prÄÌ á¹a-mÄÌ vÄ-'smiÌ -ntÄnaÌ dadhÄtiÌ  yadaÌ gnayÄÌ - [yadaÌ gnayÄÌ, pÄÌ vaÌ kÄyaÌ  vÄchaÌ-]  16</p>
<p>pÄvaÌ kÄyaÌ  vÄchaÌ-mÄÌ vÄ-'smiÌ -ntÄnaÌ dadhÄtiÌ  yadaÌ gnayÄÌ  ÅuchaÌyaÌ  ÄyuÌ-rÄÌ vÄ-'smiÌ -ntÄnaÌ dadhÄtyuÌ ta yadÄ«Ì tÄsuÌ -rbhavaÌtiÌ  jÄ«vaÌtyÄÌ vaitÄ-mÄÌ va nirvaÌpÄÌ -chchaká¹£uÌá¹£kÄmÅÌ  yadaÌ gnayÄÌ  pavaÌmÄnÄya niÌ rvapaÌti prÄÌ á¹a-mÄÌ vÄ-'smiÌ -ntÄnaÌ dadhÄtiÌ  yadaÌ gnayÄÌ pÄvaÌ kÄyaÌ  vÄchaÌ-mÄÌ vÄsmiÌ -ntÄnaÌ dadhÄtiÌ  yadaÌ gnayÄÌ  ÅuchaÌyÄÌ  chaká¹£uÌ-rÄÌ vÄsmiÌ -ntÄnaÌ dadhÄ- [chaká¹£uÌrÄÌ vÄsmiÌ -ntÄnaÌ dadhÄti, uÌ ta yadyaÌ ndhÅ]  17</p>
<p>-tyuÌ ta yadyaÌ ndhÅ bhavaÌtiÌ  praiva paÌÅyatyaÌ gnayÄÌ puÌ travaÌtÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ -dindrÄÌya puÌ triá¹ÄÌ purÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄla-mpraÌ jÄkÄÌmÅÌ -'gni-rÄÌ vÄ-'smaiÌ praÌ jÄ-mpraÌjaÌ nayaÌti vá¹Ì ddhÄ-mindraÌ á¸¥ pra yaÌchChatyaÌ gnayÄÌ  rasaÌvatÄ-'jaká¹£Ä«Ì rÄ chaÌ ru-nnirvaÌpÄÌ dyaá¸¥ kÄÌ mayÄÌtaÌ  rasaÌvÄn-thsyÄÌ -mityaÌ gni-mÄÌ va rasaÌvantaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vainaÌ gá¹Ì  rasaÌvanta-á¹karÅtiÌ  [rasaÌvanta-á¹karÅti, rasaÌvÄnÄÌ va]  18</p>
<p>rasaÌvÄnÄÌ va bhaÌvatyajaká¹£Ä«Ì rÄ bhaÌvatyÄgnÄÌ yÄ« vÄ ÄÌ á¹£Ä yadaÌ jÄ sÄÌ ká¹£ÄdÄÌ va rasaÌ mavaÌ rundhÄÌ -'gnayÄÌ  vasuÌmatÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ dyaá¸¥ kÄÌ mayÄÌtaÌ  vasuÌmÄn-thsyÄÌ mityaÌ gni-mÄÌ va vasuÌmantaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vainaÌ á¹ vasuÌmanta-á¹karÅtiÌ  vasuÌmÄnÄÌ va bhaÌvatyaÌ gnayÄÌ vÄjaÌ sá¹tÄÌ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnivaÌrpÄ-thsaá¹grÄÌ mÄ saá¹ yaÌttÄÌ  vÄjaÌ á¹- [saá¹ yaÌttÄÌ  vÄjaÌm, vÄ ÄÌ á¹£a siÌsÄ«râá¹£atiÌ ]  19</p>
<p>-à¤vÄ ÄÌ á¹£a siÌsÄ«râá¹£atiÌ  ya-ssaÌgrÄÌ mma-Ã±jigÄ«Ìá¹£atyaÌ gniá¸¥ khaluÌ  vai dÄÌ vÄnÄÌá¹ vÄjaÌ sá¹-daÌ gni-mÄÌ va vÄÌjaÌ sá¹taÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  dhÄvaÌtiÌ  vÄjaÌ gá¹Ì  hantiÌ vá¹Ì tra-Ã±jayaÌtiÌ  tagá¹ saÌgrÄÌ mma-mathÅÌ aÌ gniriÌvaÌ  na praÌtiÌ dhá¹á¹£ÄÌ bhavatyaÌ gnayÄÌ-'gniÌ vatÄÌ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ -dyasyÄÌ gnÄ- vaÌ gni- maÌbhyuÌ ddharÄÌyuÌ -rnirdiÌá¹£á¹­abhÄgÅÌ  vÄ ÄÌ tayÅÌ-raÌ nyÅ-'niÌrdiá¹£á¹­abhÄgÅÌ -'nyastau saÌ bhaá¹vaÌntauÌ  yajaÌmÄna- [yajaÌmÄnam, aÌ bhi]  20</p>
<p>-maÌ bhi sa-mbhaÌvataÌ -ssa Ä«ÌÅvaÌ ra ÄrtiÌ -mÄrtÅÌ -rya-daÌ gnayÄÌ-'gniÌ vatÄÌ niÌ rvapaÌti bhÄgaÌ dhÄyÄÌnaiÌ vainauÌ ÅamayatiÌ  nÄ-''rtiÌ mÄrchChaÌtiÌ  yajaÌmÄnÅÌ -'gnayÄÌ  jyÅtiÌá¹£matÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ -dyasyÄÌ -gniruddhá¹Ì tÅ-'huÌtÄ-'gnihÅÌ tra uÌ dvÄyÄÌ dapaÌra ÄÌ dÄ«pyÄÌ-'nÅ«Ì ddhá¹tyaÌ  ityÄÌhuÌ sta-ttathÄÌ  na kÄÌ ryaÌá¹ ya-dbhÄÌgaÌ dhÄyaÌmaÌ bhi pÅ«rvaÌ uddhriÌ yatÄÌ  kimapaÌrÅÌ -'bhyu- [kimapaÌrÅÌ -'bhyut, hriÌ yÄÌ tÄtiÌ  tÄnyÄÌ vÄ]  21</p>
<p>-ddhriÌyÄÌ tÄtiÌ  tÄnyÄÌ vÄ vaÌ ká¹£Äá¹ÄÌni sanniÌ dhÄyaÌ manthÄdiÌ taá¸¥ praÌthaÌ ma-Ã±jaÌjÃ±Ä aÌ gni-ssvÄdyÅnÄÌ radhiÌ jÄÌ tavÄÌdÄá¸¥ à¥¤ sa gÄÌyatriÌ yÄ triÌ á¹£á¹­ubhÄÌ  jagaÌtyÄ dÄÌ vÄbhyÅÌ haÌ vyaá¹ vaÌhatu prajÄÌ nannitiÌ  ChandÅÌbhi-rÄÌ vainaÌ ggÌ  svÄdyÅnÄÌ á¸¥ prajaÌnayatyÄÌ á¹£a vÄ va sÅÌ-'gnirityÄÌhuÌ  rjyÅtiÌ stvÄ aÌsyaÌ  parÄÌpatitaÌ -mitiÌ  yadaÌ gnayÄÌ  jyÅtiÌá¹£matÄ niÌ rvapaÌtiÌ  yadÄÌ vÄsyaÌ  jyÅtiÌ á¸¥ parÄÌpatitaÌ -ntadÄÌ vÄvaÌ rundhÄ à¥¥ 22 à¥¥<br/>
<b>(kaÌ rÅÌ tyaÌ nnÄÌ dÅ - daÌdhÄtiÌ  yadaÌ gnayÄÌ  - ÅuchaÌyÄÌ  chaká¹£uÌrÄÌ vÄsmiÌ -ntÄnaÌ dadhÄti -karÅtiÌ  - vÄjaÌ á¹ -à¤yajaÌmÄnaÌ  - mu - dÄÌ vÄsyaÌ  - á¹£aá¹­chaÌ) (a. 4)</b></p>
<p>vaiÌ ÅvÄÌ naÌ ra-ndvÄdaÌÅakapÄlaÌ -nnirvaÌpÄ-dvÄruÌ á¹a-Ã±chaÌ ru-ndaÌdhiÌ krÄvâá¹á¹ÄÌ chaÌ rumaÌbhiÅaÌ syamÄÌnÅÌ  ya-dvaiÌÅvÄnaÌ rÅ dvÄdaÌÅakapÄlÅÌ  bhavaÌti saá¹vathsaÌ rÅ vÄ aÌ gni rvaiÌÅvÄnaÌ ra-ssaÌá¹vathsaÌ rÄá¹aiÌ vainaggÌ svadayaÌ tyapaÌ pÄÌ paá¹ vará¹agá¹Ì hatÄ vÄruÌ á¹ÄnaiÌ vainaÌá¹ varuá¹apÄÌ ÅÄ-nmuÌÃ±chati dadhiÌ krÄvâá¹á¹ÄÌ punÄtiÌ  hiraÌá¹yaÌ -ndaká¹£iÌá¹Ä paÌ vitraÌ á¹ vai hiraÌá¹ya-mpuÌ nÄtyÄÌ vainaÌ-mÄÌ dyaÌ-maÌ syÄ-'nnaÌ-mbhavatyÄÌ tÄmÄÌ va nirvaÌpÄ-tpraÌ jÄkÄÌma-ssaá¹vathsaÌ rÅ [saá¹vathsaÌ raá¸¥, vÄ]  23</p>
<p>vÄ ÄÌ tasyÄ-'ÅÄÌmtÅÌ  yÅniÌ-mpraÌ jÄyaiÌ paÅÅ«Ì nÄ-nnirdaÌhatiÌ  yÅ-'laÌ-mpraÌ jÄyaiÌ  sa-npraÌ jÄ-nna viÌ ndatÄÌ  ya-dvaiÌÅvÄnaÌ rÅ dvÄdaÌÅakapÄlÅÌ  bhavaÌti saá¹vathsaÌ rÅ vÄ aÌ gni rvaiÌÅvÄnaÌ ra-ssaÌá¹vathsaÌ ramÄÌ va bhÄÌgaÌ dhÄyÄÌna ÅamayatiÌ  sÅÌ-'smai ÅÄÌ nta-ssvÄdyÅnÄÌá¸¥ praÌ jÄ-mprajaÌnayati vÄruÌ á¹ÄnaiÌ vainaÌá¹ varuá¹apÄÌ ÅÄ-nmuÌÃ±chati dadhiÌ krÄvâá¹á¹ÄÌ punÄtiÌ  hiraÌá¹yaÌ -ndaká¹£iÌá¹Ä paÌ vitraÌ á¹ vai hiraÌá¹ya-mpuÌ nÄtyÄÌ vainaÌá¹- [puÌ nÄtyÄÌ vainaÌm, viÌ ndatÄÌ]  24</p>
<p>-à¤viÌ ndatÄÌ praÌ jÄá¹ vaiÌÅvÄnaÌ ra-ndvÄdaÌÅakapÄlaÌ -nnirvaÌpÄ-tpuÌ trÄ jÄÌ tÄyadaÌ á¹£á¹­ÄkaÌpÄlÅÌ  bhavaÌti gÄyatriÌ yaivainaÌ-mbrahmavarchaÌ sÄnaÌ punÄtiÌ  yannavaÌkapÄla-striÌ vá¹taiÌ vÄsmiÌ -ntÄjÅÌ dadhÄtiÌ  ya-ddaÅaÌkapÄlÅ viÌ rÄjaiÌ vÄ-'smiÌ-nnaÌ nnÄdyaÌ-ndadhÄtiÌ  yadÄkÄÌdaÅakapÄla- striÌ á¹£á¹­ubhaiÌ vÄ-'smiÌ-nnindriÌ ya-ndaÌdhÄtiÌ  ya-ddvÄdaÌÅakapÄlÅÌ  jagaÌtyaiÌ vÄ-'smiÌ-npaÌ ÅÅ«-ndaÌdhÄtiÌ  yasmiÌn jÄÌ ta ÄÌ tÄmiá¹£á¹­iÌ-nniÌ rvapaÌti pÅ«Ì ta [pÅ«Ì taá¸¥, ÄÌ va tÄÌjaÌ svyaÌnnÄÌ da]  25</p>
<p>ÄÌ va tÄÌjaÌ svyaÌnnÄÌ da iÌndriyÄÌ vÄ« paÌÅuÌ mÄ-nbhaÌvaÌ tyavaÌ  vÄ ÄÌ á¹£a suÌvaÌ rgÄ-llÅÌ kÄ-chChiÌdyatÄÌ  yÅ daÌrâÅapÅ«rá¹amÄsayÄÌ jÄ« sannaÌmÄvÄÌ syÄÌá¹ vÄ paurá¹amÄÌ sÄ«á¹ vÄÌtipÄÌ dayaÌti suvaÌ rgÄyaÌ  hi lÅÌ kÄyaÌ darâÅapÅ«rá¹amÄÌ sÄ viÌ jyÄtÄÌ vaiÅvÄnaÌ ra-ndvÄdaÌÅakapÄlaÌ -nnirvaÌpÄ-damÄvÄÌ syÄÌá¹ vÄ paurá¹amÄÌ sÄ«á¹ vÄÌ-'tiÌ pÄdyaÌ saá¹vathsaÌ rÅ vÄ aÌ gni rvaiÌÅvÄnaÌ ra-ssaÌá¹vathsaÌ ramÄÌ va prÄ«Ìá¹ÄÌ tyathÅÌ saá¹vathsaÌ ramÄÌ vÄsmÄÌ  upaÌ dadhÄti suvaÌ rgasyaÌ lÅÌ kasyaÌ  samaÌá¹£á¹­yÄÌ   [samaÌá¹£á¹­yai, athÅÌ]  26</p>
<p>athÅÌ dÄÌ vatÄÌ ÄÌ vÄnvÄÌ rabhyaÌ suvaÌ rgaá¹ lÅÌ kamÄÌti vÄ«raÌ hÄ vÄ ÄÌ á¹£a dÄÌ vÄnÄÌ á¹ yÅÌ-'gni-muÌdvÄÌ sayaÌtÄÌ  na vÄ ÄÌ tasyaÌ brÄhmaÌ á¹Ä á¹ÌtÄÌ yavaÌá¸¥ puÌ rÄ-'nnaÌ-maká¹£a-nnÄgnÄÌ ya-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄ-dvaiÅvÄnaÌ ra-ndvÄdaÌÅakapÄla-maÌ gnimuÌdvÄsayiÌ á¹£yan. yadaÌ á¹£á¹­ÄkaÌpÄlÅÌ  bhavaÌtyaÌ á¹£á¹­Äká¹£aÌrÄ gÄyaÌ trÄ«-gÄÌyaÌ trÅÌ 'gni-ryÄvÄÌ-nÄÌ vÄ-'gnistasmÄÌ ÄtiÌ thya-á¹kaÌrÅÌ tyathÅÌ  yathÄÌ  janaÌá¹ yaÌ tÄÌ-'vaÌ sa-á¹kaÌ rÅtiÌ tÄÌ dá¹- [tÄÌ dá¹k, ÄÌ va]  27</p>
<p>-gÄÌ va ta-ddvÄdaÌÅakapÄlÅ vaiÅvÄnaÌ rÅ bhaÌvatiÌ  dvÄdaÌÅaÌ  mÄsÄÌ-ssaá¹vathsaÌ ra-ssaÌá¹vathsaÌ raá¸¥ khaluÌ  vÄ aÌ gnÄryÅniÌ -ssvÄmÄÌ vainaÌ á¹ yÅniÌ-á¹gamaya-tyÄÌ dyaÌmaÌ syÄnnaÌ-mbhavati vaiÅvÄnaÌ ra-ndvÄdaÌÅakapÄlaÌ -nnirvaÌpÄnmÄruÌ tagá¹ saÌ ptakaÌpÄlaÌ -á¹grÄmaÌkÄma ÄhavaÌ nÄ«yÄÌ vaiÅvÄnaÌ ramadhiÌ ÅrayatiÌ  gÄrâhaÌpatyÄ mÄruÌ ta-mpÄÌpavasyaÌ sasyaÌ  vidhá¹ÌtyaiÌ  dvÄdaÌÅakapÄlÅ vaiÅvÄnaÌ rÅ bhaÌvatiÌ  dvÄdaÌÅaÌ  mÄsÄÌ-ssaá¹vathsaÌ ra-ssaÌá¹vathsaÌ rÄá¹aiÌ vÄsmaiÌ sajÄÌ tÄgâÅchyÄÌvayati mÄruÌ tÅ bhaÌvati [  ]  28</p>
<p>maÌ rutÅÌ  vai dÄÌ vÄnÄÌ á¹ viÅÅÌ dÄvaviÌ ÅÄnaiÌ vÄ-'smaiÌ manuá¹£ya viÌ ÅamavaÌ rundhÄ saÌ ptakaÌpÄlÅ bhavati saÌ pta gaÌá¹ÄÌ  vai maÌ rutÅÌ gaá¹aÌ Åa ÄÌ vÄsmaiÌ sajÄÌ tÄnavaÌ rundhÄ 'nÅ«Ì chyamÄÌnaÌ  Ä sÄÌdayatiÌ  viÅaÌmÄÌ vÄsmÄÌ  anuÌvartmÄna-á¹karÅti à¥¥ 29 à¥¥<br/>
<b>(praÌ jÄkÄÌma-ssaá¹vathsaÌ raá¸¥ - puÌ nÄtyÄÌ vainaÌá¹ - pÅ«Ì taá¸¥ - samaÌá¹£á¹­yai -tÄÌ dá¹á¹ - mÄÌruÌ tÅ bhaÌvaÌ  - tyÄkÄÌ nna triÌ gá¹Ì ÅachchaÌ ) (a. 5)</b></p>
<p>ÄÌ diÌ tya-Ã±chaÌ ru-nnirvaÌpÄ-thsaá¹grÄÌ ma-muÌpaprayÄÌ sya-nniÌ yaá¹ vÄ adiÌti-raÌ syÄmÄÌ va pÅ«rvÄÌ  pratiÌtiá¹£á¹­hanti vaiÅvÄnaÌ ra-ndvÄdaÌÅakapÄlaÌ -nnirvaÌpÄ-dÄÌ yataÌna-á¹gaÌ tvÄ-saÌá¹vathsaÌ rÅ vÄ aÌ gni rvaiÌÅvÄnaÌ ra-ssaÌá¹vathsaÌ raá¸¥ khaluÌ  vai dÄÌ vÄnÄÌ-mÄÌ yataÌna-mÄÌ tasmÄÌ dvÄ ÄÌ yataÌnÄ-ddÄÌ vÄ asuÌrÄ-najayaÌ nÌ . ya-dvaiÌÅvÄnaÌ ra-ndvÄdaÌÅakapÄla-nniÌ rvapaÌti dÄÌ vÄnÄÌ-mÄÌ vÄ-''yataÌnÄ yatatÄÌ  jayaÌtiÌ  tagá¹ saÌgrÄÌ mma-mÄÌ tasmiÌ n vÄ ÄÌ tau má¹ÌjÄtÄÌ  [ÄÌ tau má¹ÌjÄtÄ, yÅ viÌdviá¹£ÄÌ á¹ayÅÌ -rannaÌ -mattiÌ]  à¥¥ 30 à¥¥</p>
<p>yÅ viÌdviá¹£ÄÌ á¹ayÅÌ -rannaÌ -mattiÌ vaiÅvÄnaÌ ra-ndvÄdaÌÅakapÄlaÌ -nnirvaÌpÄ-dvidviá¹£ÄÌ á¹ayÅÌ rannaÌ-Ã±jaÌ gdhvÄ saÌá¹vathsaÌ rÅ vÄ aÌ gni-rvaiÌÅvÄnaÌ ra-ssaÌá¹vathsaÌ ra svaÌdita-mÄÌ vÄ-'ttiÌ  nÄsmiÌ-nmá¹jÄtÄ saá¹vathsaÌ rÄyaÌ  vÄ ÄÌ tau samaÌmÄtÄÌ  yau saÌmaÌ mÄtÄÌ  tayÅÌ ryaá¸¥ pÅ«rvÅÌ-'bhiÌ druhyaÌtiÌ  taá¹ varuÌá¹Å gá¹há¹Äti vaiÅvÄnaÌ ra-ndvÄdaÌÅakapÄlaÌ -nnirvaÌpÄ-thsamamÄÌ nayÅÌ á¸¥ pÅ«rvÅÌ-'bhiÌ druhyaÌ saá¹vathsaÌ rÅ vÄ aÌ gni-rvaiÌÅvÄnaÌ ra-ssaÌá¹vathsaÌ ra-mÄÌ vÄ-''ptvÄ niÌrvaruÌ á¹aá¹- [niÌrvaruÌ á¹am, paÌ rastÄÌ-daÌ bhi]  à¥¥ 31 à¥¥</p>
<p>-paÌ rastÄÌ-daÌ bhi druÌhyatiÌ  nainaÌ á¹ varuÌá¹Å gá¹há¹ÄtyÄÌ vyaÌá¹ vÄ ÄÌ á¹£a pratiÌ gá¹há¹ÄtiÌ  yÅ-'viÌ-mpratigá¹Ì há¹ÄtiÌ vaiÅvÄnaÌ ra-ndvÄdaÌÅakapÄlaÌ -nnirvaÌpÄÌ daviÌ-mpratiÌ gá¹hyaÌ saá¹vathsaÌ rÅ vÄ aÌ gni-rvaiÌÅvÄnaÌ ra-ssaÌá¹vathsaÌ ra-svaÌditÄmÄÌ va pratiÌgá¹há¹ÄtiÌ  nÄ-''vyaÌ-mpratiÌgá¹há¹ÄtyÄÌ tmanÅÌ  vÄ ÄÌ á¹£a mÄtrÄÌmÄpnÅtiÌ  ya uÌbhaÌ yÄdaÌ-tpratigá¹Ì há¹ÄtyaÅvaÌá¹ vÄÌ  puruÌá¹£aá¹ vÄ vaiÅvÄnaÌ ra-ndvÄdaÌÅakapÄlaÌ -nnirvaÌpÄ-dubhaÌ yÄdaÌ- [nirvaÌpÄ-dubhaÌ yÄdaÌt, praÌ tiÌ gá¹hyaÌ]  à¥¥ 32 à¥¥</p>
<p>-tpratiÌ gá¹hyaÌ saá¹vathsaÌ rÅ vÄ aÌ gnirvaiÌÅvÄnaÌ ra-ssaÌá¹vathsaÌ ra-svaÌditamÄÌ va pratiÌ gá¹há¹ÄtiÌ  nÄtmanÅÌ  mÄtrÄÌmÄpnÅti vaiÅvÄnaÌ ra-ndvÄdaÌÅakapÄlaÌ -nnirvaÌpÄ-thsaÌ ni-mÄÌ á¹£yan-thsaÌá¹vathsaÌ rÅ vÄ aÌ gni-rvaiÌÅvÄnaÌ rÅ yaÌ dÄ khaluÌ  vai saÌá¹vathsaÌ ra-Ã±jaÌ natÄÌyÄÌ -Ã±charaÌ tyathaÌ  sa dhaÌnÄÌ rghÅ bhaÌvatiÌ ya-dvaiÌÅvÄnaÌ ra-ndvÄdaÌÅakapÄla-nniÌ rvapaÌti saá¹vathsaÌ ra-sÄÌtÄmÄÌ va saÌ nimaÌ bhi prachyaÌvatÄÌ  dÄnaÌkÄmÄ asmai praÌ jÄ bhaÌvantiÌ  yÅ vai saÌá¹vathsaÌ raá¹- [vai saÌá¹vathsaÌ ram, praÌ yujyaÌ  na]  à¥¥ 33 à¥¥</p>
<p>-praÌ yujyaÌ  na viÌmuÌ Ã±chatyaÌpratiá¹£á¹­hÄÌ nÅ vai sa bhaÌvatyÄÌ ta-mÄÌ va vaiÌÅvÄnaÌ ra-mpunaÌrÄÌ gatyaÌ  nirvaÌpÄÌ dya-mÄÌ va praÌyuÌ á¹ktÄ ta-mbhÄÌgaÌ dhÄyÄÌnaÌ  vi muÌÃ±chatiÌ  pratiÌá¹£á¹­hityaiÌ  yayÄÌ  rajvÅÌttaÌ mÄ-á¹gÄmÄÌ jÄ-ttÄ-mbhrÄtá¹ÌvyÄyaÌ  pra hiÌá¹uyÄÌ -nnir-á¹Ìti-mÄÌ vÄsmaiÌ  pra hiÌá¹Åti à¥¥ 34 à¥¥<br/>
<b>(má¹Ì jÄÌ tÄÌ  - niÌ rvaÌ ruÌ á¹aá¹ - à¤vaÌpÄdubhaÌ yÄdaÌ --dyÅ vai saÌá¹vathsaÌ ragá¹ - á¹£aá¹­trigá¹ÌÅachcha) (a. 6)</b></p>
<p>aiÌ ndra-Ã±chaÌ ru-nnirvaÌpÄ-tpaÌ ÅukÄÌma aiÌ ndrÄ vai paÌ ÅavaÌ  indraÌmÄÌ va svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄsmaiÌ paÌ ÅÅ«-nprayaÌchChati paÅuÌ mÄ-nÄÌ va bhaÌvati chaÌ rurbhaÌvatiÌ  svÄdÄÌ vÄsmaiÌ  yÅnÄÌá¸¥ paÌ ÅÅ«-nprajaÌnayaÌ tÄ«ndrÄÌyÄndriÌ yÄvaÌtÄ purÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄ-tpaÌ ÅukÄÌma indriÌ yaá¹ vai paÌ ÅavaÌ  indraÌ-mÄÌ vÄndriÌ yÄvaÌntaÌ ggÌ  svÄna ÌbhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa [dhÄvatiÌ  saá¸¥, ÄÌ vÄ-'smÄÌ]  à¥¥ 35 à¥¥</p>
<p>ÄÌ vÄ-'smÄÌ indriÌ ya-mpaÌ ÅÅ«-nprayaÌchChati paÅuÌ mÄnÄÌ va bhaÌvaÌ tÄ«ndrÄÌya-ghaÌ rmavaÌtÄ purÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄ-dbrahmavarchaÌ sakÄÌmÅ brahmavarchaÌ saá¹ vai ghaÌ rma indraÌmÄÌ va ghaÌ rmavaÌntaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄsmiÌ-nbrahmavarchaÌ sa-ndaÌdhÄti brahmavarchaÌ syÄÌva bhaÌvaÌ tÄ«ndrÄÌyÄÌ -'rkavaÌtÄ purÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄÌ -dannaÌkÄmÅÌ -'rkÅ vai dÄÌ vÄnÄÌ -mannaÌ -mindraÌ-mÄÌ vÄ-'rkavaÌntaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅ- [svÄnaÌ bhÄgaÌ dhÄyÄÌna, upaÌ dhÄvatiÌ  sa]  à¥¥ 36à¥¥</p>
<p>-paÌ dhÄvatiÌ  sa ÄÌ vÄsmÄÌ  annaÌ -mprayaÌchChatyannÄÌ da ÄÌ va bhaÌvaÌ tÄ«ndrÄÌya ghaÌ rmavaÌtÄ purÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄÌ -dindrÄÌyÄ-ndriÌ yÄvaÌtaÌ  indrÄÌyÄÌ -'rkavaÌtÄÌ  bhÅ«tiÌkÄmÅÌ  yadindrÄÌya ghaÌ rmavaÌtÄ niÌ rvapaÌtiÌ  ÅiraÌ ÄÌ vÄsyaÌ  tÄnaÌ karÅtiÌ  yadindrÄÌyÄndriÌ yÄvaÌta ÄÌ tmÄnaÌ-mÄÌ vÄsyaÌ  tÄnaÌ karÅtiÌ -ya-dindrÄÌyÄÌ -'rkavaÌtÄ bhÅ«Ì ta ÄÌ vÄnnÄdyÄÌ  pratiÌ-tiá¹£á¹­hatiÌ  bhavaÌtyÄÌ vÄndrÄÌyÄ- [bhavaÌtyÄÌ vÄndrÄÌyÄ, aÌ gá¹Ì  hÅÌ muchÄÌ]  à¥¥ 37 à¥¥</p>
<p>-'gá¹ hÅÌ muchÄÌ purÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄÌ dyaá¸¥ pÄÌ pmanÄÌ gá¹hÄ«Ì ta-ssyÄ-tpÄÌ pmÄ vÄ agá¹haÌ  indraÌmÄÌ vÄ-'gá¹ hÅÌ muchaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vainaÌ-mpÄÌ pmanÅ-'gá¹haÌsÅ muÃ±chaÌ tÄ«ndrÄÌya vaimá¹Ì dhÄyaÌ purÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄÌ dya-mmá¹dhÅÌ -'bhi praÌ vÄpÄÌran-rÄÌ á¹£á¹­rÄá¹iÌ vÄÌ -'bhi saÌmiÌ yu-rindraÌ-mÄÌ va vaiÌmá¹Ì dhaggâ svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄ-'smÄÌ nmá¹dhÅ- [ÄÌ vÄ-'smÄÌ nmá¹dhaÌá¸¥, apaÌ haÌ ntÄ«ndrÄÌya]  à¥¥ 38 à¥¥</p>
<p>-'paÌ haÌ ntÄ«ndrÄÌya trÄÌ trÄ puÌrÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄ-dbaÌ ddhÅ vÄÌ  pariÌyattÅÌ  vÄndraÌmÄÌ va trÄÌ tÄraÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vainaÌ-ntrÄyataÌ  indrÄÌyÄ-'rkÄÅvamÄÌ dhavaÌtÄ purÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄÌ dya-mmaÌhÄyaÌ jÃ±Å nÅpaÌ namÄÌdÄÌ tÄ vai maÌhÄyaÌ jÃ±asyÄ-'ntyÄÌ taÌ nÅ« ya-daÌrkÄÅvamÄÌ dhÄ-vindraÌ-mÄÌ vÄ-'rkÄÌÅvamÄÌ dha- vaÌntaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄsmÄÌ antaÌ tÅ maÌhÄyaÌ jÃ±a-Ã±chyÄÌvayaÌ tyupaiÌna-mmahÄyaÌ jÃ±Å naÌmati à¥¥ 39 à¥¥<br/>
<b>(iÌ ndriÌ yÄvaÌntaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sÅÌ - 'rkavaÌntaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌnaiÌ  - vÄndrÄÌyÄ - smÄÌ -nmá¹dhÅÌ - 'smai - saÌ pta chaÌ ) (a. 7)</b></p>
<p>indrÄÌ yÄ-'nvá¹ÌjavÄ purÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄÌ -dgrÄmaÌkÄmaÌ  indraÌ-mÄÌ vÄ-'nvá¹ÌjuÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄsmaiÌ sajÄÌ tÄ-nanuÌkÄn karÅti grÄÌ myÄÌva bhaÌvatÄ«ndrÄÌ á¹yai chaÌ ru-nnirvaÌpÄÌ dyasyaÌ  sÄnÄ-'sagá¹ÌÅitÄvaÌ  syÄ-diÌndrÄÌ á¹Ä« vai sÄnÄÌyai dÄÌ vatÄÌmdrÄÌ á¹Ä«-mÄÌ va svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  saivÄsyaÌ  sÄnÄÌ gá¹Ì  saggâ ÅyaÌtiÌ  balbaÌjÄÌ napÄ«Ì -  [balbaÌjÄÌ napiÌ, iÌ ddhmÄ sa-nnaÌhyÄÌ dgau-]  à¥¥ 40 à¥¥</p>
<p>-ddhmÄ sa-nnaÌhyÄÌ dgau-ryatrÄ-'dhiÌá¹£kannÄÌ -nyamÄÌhaÌ -ttatÅÌ  balbaÌjÄÌ  udaÌtiá¹£á¹­haÌ -ngavÄÌ-mÄÌ vainaÌ-nnyÄÌ ya-maÌpiÌ nÄ«yaÌ  gÄ vÄÌdayaÌ tÄ«ndrÄÌya manyuÌ matÄÌ  manaÌsvatÄ purÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄ-thsaá¹grÄÌ mÄ saá¹yaÌtta indriÌ yÄá¹aÌ  vai maÌ nyunÄÌ  manaÌsÄ saá¹grÄÌ ma-Ã±jaÌyaÌ tÄ«ndraÌ-mÄÌ va maÌnyuÌ mantaÌ -mmanaÌsvantaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄsmiÌnnindriÌ ya-mmaÌ nyu-mmanÅÌ dadhÄtiÌ  jayaÌtiÌ  tagá¹ [jayaÌtiÌ  tam, saÌ grÄÌ ma-mÄÌ tÄ-mÄÌ va]  à¥¥ 41 à¥¥</p>
<p>saÌgrÄÌ ma-mÄÌ tÄ-mÄÌ va nirvaÌpÄÌ dyÅ haÌ tamaÌnÄ-ssvaÌ ya-mpÄÌpa ivaÌ  syÄdÄÌ tÄniÌ  hi vÄ ÄÌ tasmÄÌ  dapaÌkrÄntÄÌ nyathaiÌ á¹£a haÌ tamaÌnÄ-ssvaÌ ya-mpÄÌpaÌ  indraÌmÄÌ va maÌnyuÌ mantaÌ -mmanaÌsvantaÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄsmiÌ-nnindriÌ ya-mmaÌ nyu-mmanÅÌ dadhÄtiÌ  na haÌ tamaÌnÄ-ssvaÌ ya-mpÄÌpÅ bhavaÌ tÄ«ndrÄÌya dÄÌ trÄ puÌrÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄÌ dyaá¸¥ kÄÌ mayÄÌtaÌ  dÄnaÌkÄmÄ mÄ praÌ jÄ-ssyuÌ - [dÄnaÌkÄmÄ mÄ praÌ jÄ-ssyuÌá¸¥, itÄ«ndraÌ-mÄÌ va]  à¥¥ 42 à¥¥</p>
<p>-ritÄ«ndraÌ-mÄÌ va dÄÌ tÄraÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄsmaiÌ  dÄnaÌkÄmÄá¸¥ praÌ jÄá¸¥ kaÌrÅtiÌ  dÄnaÌkÄmÄ asmai praÌ jÄ bhaÌvaÌ ntÄ«ndrÄÌya pradÄÌ trÄ puÌrÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄÌ -dyasmaiÌ  prattaÌmivaÌ  sanna praÌdÄ«Ì yÄtÄndraÌ-mÄÌ va praÌdÄÌ tÄraÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ-dhÄvatiÌ  sa ÄÌ vÄsmaiÌ  pra-dÄÌpayaÌ tÄ«ndrÄÌya suÌ trÄmá¹ÄÌ purÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄÌ -dapaÌruddhÅ vÄ- [-dapaÌruddhÅ vÄ, aÌ paÌ ruÌ ddhayamÄÌnÅÌ ]  à¥¥ 43 à¥¥</p>
<p>-'paruÌ ddhayamÄÌnÅÌ  vÄndraÌmÄÌ va suÌ trÄmÄÌá¹aÌ ggÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vainaÌ-ntrÄyatÄ 'naparuÌ ddhyÅ bhaÌvaÌ tÄ«ndrÅÌ  vai saÌ dá¹-ndÄÌ vatÄÌbhirÄsÄ«Ì -thsa na vyÄÌ vá¹taÌmagachChaÌ -thsa praÌ jÄpaÌtiÌ -mupÄÌdhÄvaÌ -ttasmÄÌ ÄÌ ta-maiÌ ndra-mÄkÄÌdaÅakapÄlaÌ -nniraÌvapaÌ -ttÄnaiÌ -vÄ-'smiÌ-nnindriÌ ya-maÌdadhÄÌ -chChakvaÌrÄ« yÄjyÄnuvÄÌ kyÄÌ akarÅÌ -dvajrÅÌ  vai ÅakvaÌrÄ«Ì  sa ÄÌnaÌ á¹ vajrÅÌ  bhÅ«tyÄÌ aindhaÌ - [bhÅ«tyÄÌ aindha, sÅÌ-'bhavaÌ -thsÅÌ-'bibhÄ-]  à¥¥ 44 à¥¥</p>
<p>-sÅÌ-'bhavaÌ thsÅÌ-'bibhÄ-dbhÅ«Ì taá¸¥ pra mÄÌ dhaká¹£yaÌ tÄ«tiÌ  sa praÌ jÄpaÌtiÌ -mpunaÌ rupÄÌ-'dhÄvaÌ -thsa praÌ jÄpaÌtiÌ -ÅÅakvaÌryÄÌ  adhiÌ rÄÌ vatÄ«Ì -nniraÌmimÄ«taÌ  ÅÄntyÄÌ  apraÌdÄhÄyaÌ  yÅ-'laggÌ ÅriÌ yai san-thsaÌ dá¹á¹khsaÌmÄÌ nai-ssyÄ-ttasmÄÌ ÄÌ ta-maiÌ ndra-mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄÌ -dindraÌmÄÌ va svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  sa ÄÌ vÄ-'smiÌ-nnindriÌ ya-ndaÌdhÄti rÄÌ vatÄ«Ì purÅnuvÄÌ kyÄÌ bhavatiÌ  ÅÄntyÄÌ  apraÌdÄhÄyaÌ  ÅakvaÌrÄ« yÄÌ jyÄÌ vajrÅÌ  vai ÅakvaÌrÄ«Ì sa ÄÌnaÌ á¹ vajrÅÌ  bhÅ«tyÄÌ indhÄÌ  bhavaÌtyÄÌ va à¥¥ 45 à¥¥<br/>
<b>(apiÌ  - taggâ - syuÌ - rvai - ndha - bhavatiÌ  - chatuÌrdaÅa cha ) (a. 8)</b></p>
<p>ÄÌ gnÄÌ -vaiÌ á¹£á¹aÌ va-mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄ-dabhiÌ charaÌ n-thsaraÌsvaÌ tyÄjyaÌ bhÄgÄÌ  syÄ-dbÄÌrâhaspaÌ t yaÅchaÌ ruryadÄÌgnÄ-vaiá¹£á¹aÌ va ÄkÄÌdaÅakapÄlÅÌ  bhavaÌtyaÌ gni-ssarvÄÌ dÄÌ vatÄÌ  viá¹£á¹uÌryaÌ jÃ±Å dÄÌ vatÄÌbhi-ÅchaiÌ vainaÌá¹ yaÌ jÃ±ÄnaÌ chÄÌ bhi chaÌratiÌ -saraÌsvaÌ tyÄjyaÌbhÄgÄ bhavatiÌ  vÄgvai saraÌsvatÄ« vÄÌ chaivainaÌ-maÌ bhi chaÌrati bÄrâhaspaÌ tya-ÅchaÌ ru rbhaÌvatiÌ  brahmaÌ  vai dÄÌ vÄnÄÌ -mbá¹haÌ spatiÌ  rbrahmaÌá¹aiÌ vainaÌ-maÌ bhi chaÌratiÌ  [-maÌ bhi chaÌrati, pratiÌ  vai]  à¥¥ 46 à¥¥</p>
<p>pratiÌ  vai paÌ rastÄÌ-dabhiÌ charaÌnta-maÌ bhi chaÌrantiÌ  dvÄdvÄÌ purÅ-'nuvÄÌ kyÄÌ kuryÄÌ datiÌ  prayuÌktyÄ ÄÌ tayaiÌ va yaÌjÄtÄbhi chaÌ ryamÄÌá¹Å dÄÌ vatÄÌbhi-rÄÌ va dÄÌ vatÄÌá¸¥ pratiÌ charaÌti yaÌ jÃ±ÄnaÌ yaÌ jÃ±aá¹ vÄÌ chÄ vÄchaÌ -mbrahmaÌá¹ÄÌ  brahmaÌ  sa dÄÌ vatÄÌÅchaiÌ va yaÌ jÃ±a-Ã±chaÌ maddhyaÌ tÅ vyavaÌsarpatiÌ  tasyaÌ  na kutaÌ-ÅchaÌ nÅpÄÌvyÄÌ dhÅ bhaÌvatiÌ  nainaÌ-mabhiÌ charanÌ-thstá¹á¹uta ÄgnÄvaiá¹£á¹aÌ va-mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄÌ dyaá¹ yaÌ jÃ±Å nÅ- [-yaÌ jÃ±Å na, uÌ paÌ namÄÌdaÌ gni-ssarvÄÌ]  à¥¥ 47 à¥¥</p>
<p>-paÌ namÄÌdaÌ gni-ssarvÄÌ dÄÌ vatÄÌ  viá¹£á¹uÌ-ryaÌ jÃ±ÅÌ-'gni-Ã±chaiÌ va viá¹£á¹uÌ-Ã±chaÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  tÄvÄÌ vÄsmaiÌ yaÌ jÃ±a-mprayaÌchChataÌ  upaiÌnaá¹ yaÌ jÃ±Å naÌmatyÄgnÄ- vaiá¹£á¹aÌ va-á¹ghá¹Ì tÄ chaÌ ru-nnirvaÌpÄÌ chchaká¹£uÌá¹£kÄmÅÌ -'gnÄrvai chaká¹£uÌá¹£Ä manuÌ á¹£yÄÌ vi paÌÅyanti yaÌ jÃ±asyaÌ dÄÌ vÄ aÌ gni-Ã±chaiÌ va viá¹£á¹uÌ-Ã±chaÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  tÄvÄÌ vÄ- [tÄvÄÌ va, aÌ smiÌ n chaká¹£uÌrdhattaÌ -]  à¥¥ 48 à¥¥</p>
<p>-'smiÌ n chaká¹£uÌ-rdhattaÌ -Åchaká¹£uÌá¹£mÄ-nÄÌ va bhaÌvati dhÄÌ nvai vÄ ÄÌ ta-drÄtÅÌ  yadÄjyaÌ-manaÌ á¸uhaÌ-staá¹á¸uÌ lÄ miÌthuÌ nÄ-dÄÌ vÄsmaiÌ  chaká¹£uÌ á¸¥ prajaÌnayati ghá¹Ì tÄ bhaÌvatiÌ  tÄjÅÌ  vai ghá¹Ì ta-ntÄjaÌ Åchaká¹£uÌ -stÄjaÌsaiÌ vÄsmaiÌ  tÄjaÌ -Åchaká¹£uÌ ravaÌ rundha indriÌ yaá¹ vai vÄ«Ì ryaÌá¹ vá¹á¹ktÄÌ  bhrÄtá¹ÌvyÅÌ  yajaÌmÄÌ nÅ-'yaÌjamÄnasyÄ-dhvaÌ rakaÌlpÄÌ -mpratiÌ  nirvaÌpÄÌ -dbhrÄtá¹ÌvyÄÌ  yajaÌmÄnÄÌ  nÄ-'syÄÌmdriÌ yaá¹- [nÄ-'syÄÌmdriÌ yam, vÄ«Ì ryaá¹Ì à¤vá¹á¹ktÄ]  à¥¥ 49 à¥¥</p>
<p>-à¤vÄ«Ì ryaá¹Ì à¤vá¹á¹ktÄ puÌ rÄvÄÌ chaá¸¥ pravaÌditÅÌ -rnirvaÌpÄÌ -dyÄvaÌtyÄÌ va vÄ-ktÄmaprÅÌditÄÌ -mbhrÄtá¹Ìvyasya vá¹á¹ktÄÌ  tÄmaÌsyaÌ  vÄchaÌ-mpraÌ vadaÌntÄ«-maÌ nyÄ vÄchÅ-'nuÌ  pravaÌdantiÌ  tÄ iÌndriÌ yaá¹ vÄ«Ì ryaÌá¹ yajaÌmÄnÄ dadhatyÄgnÄ vaiá¹£á¹aÌ va-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄ-tprÄta-ssavanaÌ syÄÌ-'' kÄÌ lÄ saraÌsvaÌ tyÄjyaÌbhÄgÄÌ  syÄ-dbÄÌrâhaspaÌ tyaÅchaÌ ru- ryadaÌ á¹£á¹­ÄkaÌpÄlÅÌ  bhavaÌtyaÌ á¹£á¹­Äká¹£aÌrÄ gÄyaÌ trÄ« gÄÌyaÌ tra-mprÄÌta-ssavaÌ na-mprÄÌta-ssavaÌ namÄÌ va tÄnÄÌ-''pnÅ- [tÄnÄÌ-''pnÅti, ÄÌ gnÄÌ vaiÌ á¹£á¹aÌ va-]  à¥¥ 50 à¥¥</p>
<p>-tyÄgnÄvaiá¹£á¹aÌ va-mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄÌ -nmÄddhyaÌndinasyaÌ  savaÌnasyÄ-'' kÄÌ lÄ saraÌsvaÌ tyÄjyaÌbhÄgÄÌ  syÄ-dbÄÌrâhaspaÌ tya-ÅchaÌ ru ryadÄkÄÌdaÅakapÄlÅÌ  bhavaÌ tyÄkÄÌdaÅÄká¹£arÄ triÌ á¹£á¹­u-ptraiá¹£á¹­uÌbhaÌ -mmÄddhyaÌndinaÌ gá¹Ì  savaÌnaÌ -mmÄddhyaÌdinnamÄÌ va savaÌnaÌ -ntÄnÄÌ-''pnÅtyÄgnÄvaiá¹£á¹aÌ va-ndvÄdaÌÅakapÄlaÌ -nnirvaÌpÄ-ttá¹tÄ«yasavaÌ nasyÄÌ-''kÄÌ lÄ saraÌsvaÌ tyÄjyaÌbhÄgÄÌ  syÄ-dbÄÌrâhaspaÌ tya-ÅchaÌ rurya-ddvÄdaÌÅakapÄlÅÌ  bhavaÌtiÌ  dvÄdaÌÅÄká¹£arÄÌ  jagaÌtÄ«Ì  jÄgaÌta-ntá¹tÄ«yasavaÌ na-ntá¹ÌtÄ«ya savaÌ namÄÌ va tÄnÄÌ-''pnÅti dÄÌ vatÄÌbhirÄÌ va dÄÌ vatÄÌá¸¥ [dÄÌ vatÄÌá¸¥, praÌ tiÌ charaÌti]  à¥¥ 51 à¥¥</p>
<p>pratiÌ charaÌti yaÌ jÃ±ÄnaÌ yaÌ jÃ±aá¹ vÄÌ chÄ vÄchaÌ -mbrahmaÌá¹ÄÌ  brahmaÌ kaÌ pÄlaiÌrÄÌ va ChandÄgÌsyÄÌ pnÅtiÌ purÅÌ á¸ÄÅaiÌ -ssavaÌnÄni maitrÄvaruÌ á¹a-mÄkaÌkapÄlaÌ -nnirvaÌpÄ-dvaÌ ÅÄyaiÌ kÄÌ lÄ yaivÄsau bhrÄtá¹Ìvyasya vaÌ ÅÄ-'nÅ«ÌbaÌ ndhyÄÌ sÅ ÄÌ vaiá¹£aitasyaikaÌkapÄlÅ bhavatiÌ  na hi kaÌ pÄlaiÌá¸¥ paÌ Åu-marâhaÌ tyÄptuÌm à¥¥ 52 à¥¥<br/>
<b>(brahmaÌá¹aiÌ vainaÌmaÌ bhi chaÌrati - yaÌ jÃ±Å na - tÄvÄÌ vÄ - 'syÄÌmdriÌ ya - mÄÌpnÅti -dÄÌ vatÄÌá¸¥ - saÌ ptatrigá¹ÌÅachcha ) (a. 9)</b></p>
<p>aÌ sÄvÄÌdiÌ tyÅ na vyaÌrÅchataÌ  tasmaiÌ dÄÌ vÄá¸¥ prÄyaÌÅchitti-maichChaÌ -ntasmÄÌ ÄÌ tagá¹ sÅÌmÄrauÌ dra-Ã±chaÌ ru-nniraÌvapaÌ -ntÄnaiÌ vÄsmiÌ -nruchaÌmadadhuÌ ryÅ braÌhmavarchaÌ sakÄÌmaÌ -ssyÄ-ttasmÄÌ ÄÌ tagá¹ sÅÌmÄrauÌ dra-Ã±chaÌ ru-nnirvaÌpÄÌ -thsÅmaÌ-Ã±chaiÌ va ruÌ dra-Ã±chaÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  tÄvÄÌ vÄsmiÌ-nbrahmavarchaÌ sa-ndhaÌttÅ brahmavarchaÌ syÄÌva bhaÌvati tiá¹£yÄpÅ«rá¹amÄÌ sÄ nirvaÌpÄdruÌ drÅ [nirvaÌpÄdruÌ draá¸¥, vai tiÌ á¹£yaÌ-ssÅmaÌá¸¥]  à¥¥ 53 à¥¥</p>
<p>vai tiÌ á¹£yaÌ-ssÅmaÌá¸¥ pÅ«Ì rá¹amÄÌsa-ssÄÌ ká¹£ÄdÄÌ va braÌhmavarchaÌ samavaÌ rundhÄÌ  pariÌÅritÄ yÄjayati brahmavarchaÌ sasyaÌ  pariÌgá¹hÄ«tyai ÅvÄÌ tÄyaiÌ ÅvÄÌ tavaÌthsÄyai duÌ gdha-mmaÌthiÌ tamÄjyaÌ-mbhavaÌ tyÄjyaÌ -mprÅká¹£aÌá¹aÌ mÄjyÄÌna mÄrjayantÄÌ  yÄvaÌdÄÌ va braÌhmavarchaÌ sa-nta-thsarvaÌ-á¹karÅÌ tyatiÌ brahmavarchaÌ sa-á¹kriÌyataÌ  ityÄÌhurÄ«ÅvaÌ rÅ duÌ ÅcharmÄÌ  bhaviÌtÅÌ ritiÌ mÄnaÌ vÄ« á¹chauÌ dhÄÌ yyÄÌ kuryÄÌ -dyadvai kiÃ±chaÌ  manuÌ -ravaÌdaÌ tta-dbhÄÌá¹£aÌ jaá¹- [-dbhÄÌá¹£aÌ jam, bhÄÌ á¹£aÌ ja-mÄÌ vÄ-'smaiÌ]  à¥¥ 54 à¥¥</p>
<p>-bhÄÌá¹£aÌ ja-mÄÌ vÄ-'smaiÌ karÅtiÌ  yadiÌ bibhÄ«Ì yÄ-dduÌ ÅcharmÄÌ bhaviá¹£yÄÌ mÄ«tiÌ sÅmÄpauÌ á¹£á¹a-Ã±chaÌ ru-nnirvaÌpÄ-thsauÌ myÅ vai dÄÌ vataÌyÄÌ  puruÌá¹£aá¸¥ pauÌ á¹£á¹Äá¸¥ paÌ ÅavaÌ -ssvayaiÌ  vÄsmaiÌ dÄÌ vataÌyÄ paÌ ÅubhiÌ -stvachaÌ-á¹karÅtiÌ  na duÌ ÅcharmÄÌ bhavati sÅmÄrauÌ dra-Ã±chaÌ ru-nnirvaÌpÄ-tpraÌ jÄkÄÌmaÌ -ssÅmÅÌ  vai rÄÌtÅÌ dhÄ aÌ gniá¸¥ praÌ jÄnÄÌ-mprajanayiÌ tÄ sÅmaÌ ÄÌ vÄsmaiÌ  rÄtÅÌ  dadhÄÌtyaÌ gniá¸¥ praÌ jÄ-mprajaÌnayati viÌ ndatÄÌ - [  ]  à¥¥ 55 à¥¥</p>
<p>praÌ jÄgá¹ sÅÌmÄrauÌ dra-Ã±chaÌ ru-nnirvaÌpÄ-dabhiÌ charanÌ-thsauÌ myÅ vai dÄÌ vataÌyÄÌ  puruÌá¹£a ÄÌ á¹£a ruÌ drÅ yadaÌ gni-ssvÄyÄÌ ÄÌ vainaÌ-ndÄÌ vatÄÌyai niÌ á¹£krÄ«yaÌ ruÌ drÄyÄpiÌ dadhÄti tÄÌ jagÄrtiÌ -mÄrchChaÌti sÅmÄrauÌ dra-Ã±chaÌ ru-nnirvaÌpÄÌ -jjyÅgÄÌmayÄvÄ«Ì  sÅmaÌ á¹ vÄ ÄÌ tasyaÌ  rasÅÌ gachChatyaÌ gnigá¹ ÅarÄ«ÌraÌ á¹ yasyaÌ  jyÅgÄÌ mayaÌtiÌ  sÅmÄÌdÄÌ vÄsyaÌ  rasaÌ-nniá¹£krÄ«Ì á¹ÄtyaÌ gnÄ-ÅÅarÄ«ÌramuÌ ta yadÄ«Ì - [yadiÌ, iÌ tÄsuÌ  rbhavaÌtiÌ ]  à¥¥ 56 à¥¥</p>
<p>-tÄsuÌ  rbhavaÌtiÌ  jÄ«vaÌtyÄÌ va sÅÌmÄruÌ drayÅÌ rvÄ ÄÌ ta-á¹graÌsiÌ tagá¹ hÅtÄÌ  niá¹£khiÌdatiÌ  sa Ä«ÌÅvaÌ ra ÄrtiÌ mÄrtÅÌ-ranaÌ á¸vÄn. hÅtrÄÌ  dÄyÅÌ  vahniÌ rvÄ aÌnaÌ á¸vÄn. vahniÌ rÌ hÅtÄÌ  vahniÌnaiÌ va vahniÌ-mÄÌ tmÄnaggÌ spá¹á¹Åti sÅmÄrauÌ dra-Ã±chaÌ ru-nnirvaÌpÄÌ dyaá¸¥ kÄÌ mayÄÌtaÌ  svÄÌ-'smÄ ÄÌ yataÌnÄÌ  bhrÄtá¹Ìvya-Ã±janayÄyaÌ mitiÌ  vÄdiÌ-mpariÌ gá¹hyÄÌ -'rdha-muÌddhaÌ nyÄ-daÌ rdha-nnÄrdha-mbaÌ rÌ hiá¹£aÌ-sstá¹á¹Ä«Ì yÄ-daÌ rdha-nnÄrdha-miÌ ddhmasyÄÌ-'bhyÄ-daÌ ddhyÄ-dadÌ rdha-nna sva ÄÌ vÄsmÄÌ ÄÌ yataÌnÄÌ  bhrÄtá¹Ìvya-Ã±janayati à¥¥ 57 à¥¥<br/>
<b>(ruÌ drÅ - bhÄÌá¹£aÌ jaá¹ - viÌ ndatÄÌ - yadiÌ - stá¹á¹Ä«Ì yÄdaÌ rdhaá¹ - dvÄdaÌÅa cha) (a. 10)</b></p>
<p>aiÌ ndra-mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄnmÄruÌ tagá¹ saÌ ptakaÌpÄlaÌ -á¹grÄmaÌkÄmaÌ  indraÌ-Ã±chaiÌ va maÌ rutaÌÅchaÌ  svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  ta ÄÌ vÄsmaiÌ sajÄÌ tÄ-nprayaÌchChanti grÄÌ myÄÌva bhaÌvatyÄhavaÌ nÄ«yaÌ aiÌ ndramadhiÌ ÅrayatiÌ  gÄrâhaÌpatyÄ mÄruÌ ta-mpÄÌpavasyaÌ sasyaÌ  vidhá¹Ìtyai saÌ ptakaÌpÄlÅ mÄruÌ tÅ bhaÌvati saÌ ptagaÌá¹ÄÌ  vai maÌ rutÅÌgaá¹aÌ Åa ÄÌ vÄsmaiÌ sajÄÌ tÄnavaÌ rundhÄ-'nÅ«Ì chyamÄÌnaÌ  Ä sÄÌdayatiÌ  viÅaÌmÄÌ vÄ- [viÅaÌmÄÌ va, aÌ smÄÌ  anuÌvartmÄnaá¹-]  à¥¥ 58 à¥¥</p>
<p>-'smÄÌ  anuÌvartmÄna-á¹karÅtyÄÌ tÄmÄÌ va nirvaÌpÄÌ dyaá¸¥ kÄÌ mayÄÌta ká¹£aÌ trÄyaÌ cha viÌ ÅÄ chaÌ saÌ madaÌ-ndaddhyÄÌ -mityaiÌ ndrasyÄÌ-'vaÌ dya-nbrÅ«ÌyÄÌ -dindrÄÌ yÄ-'nuÌ brÅ«Ì hÄ«tyÄÌ ÅrÄvyaÌ brÅ«yÄ-nmaÌ rutÅÌ yaÌ jÄtiÌ mÄruÌ tasyÄÌ-'vaÌ dya-nbrÅ«ÌyÄ-nmaÌ rudbhyÅ-'nuÌ brÅ«Ì hÄ«tyÄÌ ÅrÄvyaÌ brÅ«yÄÌ dindraÌá¹ yaÌ jÄtiÌ  sva ÄÌ vaibhyÅÌ bhÄgaÌ dhÄyÄÌ saÌ madaÌ-ndadhÄti vitá¹gá¹hÄÌ á¹Ä-stiÌá¹£á¹­hantyÄÌ  tÄmÄÌ va [  ]  à¥¥ 59 à¥¥</p>
<p>nirvaÌpÄÌ dyaá¸¥ kÄÌ mayÄÌtaÌ  kalpÄÌraÌ nnitiÌ yathÄdÄvaÌ ta-maÌvaÌ dÄyaÌ yathÄ dÄvaÌ taá¹ yaÌjÄ-dbhÄgaÌ dhÄyÄÌnaiÌ vainÄnÌ yathÄyaÌ tha-á¹kaÌlpayatiÌ  kalpaÌnta ÄÌ vaindra-mÄkÄÌdaÅakapÄlaÌ -nnirvaÌpÄ-dvaiÅvadÄÌ va-ndvÄdaÌÅakapÄlaÌ -á¹grÄmaÌkÄmaÌ  indraÌ-Ã±chaiÌ va viÅvÄgÌÅcha dÄÌ vÄn-thsvÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  ta ÄÌ vÄsmaiÌ sajÄÌ tÄ-nprayaÌchChanti grÄÌ myÄÌva bhaÌvatyaiÌ ndrasyÄÌ-'vaÌ dÄyaÌ vaiÅvadÄÌ vasyÄvaÌ dyÄÌ -dathaiÌ ndrasyÅÌ - [-dathaiÌ ndrasyaÌ, uÌ pariÌá¹£á¹­Ä-]  à¥¥ 60 à¥¥</p>
<p>-pariÌá¹£á¹­Ä-dindriÌ yÄá¹aiÌ vÄsmÄÌ ubhaÌ yataÌ-ssajÄÌ tÄ-npariÌ gá¹há¹ÄtyupÄdhÄÌ yyaÌ pÅ«rvayaÌ á¹ vÄsÅÌ  daká¹£iÌá¹Ä sajÄÌ tÄnÄÌ mupaÌhityaiÌ  pá¹ÅÃ±iÌyai duÌ gdhÄ praiyaÌá¹gava-Ã±chaÌ ru-nnirvaÌpÄnmaÌ rudbhyÅÌ  grÄmaÌkÄmaÌ á¸¥ pá¹ÅÃ±iÌyaiÌ  vai payaÌsÅ maÌ rutÅÌ jÄÌ tÄá¸¥ pá¹ÅÃ±iÌyai priÌ yaá¹gaÌvÅ mÄruÌ tÄá¸¥ khaluÌ  vai dÄÌ vataÌyÄ sajÄÌ tÄ maÌ rutaÌ ÄÌ va svÄnaÌ bhÄgaÌ dhÄyÄÌ nÅpaÌ dhÄvatiÌ  ta ÄÌ vÄsmaiÌ sajÄÌ tÄ-nprayaÌchChanti grÄÌ myÄÌva bhaÌvati priÌ yavaÌtÄ« yÄjyÄnuvÄÌ kyÄÌ [yÄjyÄnuvÄÌ kyÄÌ, bhaÌ vaÌ taÌ á¸¥ priÌ yamÄÌ vainagá¹Ì]  à¥¥ 61 à¥¥</p>
<p>bhavataá¸¥ priÌ yamÄÌ vainagá¹Ì samÄÌ nÄnÄÌ-á¹karÅti dviÌ padÄÌ purÅ-'nuvÄÌ kyÄÌ bhavati dviÌ padaÌ ÄÌ vÄvaÌ rundhÄÌ  chatuÌá¹£padÄ yÄÌ jyÄÌ chatuÌá¹£pada ÄÌ va paÌ ÅÅ«navaÌ rundhÄ dÄvÄsuÌ rÄ-ssaá¹yaÌttÄ ÄsaÌ -ntÄ dÄÌ vÄ miÌ thÅ vipriÌyÄ ÄsaÌ -ntÄÌ(1Ì ) 'nyÅÌ-'nyasmaiÌ  jyaiá¹£á¹­hyÄÌ yÄ-tiÌá¹£á¹­hamÄnÄ-ÅchatuÌ rdhÄ vyaÌkrÄma-nnaÌ gni-rvasuÌbhiÌ -ssÅmÅÌ ruÌ drairindrÅÌ maÌ rudbhiÌ -rvaruÌá¹a ÄdiÌ tyai-ssa indraÌá¸¥ praÌ jÄpaÌtiÌ -mupÄÌ-'dhÄvaÌ -tta- [-'dhÄvaÌ -ttam, ÄÌ tayÄÌ]  à¥¥ 62 à¥¥</p>
<p>-mÄÌ tayÄÌ saÌ á¹(2)jÃ±ÄnyÄÌ-'yÄjaya-daÌ gnayÄÌ  vasuÌmatÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nniraÌvapaÌ -thsÅmÄÌya ruÌ dravaÌtÄ chaÌ rumindrÄÌya maÌ rutvaÌtÄ purÅÌ á¸ÄÅaÌ  -mÄkÄÌdaÅakapÄlaÌ á¹ varuÌá¹ÄyÄ-''diÌ tyavaÌtÄ chaÌ ru-ntatÅÌ  vÄ indraÌ-ndÄÌ vÄ jyaiá¹£á¹­hyÄÌyÄÌ bhi samaÌjÄnataÌ  ya-ssaÌmÄÌ nai-rmiÌ thÅ vipriÌyaÌ -ssyÄ-ttamÄÌ tayÄÌ saÌ á¹(2)jÃ±ÄnyÄÌ yÄjayÄ-daÌ gnayÄÌ  vasuÌmatÄ purÅÌ á¸ÄÅaÌ-maÌ á¹£á¹­ÄkaÌpÄlaÌ -nnirvaÌpÄÌ -thsÅmÄÌya ruÌ dravaÌtÄ chaÌ ru-mindrÄÌya maÌ rutvaÌtÄ purÅÌ á¸ÄÅaÌ -mÄkÄÌdaÅakapÄlaÌ á¹ varuÌá¹ÄyÄ ''diÌ tyavaÌtÄ chaÌ ru-mindraÌ-mÄÌ vainaÌ-mbhÅ«Ì ta-Ã±jyaiá¹£á¹­hyÄÌya samÄÌ nÄ aÌ bhi sa-Ã±jÄÌnatÄÌ  vasiÌá¹£á¹­ha-ssamÄÌ nÄnÄÌ-mbhavati à¥¥ 63 à¥¥<br/>
<b>(viÅaÌmÄÌ va - tiÌá¹£á¹­hantyÄÌ tÄmÄÌ  - vÄthaiÌ ndrasyaÌ - yÄjyÄnuvÄÌ kyÄÌ - taá¹ - à¤varuÌá¹ÄyaÌ  -chatuÌrdaÅa cha) (a. 11)</b></p>
<p>hiÌ raÌ á¹yaÌ gaÌ rbha ÄpÅÌ haÌ  yatprajÄÌpatÄ à¥¥ sa vÄÌda puÌ traá¸¥ piÌ taraÌ gá¹Ì  sa mÄÌ taraÌ gá¹Ì  sa sÅ«Ì nubhaÌrvaÌ -thsa bhuÌvaÌ -tpunaÌrmaghaá¸¥ à¥¤ sa dyÄmaurá¹ÅÌdaÌ ntariÌká¹£aÌ gá¹Ì  sa suvaÌ -ssa viÅvÄÌ  bhuvÅÌ abhavaÌ -thsa Ä-'bhaÌvat à¥¥ uduÌ  tya-Ã±chiÌ tram à¥¥ sa praÌtnaÌ vannavÄ«ÌyaÌ sÄ-'gnÄÌ dyuÌ mnÄnaÌ saÌ á¹yatÄÌ à¥¤ bá¹Ì ha-ttaÌtantha bhÄÌ nunÄÌ à¥¥ ni kÄvyÄÌ vÄÌ dhasaÌ -ÅÅaÅvaÌtaskaÌ rÌ hastÄÌ  dadhÄÌnÅÌ  [dadhÄÌnaá¸¥, naryÄÌ puÌ rÅ«á¹iÌ à¥¤]  à¥¥ 64 à¥¥</p>
<p>naryÄÌ puÌ rÅ«á¹iÌ à¥¤ aÌ gnirbhuÌvadrayiÌ patÄ«Ì rayÄ«Ì á¹Ägá¹ saÌ trÄ chaÌkrÄÌ á¹Å aÌ má¹tÄÌniÌ  viÅvÄÌ à¥¥ hiraÌá¹yapÄá¹imÅ«Ì tayÄÌ saviÌ tÄraÌ mupaÌ hvayÄ à¥¤ sa chÄttÄÌ dÄÌ vatÄÌ paÌ dam à¥¥ vÄÌ mamaÌ dya saÌvitarvÄÌ mamuÌ  ÅvÅ diÌ vÄdiÌvÄ vÄÌ mamaÌ smabhyagá¹Ì sÄvÄ«á¸¥ à¥¤ vÄÌ masyaÌ  hi ká¹£ayaÌsya dÄvaÌ  bhÅ«rÄÌraÌ yÄ dhiÌ yÄ vÄÌmaÌ bhÄjaÌ-ssyÄma à¥¥ baá¸iÌ tthÄ parvaÌtÄnÄ-á¹khiÌ dra-mbiÌbharâá¹£i pá¹thivi à¥¤ pra yÄ bhÅ«Ìmi pravatvati maÌ hnÄ jiÌ nÅá¹£iÌ [jiÌ nÅá¹£iÌ, maÌ hiÌ niÌ  à¥¤]  à¥¥ 65 à¥¥</p>
<p>mahini à¥¥ stÅmÄÌsastvÄ vichÄriá¹iÌ  pratiÌá¹£á¹­ÅbhantyaÌ ktubhiÌá¸¥ à¥¤ prayÄ vÄjaÌ -nna hÄá¹£aÌnta-mpÄÌ ru-masyaÌsyarjuni à¥¥ á¹Ì dÅ«Ì darÄÌá¹aÌ  sakhyÄÌ sachÄyaÌ  yÅ mÄÌ  na riá¹£yÄÌddharyaÅva pÄ«Ì taá¸¥ à¥¤ aÌ yaá¹ ya-ssÅmÅÌ  nyadhÄÌyyaÌ smÄ tasmÄÌ  indraÌ-mpraÌ tiraÌ-mÄÌ myachChaÌ à¥¥ ÄpÄÌmtamanyu-stá¹Ì palaÌ-prabharmÄÌ  dhuniÌ -ÅÅimÄ«Ì vÄÌ Ã±CharuÌmÄgá¹ á¹jÄ«Ì á¹£Ä« à¥¤ sÅmÅÌ  viÅvÄÌnyataÌ sÄ vanÄÌniÌ  nÄrvÄgindraÌ-mpratiÌ mÄnÄÌni dÄbhuá¸¥ à¥¥ pra- [pra, suÌ vÄÌ na-ssÅmaÌ]  à¥¥ 66 à¥¥</p>
<p>-suÌvÄÌ na-ssÅmaÌ á¹taÌ yu-ÅchiÌkÄÌ tÄndrÄÌyaÌ  brahmaÌ jaÌ madaÌgniÌ -rarchannÌ à¥¤ vá¹á¹£ÄÌ yaÌ ntÄ-'siÌ  ÅavaÌsa-stuÌ rasyÄÌ -'nta-ryaÌchCha gá¹á¹aÌ tÄ dhaÌ rtra-ndá¹gá¹Ìha à¥¥ saÌ bÄdhaÌstÄÌ  madaÌ-Ã±cha Åuá¹£maÌ ya-Ã±chaÌ  brahmaÌ  narÅÌ brahmaÌ ká¹taÌ-ssaparyann à¥¤ aÌ rkÅ vÄÌ  ya-ttuÌ ratÄÌ  sÅmaÌchaká¹£ÄÌ -statrÄ-dindrÅÌ dadhatÄ pá¹Ì thsu tuÌ ryÄm à¥¥ vaá¹£aÌ-á¹­tÄ viá¹£á¹avÄÌ sa Ä ká¹Ìá¹ÅmiÌ  tanmÄÌ juá¹£asva Åipiviá¹£á¹­a haÌ vyam à¥¤  à¥¥ 67 à¥¥</p>
<p>vardhaÌntu tvÄ suá¹£á¹­uÌ tayÅÌ  girÅÌ mÄ yÅ«Ì ya-mpÄÌta svaÌ stibhiÌ -ssadÄÌ naá¸¥ à¥¥pra ta-ttÄÌ aÌ dya ÅiÌpiviá¹£á¹­aÌ  nÄmÄÌ -'rya-ÅÅagá¹Ì sÄmi vaÌ yunÄÌni viÌ dvÄn à¥¤ tantvÄÌ gá¹á¹Ämi taÌ vasaÌ -mataÌvÄ«yÄÌ n ká¹£ayaÌntamaÌ sya rajaÌsaá¸¥ parÄÌ kÄ à¥¥ kimi-ttÄÌ viá¹£á¹Å pariÌ chaká¹£yaÌ-mbhÅ«Ì -tpra yadvaÌvaÌ ká¹£Ä ÅiÌpiviÌ á¹£á¹­Å aÌsmi à¥¤ mÄ varpÅÌ aÌ smadapaÌ gÅ«ha ÄÌ tadya-daÌ nyarÅ«Ìpa-ssamiÌ thÄ baÌ bhÅ«thaÌ à¥¤ à¥¥ 68 à¥¥</p>
<p>agnÄÌ  dÄ dÄÌ Åuá¹£ÄÌ raÌ yiá¹ vÄ«Ì ravaÌntaÌ -mparÄ«Ìá¹asam à¥¤ ÅiÌ ÅÄ«Ì hi naÌ-ssÅ«nuÌ mataÌá¸¥ à¥¥ dÄ nÅÌ agnÄ ÅaÌ tinÅÌ  dÄ-ssaÌhaÌ sriá¹ÅÌ duÌ rÅ na vÄjaÌ ggÌ  ÅrutyÄÌ  apÄÌ vá¹dhi à¥¤ prÄchÄ«Ì  dyÄvÄÌpá¹thiÌ vÄ« brahmaÌá¹Ä ká¹dhiÌ  suvaÌ rá¹a ÅuÌ kramuÌ á¹£asÅÌ  vi diÌdyutuá¸¥ à¥¥ aÌ gnirdÄÌ  draviÌá¹aá¹ vÄ«Ì rapÄÌÅÄ aÌ gnir-á¹á¹£iÌ á¹ ya-ssaÌ hasrÄÌ saÌ nÅtiÌ à¥¤ aÌ gnirdiÌ vi haÌ vyamÄ taÌtÄnÄÌ -'gnÄ-rdhÄmÄÌniÌ  vibhá¹ÌtÄ puruÌ trÄ à¥¥ mÄ [mÄ, nÅÌ  maÌ rdhÄ«Ì  rÄ tÅ« bhaÌra à¥¤]  à¥¥ 69 à¥¥</p>
<p>nÅÌ mardhÄ«Ì  rÄ tÅ« bhaÌra à¥¥ ghá¹Ì ta-nna pÅ«Ì ta-ntaÌ nÅ«raÌrÄÌ pÄ-ÅÅuchiÌ  hiraÌá¹yam à¥¤ ta-ttÄÌ ruÌ kmÅ na rÅÌchata svadhÄvaá¸¥ à¥¥ uÌ bhÄ suÌÅchandra saÌ rpiá¹£ÅÌ  darvÄ«Ì ÅrÄ«á¹Ä«á¹£a ÄÌ saniÌ à¥¤ uÌ tÅ naÌ  u-tpuÌpÅ«ryÄ uÌ kthÄá¹£uÌ ÅavasaspataÌ  iá¹£aggÌ stÅÌ tá¹bhyaÌ  Ä bhaÌra à¥¥ vÄyÅÌ ÅaÌ tagá¹ harÄ«Ìá¹Äá¹ yuÌ vasvaÌ  pÅá¹£yÄÌá¹Äm à¥¤ uÌ ta vÄÌ tÄ sahaÌ sriá¹ÅÌ  rathaÌ  Ä yÄÌtuÌ  pÄjaÌsÄ à¥¥ pra yÄbhiÌ - [pra yÄbhiá¸¥, yÄsiÌ dÄÌ ÅvÄgá¹ saÌ machChÄÌ]  à¥¥ 70 à¥¥</p>
<p>-ryÄsiÌ dÄÌ ÅvÄgá¹ saÌ machChÄÌ niÌ yudbhiÌ-rvÄyaviÌ á¹£á¹­ayÄÌ durÅÌ á¹Ä à¥¤ ni nÅÌ raÌ yigá¹ suÌ bhÅjaÌsaá¹ yuvÄÌ ha ni vÄ«Ì ravaÌ -dgavyaÌ maÅviÌya-Ã±chaÌ  rÄdhaÌá¸¥ à¥¥rÄÌ vatÄ«Ìrna-ssadhaÌ mÄdaÌ  indrÄÌ santu tuÌ vivÄÌjÄá¸¥ à¥¤ ká¹£uÌ mantÅÌ  yÄbhiÌ rmadÄÌma à¥¥ rÄÌ vÄgá¹ idrÄÌ vataÌ-sstÅÌ tÄ syÄ-ttvÄvaÌtÅ maÌ ghÅnaÌá¸¥ à¥¤ prÄduÌ hariva-ÅÅruÌ tasyaÌ à¥¥ 71 à¥¥<br/>
<b>(dadhÄÌnÅ - jiÌ nÅá¹£iÌ - dÄbhuÌ á¸¥ pra - haÌ vyaá¹ - baÌ bhÅ«thaÌ  - mÄ - yÄbhiÌ - ÅchatvÄriÌ gá¹Ì ÅachchaÌ ) (a. 12)</b></p>
<p><i>(praÌ jÄpaÌtiÌ stÄ-ssá¹Ì á¹£á¹­Ä - aÌ gnayÄÌ pathiÌ ká¹tÄÌ  - gnayÄÌ  kÄmÄÌyÄÌ  - gnayÄnnaÌvatÄ -vaiÅvÄnaÌ ra -mÄÌdiÌ tya-Ã±chaÌ ru - maiÌ ndra-Ã±chaÌ ru - mindrÄÌ yÄnvá¹Ìjava - ÄgnÄvaiá¹£á¹aÌ va -maÌ sau sÅÌmÄrauÌ dra - maiÌ ndramaÌ kÄÌdaÅakapÄlagá¹- hiraá¹yagaÌ rbhÅ - dvÄdaÌÅa )</i></p>
<p><i>(praÌ jÄpaÌti - raÌ gnayÄÌ  kÄmÄÌyÄÌ  - 'bhi sa-mbhaÌvatÅÌ  - yÅ viÌdviá¹£ÄÌ á¹ayÅÌ -riÌ dhmÄ sannaÌ hyÄ - dÄgnÄvaiá¹£á¹aÌ vamuÌ  - pariÌá¹£á¹­ÄÌ  - dyÄsiÌ dÄÌ ÅvÄgá¹saÌ  - mÄkaÌsaptatiá¸¥ )</i></p>
<p><b>(praÌ jÄpaÌtiÌ á¸¥, prÄduÌ hariva-ÅÅruÌ tasyaÌ)</b></p>
<p>à¥¥ hariÌá¸¥ Åm à¥¥<br/>
à¥¥ ká¹á¹£á¹a yajurvÄdÄ«ya taittirÄ«ya saá¹hitÄyÄ-ndvitÄ«yakÄá¹á¸Ä dvitÄ«yaá¸¥ praÅna-ssamÄptaá¸¥ à¥¥<br/>
</p></span> <br/><br/><br/>
<p class="relatedCategories">Browse Related Categories:</p>
<ul class="aqtree3clickable">
<li><img height="30" src="../images/cats/tags/001.jpg" width="30"/><a class="link1" href="https://vignanam.org">Krishna Yajurveda Taittiriya Samhita (88)</a>
<ul>
<li><a class="link4" href="kyts-1.1-ishe-tvorje-tva-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.1 Ishe Tvorje Tva - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.2-apa-undantu-jivase-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.2 Apa Undantu Jivase - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.3-devasya-tva-savitu-prasave-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.3 Devasya Tva Savitu Prasave - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.4-a-dade-graavaa-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.4 A Dade Graavaa - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.5-devasurah-samyatta-aasann-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.5 Devasurah Samyatta Aasann - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.6-santva-sinchami-yajusha-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.6 Santva Sinchami Yajusha - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.7-pakayagnam-va-anvahitagne-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.7 Pakayagnam Va Anvahitagne - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.8-anumatyai-purodaasamashtakapalam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.8 Anumatyai Purodaasamashtakapalam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.1-vayavyagg-sveta-maa-labheta-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.1 Vayavyagg Sveta Maa Labheta - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.3-adityebhyo-bhuvadvadbhyascharum-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.3 Adityebhyo BhuvadvadbhyaScharum - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.4-deva-manushyah-pitarah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.4 Deva Manushyah Pitarah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.5-visvaroopo-vai-tvaashtrah-krishna-taittiriya-yajurveda-samhita-patha.html">KYTS 2.5 Visvaroopo Vai Tvaashtrah - Krishna Taittiriya Yajurveda Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.6-samidho-yajati-vasantam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.6 Samidho Yajati Vasantam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.1-prajapatirakaamayata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.1 Prajapatirakaamayata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.2-yo-vai-pavamanaanaam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.2 Yo Vai Pavamanaanaam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.3-agne-tejasvintejasvee-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.3 Agne Tejasvintejasvee - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.4-vi-vaa-etasya-yagnah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.4 Vi Vaa Etasya Yagnah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.5-purna-paschaaduta-purna-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.5 Purna Paschaaduta Purna - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.1-yunjanah-prathamam-manah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.1 Yunjanah Prathamam Manah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.2-vishnoh-kramosyabhimaatihaa-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.2 Vishnoh Kramosyabhimaatihaa - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.3-apaan-tvemanthsaadayaami-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.3 Apaan Tvemanthsaadayaami - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.4-rasmirasi-kshayaaya-tvaa-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.4 Rasmirasi Kshayaaya Tvaa - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.5-namaste-rudra-manyava-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.5 Namaste Rudra Manyava - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.6-asmannoorjam-parvate-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.6 Asmannoorjam Parvate - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.7-agnavishnoo-sajoshasemaa-vardhantu-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.7 Agnavishnoo Sajoshasemaa Vardhantu - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.1-savitraani-juhoti-prasootyai-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.1 Savitraani Juhoti Prasootyai - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.2-vishnumukhaa-vai-devaah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.2 Vishnumukhaa Vai Devaah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.3-uthsannayagno-vaa-esha-yadagnih-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.3 Uthsannayagno Vaa Esha Yadagnih - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.4-devasuraa-samyattaa-aasann-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.4 Devasuraa Samyattaa Aasann - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.5-yadekena-saggsthaapayati-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.5 Yadekena Saggsthaapayati - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.6-hirnyavarnaah-suchayah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.6 Hirnyavarnaah Suchayah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.7-yo-vaa-ayathaa-devatam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.7 Yo Vaa Ayathaa Devatam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.2-yadubhau-vimuchyaatithyam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.2 Yadubhau Vimuchyaatithyam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.3-chaatvaalaad-dhishniyaanupavapati-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.3 Chaatvaalaad Dhishniyaanupavapati - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.4-yagnena-vai-prajaapatih-prajaa-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.4 Yagnena Vai Prajaapatih Prajaa Asrujata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.5-indro-vrutraaya-vajramudayacchat-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.5 Indro Vrutraaya Vajramudayacchat - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.6-suvargaaya-vaa-etaani-lokaaya-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.6 Suvargaaya Vaa Etaani Lokaaya - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.1-prajananam-jyothiragnih-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.1 Prajananam Jyothiragnih - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.2-saadhyaa-vai-devaah-suvargakaamaah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.2 Saadhyaa Vai Devaah Suvargakaamaah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.3-prajavam-vaa-etena-yanti-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.3 Prajavam Vaa Etena Yanti - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.4-bruhaspati-rakaamayata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.4 Bruhaspati Rakaamayata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.5-gaavo-vaa-etathsatramaasata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.5 Gaavo Vaa Etathsatramaasata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-jata-1.1-ishe-tvorje-tva-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.1 Ishe Tvorje Tva - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.2-apa-undantu-jivase-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.2 Apa Undantu Jivase - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.3-devasya-tva-savitu-prasave-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.3 Devasya Tva Savitu Prasave - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.4-a-dade-graavaa-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.4 A Dade Graavaa - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.5-devasurah-samyatta-aasann-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.5 Devasurah Samyatta Aasann - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.6-santva-sinchami-yajusha-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.6 Santva Sinchami Yajusha - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.7-pakayagnam-va-anvahitagne-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.7 Pakayagnam Va Anvahitagne - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kys-jata-1.8-anumatyai-purodaasamashtakapalam-krishna-yajurveda-taittiriya-samhita.html">KYS Jata 1.8 Anumatyai Purodaasamashtakapalam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.1-vayavyagg-sveta-maa-labheta-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.1 Vayavyagg Sveta Maa Labheta - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.3-adityebhyo-bhuvadvadbhyascharum-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.3 Adityebhyo BhuvadvadbhyaScharum - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.4-deva-manushyah-pitarah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.4 Deva Manushyah Pitarah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.5-visvaroopo-vai-tvaashtrah-krishna-taittiriya-yajurveda-samhita.html">KYTS Jata 2.5 Visvaroopo Vai Tvaashtrah - Krishna Taittiriya Yajurveda Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.6-samidho-yajati-vasantam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.6 Samidho Yajati Vasantam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.1-prajapatirakaamayata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.1 Prajapatirakaamayata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.2-yo-vai-pavamanaanaam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.2 Yo Vai Pavamanaanaam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.3-agne-tejasvintejasvee-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.3 Agne Tejasvintejasvee - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.4-vi-vaa-etasya-yagnah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.4 Vi Vaa Etasya Yagnah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.5-purna-paschaaduta-purna-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.5 Purna Paschaaduta Purna - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.1-yunjanah-prathamam-manah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.1 Yunjanah Prathamam Manah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.2-vishnoh-kramosyabhimaatihaa-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.2 Vishnoh Kramosyabhimaatihaa - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.3-apaan-tvemanthsaadayaami-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.3 Apaan Tvemanthsaadayaami - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.4-rasmirasi-kshayaaya-tvaa-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.4 Rasmirasi Kshayaaya Tvaa - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.5-namaste-rudra-manyava-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.5 Namaste Rudra Manyava - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.6-asmannoorjam-parvate-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.6 Asmannoorjam Parvate - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.7-agnavishnoo-sajoshasemaa-vardhantu-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.7 Agnavishnoo Sajoshasemaa Vardhantu - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.1-savitraani-juhoti-prasootyai-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.1 Savitraani Juhoti Prasootyai - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.2-vishnumukhaa-vai-devaah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.2 Vishnumukhaa Vai Devaah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.3-uthsannayagno-vaa-esha-yadagnih-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.3 Uthsannayagno Vaa Esha Yadagnih - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.4-devasuraa-samyattaa-aasann-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.4 Devasuraa Samyattaa Aasann - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.5-yadekena-saggsthaapayati-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.5 Yadekena Saggsthaapayati - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.6-hirnyavarnaah-suchayah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.6 Hirnyavarnaah Suchayah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.7-yo-vaa-ayathaa-devatam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.7 Yo Vaa Ayathaa Devatam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.2-yadubhau-vimuchyaatithyam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.2 Yadubhau Vimuchyaatithyam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.3-chaatvaalaad-dhishniyaanupavapati-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.3 Chaatvaalaad Dhishniyaanupavapati - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.4-yagnena-vai-prajaapatih-prajaa-asrujata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.4 Yagnena Vai Prajaapatih Prajaa Asrujata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.5-indro-vrutraaya-vajramudayacchat-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.5 Indro Vrutraaya Vajramudayacchat - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.6-suvargaaya-vaa-etaani-lokaaya-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.6 Suvargaaya Vaa Etaani Lokaaya - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.1-prajananam-jyothiragnih-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.1 Prajananam Jyothiragnih - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.2-saadhyaa-vai-devaah-suvargakaamaah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.2 Saadhyaa Vai Devaah Suvargakaamaah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.3-prajavam-vaa-etena-yanti-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.3 Prajavam Vaa Etena Yanti - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.4-bruhaspati-rakaamayata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.4 Bruhaspati Rakaamayata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.5-gaavo-vaa-etathsatramaasata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.5 Gaavo Vaa Etathsatramaasata - Krishna Yajurveda Taittiriya Samhita</a></li>
</ul>
</li>
<li><img height="30" src="../images/cats/tags/001.jpg" width="30"/><a class="link1" href="https://vignanam.org">Kanda 2 - Krishna Yajurveda Taittiriya Samhita (12)</a>
<ul>
<li><a class="link4" href="kyts-2.1-vayavyagg-sveta-maa-labheta-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.1 Vayavyagg Sveta Maa Labheta - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.3-adityebhyo-bhuvadvadbhyascharum-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.3 Adityebhyo BhuvadvadbhyaScharum - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.4-deva-manushyah-pitarah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.4 Deva Manushyah Pitarah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.5-visvaroopo-vai-tvaashtrah-krishna-taittiriya-yajurveda-samhita-patha.html">KYTS 2.5 Visvaroopo Vai Tvaashtrah - Krishna Taittiriya Yajurveda Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.6-samidho-yajati-vasantam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.6 Samidho Yajati Vasantam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-jata-2.1-vayavyagg-sveta-maa-labheta-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.1 Vayavyagg Sveta Maa Labheta - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.3-adityebhyo-bhuvadvadbhyascharum-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.3 Adityebhyo BhuvadvadbhyaScharum - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.4-deva-manushyah-pitarah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.4 Deva Manushyah Pitarah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.5-visvaroopo-vai-tvaashtrah-krishna-taittiriya-yajurveda-samhita.html">KYTS Jata 2.5 Visvaroopo Vai Tvaashtrah - Krishna Taittiriya Yajurveda Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.6-samidho-yajati-vasantam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.6 Samidho Yajati Vasantam - Krishna Yajurveda Taittiriya Samhita</a></li>
</ul>
</li>
<li><img height="30" src="../images/cats/festivals/047.jpg" width="30"/><a class="link1" href="https://vignanam.org">Upakarma (114)</a>
<ul>
<li><a class="link4" href="gayatri-mantram-ghanapatham.html">Gayatri Mantram Ghanapatham</a></li>
<li><a class="link4" href="nitya-sandhya-vandanam-krishna-yajurvediya.html">Nitya Sandhya Vandanam (Krishna Yajurvediya)</a></li>
<li><a class="link4" href="gayatri-ashtottara-sata-namavali.html">Gayatri Ashtottara Sata Namavali</a></li>
<li><a class="link4" href="gayatri-kavacham.html">Gayatri Kavacham</a></li>
<li><a class="link4" href="sri-gayatri-sahasra-nama-stotram.html">Sri Gayatri Sahasra Nama Stotram</a></li>
<li><a class="link4" href="yagnopavita-dharana.html">Yagnopavita Dharana</a></li>
<li><a class="link4" href="sarva-devata-gayatri-mantras.html">Sarva Devata Gayatri Mantras</a></li>
<li><a class="link4" href="gayatri-ashtottara-sata-nama-stotram.html">Gayatri Ashtottara Sata Nama Stotram</a></li>
<li><a class="link4" href="kyts-1.1-ishe-tvorje-tva-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.1 Ishe Tvorje Tva - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.2-apa-undantu-jivase-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.2 Apa Undantu Jivase - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.3-devasya-tva-savitu-prasave-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.3 Devasya Tva Savitu Prasave - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.4-a-dade-graavaa-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.4 A Dade Graavaa - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.5-devasurah-samyatta-aasann-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.5 Devasurah Samyatta Aasann - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.6-santva-sinchami-yajusha-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.6 Santva Sinchami Yajusha - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.7-pakayagnam-va-anvahitagne-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.7 Pakayagnam Va Anvahitagne - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.8-anumatyai-purodaasamashtakapalam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.8 Anumatyai Purodaasamashtakapalam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.1-vayavyagg-sveta-maa-labheta-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.1 Vayavyagg Sveta Maa Labheta - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.3-adityebhyo-bhuvadvadbhyascharum-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.3 Adityebhyo BhuvadvadbhyaScharum - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.4-deva-manushyah-pitarah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.4 Deva Manushyah Pitarah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.5-visvaroopo-vai-tvaashtrah-krishna-taittiriya-yajurveda-samhita-patha.html">KYTS 2.5 Visvaroopo Vai Tvaashtrah - Krishna Taittiriya Yajurveda Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.6-samidho-yajati-vasantam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.6 Samidho Yajati Vasantam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.1-prajapatirakaamayata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.1 Prajapatirakaamayata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.2-yo-vai-pavamanaanaam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.2 Yo Vai Pavamanaanaam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.3-agne-tejasvintejasvee-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.3 Agne Tejasvintejasvee - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.4-vi-vaa-etasya-yagnah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.4 Vi Vaa Etasya Yagnah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.5-purna-paschaaduta-purna-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.5 Purna Paschaaduta Purna - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.1-yunjanah-prathamam-manah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.1 Yunjanah Prathamam Manah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.2-vishnoh-kramosyabhimaatihaa-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.2 Vishnoh Kramosyabhimaatihaa - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.3-apaan-tvemanthsaadayaami-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.3 Apaan Tvemanthsaadayaami - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.4-rasmirasi-kshayaaya-tvaa-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.4 Rasmirasi Kshayaaya Tvaa - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.5-namaste-rudra-manyava-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.5 Namaste Rudra Manyava - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.6-asmannoorjam-parvate-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.6 Asmannoorjam Parvate - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.7-agnavishnoo-sajoshasemaa-vardhantu-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.7 Agnavishnoo Sajoshasemaa Vardhantu - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.1-savitraani-juhoti-prasootyai-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.1 Savitraani Juhoti Prasootyai - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.2-vishnumukhaa-vai-devaah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.2 Vishnumukhaa Vai Devaah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.3-uthsannayagno-vaa-esha-yadagnih-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.3 Uthsannayagno Vaa Esha Yadagnih - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.4-devasuraa-samyattaa-aasann-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.4 Devasuraa Samyattaa Aasann - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.5-yadekena-saggsthaapayati-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.5 Yadekena Saggsthaapayati - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.6-hirnyavarnaah-suchayah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.6 Hirnyavarnaah Suchayah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.7-yo-vaa-ayathaa-devatam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.7 Yo Vaa Ayathaa Devatam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.2-yadubhau-vimuchyaatithyam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.2 Yadubhau Vimuchyaatithyam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.3-chaatvaalaad-dhishniyaanupavapati-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.3 Chaatvaalaad Dhishniyaanupavapati - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.4-yagnena-vai-prajaapatih-prajaa-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.4 Yagnena Vai Prajaapatih Prajaa Asrujata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.5-indro-vrutraaya-vajramudayacchat-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.5 Indro Vrutraaya Vajramudayacchat - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.6-suvargaaya-vaa-etaani-lokaaya-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.6 Suvargaaya Vaa Etaani Lokaaya - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.1-prajananam-jyothiragnih-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.1 Prajananam Jyothiragnih - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.2-saadhyaa-vai-devaah-suvargakaamaah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.2 Saadhyaa Vai Devaah Suvargakaamaah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.3-prajavam-vaa-etena-yanti-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.3 Prajavam Vaa Etena Yanti - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.4-bruhaspati-rakaamayata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.4 Bruhaspati Rakaamayata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.5-gaavo-vaa-etathsatramaasata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.5 Gaavo Vaa Etathsatramaasata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="saraswati-suktam.html">Saraswati Suktam</a></li>
<li><a class="link4" href="bhagya-suktam.html">Bhagya Suktam</a></li>
<li><a class="link4" href="pavamana-suktam.html">Pavamana Suktam</a></li>
<li><a class="link4" href="nasadiya-suktam.html">Nasadiya Suktam</a></li>
<li><a class="link4" href="navagraha-suktam.html">Navagraha Suktam</a></li>
<li><a class="link4" href="pitru-suktam.html">Pitru Suktam</a></li>
<li><a class="link4" href="ratri-suktam.html">Ratri Suktam</a></li>
<li><a class="link4" href="sarpa-suktam.html">Sarpa Suktam</a></li>
<li><a class="link4" href="hiranya-garbha-suktam.html">Hiranya Garbha Suktam</a></li>
<li><a class="link4" href="sanusvara-prasna-sunnala-pannam.html">Sanusvara Prasna (Sunnala Pannam)</a></li>
<li><a class="link4" href="go-suktam.html">Go Suktam</a></li>
<li><a class="link4" href="trisuparnam.html">Trisuparnam</a></li>
<li><a class="link4" href="chitti-pannam.html">Chitti Pannam</a></li>
<li><a class="link4" href="aghamarshana-suktam.html">Aghamarshana Suktam</a></li>
<li><a class="link4" href="ayushya-suktam.html">Ayushya Suktam</a></li>
<li><a class="link4" href="shraddha-suktam.html">Shraddha Suktam</a></li>
<li><a class="link4" href="kyts-jata-1.1-ishe-tvorje-tva-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.1 Ishe Tvorje Tva - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.2-apa-undantu-jivase-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.2 Apa Undantu Jivase - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.3-devasya-tva-savitu-prasave-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.3 Devasya Tva Savitu Prasave - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.4-a-dade-graavaa-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.4 A Dade Graavaa - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.5-devasurah-samyatta-aasann-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.5 Devasurah Samyatta Aasann - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.6-santva-sinchami-yajusha-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.6 Santva Sinchami Yajusha - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.7-pakayagnam-va-anvahitagne-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.7 Pakayagnam Va Anvahitagne - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kys-jata-1.8-anumatyai-purodaasamashtakapalam-krishna-yajurveda-taittiriya-samhita.html">KYS Jata 1.8 Anumatyai Purodaasamashtakapalam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.1-vayavyagg-sveta-maa-labheta-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.1 Vayavyagg Sveta Maa Labheta - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.3-adityebhyo-bhuvadvadbhyascharum-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.3 Adityebhyo BhuvadvadbhyaScharum - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.4-deva-manushyah-pitarah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.4 Deva Manushyah Pitarah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.5-visvaroopo-vai-tvaashtrah-krishna-taittiriya-yajurveda-samhita.html">KYTS Jata 2.5 Visvaroopo Vai Tvaashtrah - Krishna Taittiriya Yajurveda Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.6-samidho-yajati-vasantam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.6 Samidho Yajati Vasantam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.1-prajapatirakaamayata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.1 Prajapatirakaamayata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.2-yo-vai-pavamanaanaam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.2 Yo Vai Pavamanaanaam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.3-agne-tejasvintejasvee-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.3 Agne Tejasvintejasvee - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.4-vi-vaa-etasya-yagnah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.4 Vi Vaa Etasya Yagnah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.5-purna-paschaaduta-purna-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.5 Purna Paschaaduta Purna - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.1-yunjanah-prathamam-manah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.1 Yunjanah Prathamam Manah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.2-vishnoh-kramosyabhimaatihaa-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.2 Vishnoh Kramosyabhimaatihaa - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.3-apaan-tvemanthsaadayaami-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.3 Apaan Tvemanthsaadayaami - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.4-rasmirasi-kshayaaya-tvaa-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.4 Rasmirasi Kshayaaya Tvaa - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.5-namaste-rudra-manyava-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.5 Namaste Rudra Manyava - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.6-asmannoorjam-parvate-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.6 Asmannoorjam Parvate - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.7-agnavishnoo-sajoshasemaa-vardhantu-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.7 Agnavishnoo Sajoshasemaa Vardhantu - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.1-savitraani-juhoti-prasootyai-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.1 Savitraani Juhoti Prasootyai - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.2-vishnumukhaa-vai-devaah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.2 Vishnumukhaa Vai Devaah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.3-uthsannayagno-vaa-esha-yadagnih-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.3 Uthsannayagno Vaa Esha Yadagnih - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.4-devasuraa-samyattaa-aasann-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.4 Devasuraa Samyattaa Aasann - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.5-yadekena-saggsthaapayati-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.5 Yadekena Saggsthaapayati - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.6-hirnyavarnaah-suchayah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.6 Hirnyavarnaah Suchayah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.7-yo-vaa-ayathaa-devatam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.7 Yo Vaa Ayathaa Devatam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.2-yadubhau-vimuchyaatithyam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.2 Yadubhau Vimuchyaatithyam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.3-chaatvaalaad-dhishniyaanupavapati-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.3 Chaatvaalaad Dhishniyaanupavapati - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.4-yagnena-vai-prajaapatih-prajaa-asrujata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.4 Yagnena Vai Prajaapatih Prajaa Asrujata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.5-indro-vrutraaya-vajramudayacchat-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.5 Indro Vrutraaya Vajramudayacchat - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.6-suvargaaya-vaa-etaani-lokaaya-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.6 Suvargaaya Vaa Etaani Lokaaya - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.1-prajananam-jyothiragnih-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.1 Prajananam Jyothiragnih - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.2-saadhyaa-vai-devaah-suvargakaamaah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.2 Saadhyaa Vai Devaah Suvargakaamaah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.3-prajavam-vaa-etena-yanti-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.3 Prajavam Vaa Etena Yanti - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.4-bruhaspati-rakaamayata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.4 Bruhaspati Rakaamayata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.5-gaavo-vaa-etathsatramaasata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.5 Gaavo Vaa Etathsatramaasata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="shukla-yajurveda-sandhya-vandanam.html">Shukla Yajurveda Sandhya Vandanam</a></li>
<li><a class="link4" href="rigveda-sandhya-vandanam.html">Rigveda Sandhya Vandanam</a></li>
</ul>
</li>
</ul>

</span>
</div>
<!-- <br /><br /><br /><br /> -->
<!-- <br /><br /><br /><br /><br /><br />	-->
</div>
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td>
<div class="footer-space"> </div>
</td>
</tr>
</tfoot>
</table>
</div>
<footer class="deepLinkFooter">
<a class="deepLinkRef" href="https://vignanam.page.link/mvbe">Open In Vignanam Mobile App</a>
</footer>

    </article>
    
    <!-- Ad Promotion Template: For my Website -->
    <div class="promo mt-5 mb-5">
        <?php include "../includes/promo1-devotional.php"; ?>
    </div>
</div>
</section>
</main>

<?php include "../includes/footer.php"; ?>
