<?php
// Meta Tags
$meta_title = "KYTS 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita Patha in English - ClickVedicAstro";
$meta_description = "Full KYTS 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita Patha lyrics in English with meaning. Collection of Spiritual and Devotional Li...";
$meta_keywords = "KYTS 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita Patha, English Stotras, Devotional Hymns, Hindu Slokas, ClickVedicAstro"; 
$meta_url = "https://www.clickvedicastro.com/en/kyts-61-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha-english.php";

// Include Header (session_start is already here)
include "../includes/header.php";
?>

<main id="content" role="main" class="main-content pt-0 pb-0">
<!-- breadcrumb -->
<div class="page-breadcrumb bg-white py-0">
    <div class="container">
        <div class="my-3">
            <ul class="list">
                <li><a href="<?php echo $base_url; ?>/index.php">Home</a></li>
                <li><a href="<?php echo $base_url; ?>/en/" title="Stotras in English">Stotras in English</a></li>
                <li><a href="<?php echo $base_url; ?>/en/others-stotras">Others Stotras</a></li>
                <li>KYTS 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita Patha</li>
            </ul>
        </div>
    </div>
</div>

    <!-- Ad Promotion Template: For my Website -->
    <div class="adpromotion mt-5">
    <?php include "../includes/ad-promotion2.php"; ?>
    </div>

<section class="devotional-content pt-5">
<div class="container">
    <?php include "../includes/language-table-birth.php"; ?><!-- Language Birth Template-->
    <h1 class="stotra-title">KYTS 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita Patha</h1>

    <article class="stotra-content">
      
<div class="mcontainer">

<br/>
</div>

<br/>
</div>
<div id="search">
<input id="searchbar" placeholder="Search for Stotram..." type="text"/>
</div>
<div id="stotramheader">
<div class="pdfLinks">
<a href="../meaning/english/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Meaning</a>, <a href="../media/english/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Multimedia</a> </div>
<div class="languageView">View this in:</div>
<table><tr>
<td class="languageText">| <a href="../english/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">English</a></td>
<td class="languageText">| <a href="../devanagari/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Devanagari</a></td>
<td class="languageText">| <a href="../telugu/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Telugu</a></td>
<td class="languageText">| <a href="../tamil/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Tamil</a></td>
<td class="languageText">| <a href="../kannada/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Kannada</a></td>
<td class="languageText">| <a href="../malayalam/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Malayalam</a></td>
<td class="languageText">| <a href="../gujarati/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Gujarati</a></td>
<td class="languageText">| <a href="../odia/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Odia</a></td>
<td class="languageText">| <a href="../bengali/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Bengali</a></td>
<td class="languageText"> |</td></tr> </table>
<table><tr>
<td class="languageText">| <a href="../marathi/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Marathi</a></td>
<td class="languageText">| <a href="../assamese/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Assamese</a></td>
<td class="languageText">| <a href="../punjabi/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Punjabi</a></td>
<td class="languageText">| <a href="../hindi/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Hindi</a></td>
<td class="languageText">| <a href="../samskritam/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Samskritam</a></td>
<td class="languageText">| <a href="../konkani/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Konkani</a></td>
<td class="languageText">| <a href="../nepali/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Nepali</a></td>
<td class="languageText">| <a href="../sinhala/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Sinhala</a></td>
<td class="languageText">| <a href="../grantha/kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">Grantha</a></td>
<td class="languageText"> |</td></tr> </table>
<div class="languagePrefix">
This document is in romanized sanskrit according to <b><a href="https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration">IAST</a></b> standard.			</div>
<br/>
</div>
<table>
<!-- <thead><tr><td>
			  <div class="header-space">&nbsp;</div>
			</td></tr></thead> -->
<tbody>
<tr>
<td>
<div id="stotramcontent">
<div id="pageFooter">  </div>
<p class="stotramtitle" id="stitle">
								KYTS 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita Patha
							</p>
<div class="stotramtext" id="stext">
<span>
<span style="font-family:NotoSans; line-height:250%;font-size: 22px;">
<p>ká¹á¹£á¹a yajurvÄdÄ«ya taittirÄ«ya saá¹hitÄyÄá¹ á¹£aá¹£á¹­hakÄá¹á¸Ä prathamaá¸¥ praÅnaá¸¥ - sÅmamantrabrÄhmaá¹anirÅ«paá¹aá¹</p>
<p>Å-nnamaá¸¥ paramÄtmanÄ, ÅrÄ« mahÄgaá¹apatayÄ namaá¸¥, <br/>
ÅrÄ« gurubhyÅ namaá¸¥ à¥¤ haÌ riÌ á¸¥ Åm à¥¥</p>
<p>prÄÌ chÄ«naÌvagá¹Åa-á¹karÅti dÄvamanuÌ á¹£yÄ diÅÅÌ  vyaÌbhajantaÌ  prÄchÄ«Ì-ndÄÌ vÄ daÌká¹£iÌ á¹Ä piÌ taraÌá¸¥ praÌ tÄ«chÄ«Ì-mmanuÌ á¹£yÄÌ udÄ«ÌchÄ«gá¹ ruÌ drÄ ya-tprÄÌ chÄ«naÌvagá¹Åa-á¹kaÌ rÅtiÌ dÄvalÅÌ kamÄÌ va ta-dyajaÌmÄna uÌ pÄvaÌrtatÄÌ  pariÌ ÅrayatyaÌ ntarâhiÌtÅÌ hi dÄÌvalÅÌ kÅ maÌnuá¹£yalÅÌ kÄ-nnÄsmÄllÅÌ kÄ-thsvÄÌtavyamiÌ vÄtyÄÌhuÌ á¸¥ kÅ hi ta-dvÄdaÌ  ya-dyaÌ muá¹£miÌà¤llÅÌ kÄ-'stiÌ vÄÌ  na vÄtiÌ diÌ ká¹£vaÌtÄ« kÄÌ ÅÄn kaÌrÅ- [diÌ ká¹£vaÌtÄ« kÄÌ ÅÄn kaÌrÅti, uÌ bhayÅÌ] 1</p>
<p>-tyuÌ bhayÅÌ-rlÅÌ kayÅÌ-raÌ bhijiÌtyai kÄÅaÅmaÌ Åru vaÌpatÄ naÌ khÄniÌ  ni ká¹ÌntatÄ má¹Ì tÄ vÄ ÄÌ á¹£Ä tvagaÌmÄÌ ddhyÄ ya-tkÄÌÅaÅmaÌ Åru má¹Ì tÄmÄÌ va tvachaÌma-mÄÌ ddhyÄmaÌpaÌ hatyaÌ yaÌ jÃ±iyÅÌ bhÅ«Ì tvÄ mÄdhaÌ mupaiÌ tyaá¹giÌrasa-ssuvaÌ rgaá¹ lÅÌ kaá¹ yantÅÌ -'phsu dÄ«Ìká¹£ÄtaÌ pasÄ«Ì  prÄvÄÌÅayannaÌ phsu snÄÌti sÄÌ ká¹£ÄdÄÌ va dÄ«Ìká¹£ÄtaÌ pasÄ«Ì  avaÌ rundhÄ tÄ«Ì rthÄ snÄÌti tÄ«Ì rthÄ hi tÄ tÄ-mprÄvÄÌÅaya-ntÄ«Ì rthÄ snÄÌti [  ] 2</p>
<p>tÄ«Ì rthamÄÌ va saÌmÄÌ nÄnÄÌ-mbhavatyaÌ pÅÌ-'ÅÃ±ÄtyantaraÌ ta ÄÌ va mÄddhyÅÌ bhavatiÌ  vÄsaÌsÄ dÄ«ká¹£ayati sauÌ myaá¹ vai ká¹£aumaÌ-ndÄÌ vataÌyÄÌ  sÅmaÌmÄÌ á¹£a dÄÌ vatÄÌ mupaiÌtiÌ  yÅ dÄ«ká¹£aÌtÄÌ  sÅmaÌsya taÌ nÅ«raÌsi taÌ nuvaÌ-mmÄ pÄÌ hÄ«tyÄÌhaÌ  svÄmÄÌ va dÄÌ vatÄÌ mupaiÌ tyathÅÌ ÄÌ Åiá¹£aÌmÄÌ vaitÄmÄ ÅÄÌstÄÌ  'gnÄstÅ«Ìá¹£ÄÌ dhÄnaÌá¹ vÄÌ yÅrvÄÌtaÌ pÄnaÌ-mpitá¹Ì á¹Ä-nnÄ«Ì vi-rÅá¹£aÌdhÄ«nÄ-mpraghÄÌ ta [-rÅá¹£aÌdhÄ«nÄ-mpraghÄÌ taá¸¥, ÄÌ diÌ tyÄnÄÌ-mprÄchÄ«natÄÌ nÅ] 3</p>
<p>ÄÌdiÌ tyÄnÄÌ-mprÄchÄ«natÄÌ nÅ viÅvÄÌá¹£Ä-ndÄÌ vÄnÄÌ mÅtuÌ  rnaká¹£aÌtrÄá¹Ä-matÄ«kÄÌ ÅÄstadvÄ ÄÌ ta-thsaÌrva dÄvaÌ tyaÌá¹ ya-dvÄsÅÌ  ya-dvÄsaÌsÄ dÄ«Ì ká¹£ayaÌtiÌ  sarvÄÌbhirÄÌ vainaÌ-ndÄÌ vatÄÌbhi-rdÄ«ká¹£ayati baÌ hiá¸¥prÄÌá¹ÅÌ  vai maÌnuÌ á¹£yaÌsta-syÄÅaÌna-mprÄÌ á¹ÅÌ-'ÅÃ±ÄtiÌ  saprÄÌá¹a ÄÌ va dÄ«Ìká¹£ataÌ  ÄÅiÌtÅ bhavatiÌ  yÄvÄÌnÄÌ vÄsyaÌ prÄÌ á¹astÄnaÌ saÌ ha mÄdhaÌ mupaiÌti ghá¹Ì ta-ndÄÌ vÄnÄÌ -mmastuÌ pitá¹Ì á¹Ä-nniá¹£paÌkva-mmanuÌ á¹£yÄÌá¹ÄÌ -ntadvÄ [-mmanuÌ á¹£yÄÌá¹ÄÌ -ntadvai, ÄÌ ta-thsaÌrvadÄvaÌ tyaÌá¹] 4</p>
<p>ÄÌ ta-thsaÌrvadÄvaÌ tyaÌá¹ yannavaÌnÄ«taÌ á¹ yannavaÌnÄ«tÄnÄbhyaÌ á¹ktÄ sarvÄÌ ÄÌ va dÄÌ vatÄÌá¸¥ prÄ«á¹ÄtiÌ  prachyuÌtÅÌ  vÄ ÄÌ á¹£ÅÌ-'smÄllÅÌ kÄdagaÌtÅ dÄvalÅÌ kaá¹ yÅ dÄ«Ìká¹£iÌ tÅÌ 'ntaÌ rÄvaÌ  navaÌnÄ«taÌ -ntasmÄÌ -nnavaÌnÄ«tÄnÄÌ bhyaÌá¹ktÄ 'nulÅÌ maá¹ yajuÌá¹£ÄÌ  vyÄvá¹ÌttyÄÌ  indrÅÌ vá¹Ì tramaÌhaÌ -ntasyaÌ kaÌ nÄ«niÌkÄÌ  parÄÌ-'pataÌ -ttadÄÃ±jaÌnama-bhavaÌ dyadÄÌ á¹ktÄ chaká¹£uÌrÄÌ va bhrÄtá¹Ìvyasya vá¹á¹ktÄÌ  daká¹£iÌá¹aÌ -mpÅ«rvaÌ mÄ-'á¹ktÄÌ [daká¹£iÌá¹aÌ -mpÅ«rvaÌ mÄ-'á¹ktÄÌ, saÌ vyagá¹ hi] 5</p>
<p>saÌ vyagá¹ hi pÅ«rvaÌ-mmanuÌ á¹£yÄÌ ÄÌ Ã±jatÄÌ  na ni dhÄÌvatÄÌ  nÄ«vaÌ  hi maÌnuÌ á¹£yÄÌ dhÄvaÌntÄÌ  paÃ±chaÌ  ká¹tvaÌ  Ä-'á¹ktÄÌ  paÃ±chÄÌká¹£arÄ paÌ á¹ktiá¸¥ pÄá¹ktÅÌ yaÌ jÃ±Å yaÌ jÃ±amÄÌ vÄvaÌ rundhÄÌ  pariÌmitaÌ mÄá¹ktÄ 'paÌrimitaÌ gá¹Ì  hi maÌnuÌ á¹£yÄÌ ÄÌ Ã±jatÄÌ  satÅ«ÌlaÌ yÄ-''á¹ktÄ- 'paÌtÅ«layÄÌ  hi maÌnuÌ á¹£yÄÌ ÄÌ Ã±jatÄÌ  vyÄvá¹ÌttyaiÌ  yadapaÌtÅ«layÄÃ±jÄ«Ì ta vajraÌ iva syÄÌ -thsatÅ«ÌlaÌ yÄ-''á¹ktÄÌ mitraÌ tvÄyÄ- [mitraÌ tvÄyaÌ, indrÅÌ] 6</p>
<p>-ndrÅÌ vá¹Ì tramaÌhaÌ nâthsÅÌ-'(1Ì )pÅÌ-'(1Ì )bhyaÌ-mriyataÌ  tÄsÄÌ á¹ yanmÄddhyaÌá¹ yaÌ jÃ±iyaÌ gá¹Ì  sadÄÌvaÌ mÄsÄ«Ì -ttadaÌ pÅdaÌkrÄmaÌ -ttÄ daÌ rbhÄ aÌbhavaÌ nÌ . yaddaÌrbhapuÃ±jÄ«Ì laiá¸¥ paÌ vayaÌtiÌ  yÄ ÄÌ va mÄddhyÄÌ yaÌ jÃ±iyÄÌ -ssadÄÌvÄÌ  ÄpaÌ stÄbhiÌrÄÌ vainaÌ-mpavayatiÌ  dvÄbhyÄÌ-mpavayatya-hÅrÄÌ trÄbhyÄÌmÄÌ vainaÌ-mpavayati triÌ bhiá¸¥ paÌvayatiÌ  trayaÌ iÌ mÄ lÅÌ kÄ ÄÌ bhirÄÌ vainaÌá¹ lÅÌ kaiá¸¥ paÌvayati paÌ Ã±chabhiÌá¸¥ [paÌ Ã±chabhiÌá¸¥, paÌ vaÌ yaÌ tiÌ  paÃ±chÄÌká¹£arÄ] 7</p>
<p>pavayatiÌ  paÃ±chÄÌká¹£arÄ paÌ á¹ktiá¸¥ pÄá¹ktÅÌ yaÌ jÃ±Å yaÌ jÃ±ÄyaiÌ vainaÌ-mpavayati á¹£aÌ á¸bhiá¸¥ paÌvayatiÌ  á¹£aá¸vÄ á¹Ì tavaÌ á¹Ì tubhiÌrÄÌ vainaÌ-mpavayati saÌ ptabhiÌá¸¥ pavayati saÌ pta ChandÄgá¹ÌsiÌ  ChandÅÌbhirÄÌ vainaÌ-mpavayati naÌ vabhiÌá¸¥ pavayatiÌ  navaÌ  vai puruÌá¹£Ä prÄÌ á¹Ä-ssaprÄÌá¹amÄÌ vainaÌ-mpavayaÌ tyÄkaÌvigá¹ÅatyÄ pavayatiÌ  daÅaÌ  hastyÄÌ aÌ á¹gulaÌyÅÌ  daÅaÌ  padyÄÌ ÄÌ tmaikaÌviÌ gá¹Ì ÅÅ yÄvÄÌnÄÌ va puruÌá¹£aÌ sta-mapaÌrivarga- [puruÌá¹£aÌ sta-mapaÌrivargam, paÌ vaÌ yaÌ tiÌ  chiÌ tpatiÌstvÄ] 8</p>
<p>-mpavayati chiÌ tpatiÌstvÄ punÄÌ tvityÄÌhaÌ  manÅÌ  vai chiÌ tpatiÌ rmanaÌsaiÌ vainaÌ-mpavayati vÄÌ kpatiÌstvÄ punÄÌ tvityÄÌha vÄÌ chaivainaÌ-mpavayati dÄÌ vastvÄÌ saviÌ tÄ puÌnÄÌ tvityÄÌha saviÌ tá¹praÌsÅ«ta ÄÌ vainaÌ-mpavayatiÌ  tasyaÌ tÄ pavitrapatÄ paÌ vitrÄÌá¹aÌ  yasmaiÌ  ka-mpuÌ nÄ tachChaÌkÄyaÌ mityÄÌ-hÄÌ -''Åiá¹£aÌmÄÌ vaitÄmÄ ÅÄÌstÄ à¥¥ 9 à¥¥<br/>
<b>(aÌ tÄ«Ì kÄÌ ÅÄn kaÌrÅÌ tya - vÄÌÅaya-ntiÌ rtha snÄÌti - praghÄÌ tÅ - maÌnuÌ á¹£yÄÌá¹ÄÌ -ntadvÄ - Ä-'á¹ktÄÌ - mitraÌ tvÄyaÌ - paÌ Ã±chabhiÌ  - rapaÌrivarga - maÌ á¹£á¹­ÄchaÌtvÄrigá¹Åachcha) (a. 1)</b></p>
<p>yÄvaÌntÅÌ  vai dÄÌ vÄ yaÌ jÃ±ÄyÄpuÌnataÌ  ta ÄÌ vÄbhaÌvaÌ nÌ . ya ÄÌ vaá¹ viÌ dvÄn. yaÌ jÃ±ÄyaÌ punÄ«Ì tÄ bhavaÌtyÄÌ va baÌ hiá¸¥ paÌvayiÌ tvÄ-'ntaá¸¥ pra pÄÌdayati manuá¹£yalÅÌ ka ÄÌ vainaÌ-mpavayiÌ tvÄ pÅ«Ì ta-ndÄÌvalÅÌ ka-mpra á¹aÌyaÌ tyadÄ«Ìká¹£itaÌ  ÄkaÌ yÄ-''huÌ tyÄtyÄÌhu-ssruÌ vÄá¹aÌ  chataÌsrÅ juhÅti dÄ«ká¹£itaÌ tvÄyaÌ sruÌ chÄ paÌÃ±chaÌ mÄ«-mpaÃ±chÄÌká¹£arÄ paÌ á¹ktiá¸¥ pÄá¹ktÅÌ yaÌ jÃ±Å yaÌ jÃ±amÄÌ vÄvaÌ rundhaÌ  ÄkÅ«Ìtyai praÌ yujÄÌ -'gnayÄÌ  [praÌ yujÄÌ -'gnayÄÌ, svÄhÄtyÄÌ hÄ] 10</p>
<p>svÄhÄtyÄÌ hÄ-''kÅ«ÌtyÄÌ  hi puruÌá¹£Å yaÌ jÃ±amaÌ bhi praÌyuÌ á¹ktÄ yajÄÌ yÄtiÌ mÄÌ dhÄyaiÌ  manaÌsÄÌ -'gnayÄÌ  svÄhÄtyÄÌha mÄÌ dhayÄÌ  hi manaÌsÄÌ  puruÌá¹£Å yaÌ jÃ±amaÌbhiÌ gachChaÌtiÌ  saraÌsvatyai pÅ«Ì á¹£á¹ÄÌ-'gnayÄÌ  svÄhÄtyÄÌhaÌ  vÄgvai saraÌsvatÄ« pá¹thiÌ vÄ« pÅ«Ì á¹£Ä vÄÌ chaiva pá¹ÌthiÌ vyÄ yaÌ jÃ±a-mprayuÌá¹ktaÌ  ÄpÅÌ dÄvÄ«-rbá¹hatÄ«-rviÅvaÅambhuvaÌ  ityÄÌhaÌ  yÄ vai varâá¹£yÄÌ stÄ [yÄ vai varâá¹£yÄÌ stÄá¸¥, ÄpÅÌ dÄÌ vÄ«-rbá¹ÌhaÌ tÄ«-] 11</p>
<p>ÄpÅÌ dÄÌ vÄ«-rbá¹ÌhaÌ tÄ«-rviÌ ÅvaÅaÌbhuá¹vÅÌ  yadÄÌ ta-dyajuÌ rna brÅ«Ì yÄ-ddiÌ vyÄ ÄpÅ-'ÅÄÌmtÄ iÌ maá¹ lÅÌ kamÄ gaÌchChÄyuÌ rÄpÅÌ dÄvÄ«-rbá¹hatÄ«-rviÅvaÅambhuvaÌ  ityÄÌhÄÌ smÄ ÄÌ vainÄÌ lÅÌ kÄyaÌ ÅamayatiÌ  tasmÄÌchChÄÌ ntÄ iÌ maá¹ lÅÌ kamÄ gaÌchChantiÌ  dyÄvÄÌpá¹thiÌ vÄ« ityÄÌhaÌ  dyÄvÄÌpá¹thiÌ vyÅrâhi yaÌ jÃ±a uÌ rvaÌntariÌká¹£aÌ -mityÄÌhÄÌ ntariÌká¹£ÄÌ  hi yaÌ jÃ±Å bá¹haÌ spatiÌrnÅ haÌ viá¹£ÄÌ vá¹dhÄÌ - [haÌ viá¹£ÄÌ vá¹dhÄtu, ityÄÌhaÌ  brahmaÌ  vai] 12</p>
<p>-tvityÄÌhaÌ  brahmaÌ  vai dÄÌ vÄnÄÌ -mbá¹haÌ spatiÌ -rbrahmaÌá¹aiÌ vÄsmaiÌ yaÌ jÃ±amavaÌ rundhÄÌ  yad- brÅ«Ì yÄ-dviÌdhÄÌ ritiÌ yajÃ±asthÄÌ á¹umá¹ÌchChÄ-dvá¹dhÄÌ tvityÄÌha yajÃ±asthÄÌ á¹umÄÌ va pariÌ vá¹á¹akti praÌ jÄpaÌti-ryaÌ jÃ±amaÌsá¹jataÌ  sÅÌ-'smÄ-thsá¹Ì á¹£á¹­aá¸¥ parÄÌá¹aiÌ -thsa pra yajuÌ ravlÄ«ÌnÄÌ -tpra sÄmaÌ  tamá¹gudaÌyachChaÌ -dyadá¹guÌ dayaÌchChaÌ -ttadauÌ-dgrahaÌ á¹asyauÌ-dgrahaá¹aÌ tva má¹Ì chÄ [má¹Ì chÄ, juÌ hÅÌ tiÌ  yaÌ jÃ±asyÅdyaÌtyÄ] 13</p>
<p>juÌhÅti yaÌ jÃ±asyÅdyaÌtyÄ anuÌ á¹£á¹­up-ChandaÌsÄÌ -mudaÌyachChaÌ dityÄÌ-huÌ stasmÄÌdanuÌ á¹£á¹­ubhÄÌ juhÅti yaÌ jÃ±asyÅdyaÌtyaiÌ  dvÄdaÌÅa vÄthsabaÌ ndhÄnyudaÌyachChaÌ -nnityÄÌhuÌ -stasmÄÌd- dvÄdaÌ ÅabhiÌ-rvÄthsabandhaÌ vidÅÌ dÄ«ká¹£ayantiÌ  sÄ vÄ ÄÌ á¹£argaÌnuÌ á¹£á¹­ug-vÄgaÌnuÌ á¹£á¹­ug-yadÄÌ tayaÌ rchÄ dÄ«Ì ká¹£ayaÌti vÄÌ chaivainaÌ gá¹Ì  sarvaÌyÄ dÄ«ká¹£ayatiÌ  viÅvÄÌ dÄÌ vasyaÌ nÄÌ turityÄÌha sÄviÌ tryÄÌtÄnaÌ  martÅÌ vá¹á¹Ä«ta saÌ khya- [saÌ khyam, ityÄÌha] 14</p>
<p>-mityÄÌha pitá¹dÄvaÌ tyaiÌtÄnaÌ  viÅvÄÌ rÄÌ ya iÌá¹£uddhyaÌ sÄ«tyÄÌha vaiÅvadÄÌ vyÄÌtÄnaÌ dyuÌ mnaá¹ vá¹Ìá¹Ä«ta puÌ á¹£yasaÌ  ityÄÌha pauÌ á¹£á¹yÄÌtÄnaÌ  sÄ vÄ ÄÌ á¹£arkhsaÌrvadÄvaÌ tyÄÌ yadÄÌ tayaÌ rchÄ dÄ«Ì ká¹£ayaÌtiÌ  sarvÄÌbhirÄÌ vainaÌ-ndÄÌ vatÄÌbhirdÄ«ká¹£ayati saÌ ptÄká¹£aÌra-mprathaÌ ma-mpaÌ damaÌ á¹£á¹­Äká¹£aÌrÄá¹iÌ  trÄ«á¹iÌ  yÄniÌ  trÄ«á¹iÌ  tÄnyaÌ á¹£á¹­ÄvupaÌ yantiÌ  yÄniÌ chaÌ tvÄriÌ  tÄnyaÌ á¹£á¹­au yadaÌ á¹£á¹­Äká¹£aÌrÄÌ  tÄnaÌ [tÄnaÌ, gÄÌ yaÌ trÄ« yadÄkÄÌdaÅÄká¹£arÄÌ ] 15</p>
<p>gÄyaÌ trÄ« yadÄkÄÌdaÅÄká¹£arÄÌ  tÄnaÌ triÌ á¹£á¹­ugya-ddvÄdaÌÅÄká¹£arÄÌ  tÄnaÌ  jagaÌtÄ«Ì  sÄ vÄ ÄÌ á¹£arkhsarvÄÌá¹iÌ  ChandÄgá¹ÌsiÌ  yadÄÌ tayaÌ rchÄ dÄ«Ì ká¹£ayaÌtiÌ  sarvÄÌbhirÄÌ vainaÌ -Ã±ChandÅÌbhirdÄ«ká¹£ayati saÌ ptÄká¹£aÌra-mprathaÌ ma-mpaÌ dagá¹ saÌ ptapaÌdÄÌ  ÅakvaÌrÄ« paÌ ÅavaÌ -ÅÅakvaÌrÄ« paÌ ÅÅ«nÄÌ vÄvaÌ rundhaÌ  ÄkaÌsmÄdaÌ ká¹£arÄÌ danÄÌpta-mprathaÌ ma-mpaÌ da-ntasmÄÌ -dya-dvÄÌ chÅ-'nÄÌptaÌ -ntanmaÌnuÌ á¹£yÄÌ upaÌ jÄ«vanti pÅ«Ì rá¹ayÄÌ juhÅti pÅ«Ì rá¹a iÌvaÌ  hi praÌ jÄpaÌtiá¸¥ praÌ jÄpaÌtÄÌ rÄptyaiÌ  nyÅ«ÌnayÄ juhÅtiÌ  nyÅ«ÌnÄÌ ddhi praÌ jÄpaÌtiá¸¥ praÌ jÄ asá¹Ìjata praÌ jÄnÄÌ gá¹Ì  sá¹á¹£á¹­yaiÌ à¥¥ 16 à¥¥<br/>
<b>(aÌ gnayÄÌ  - tÄ - vá¹ÌdhÄtvá¹Ì  - chÄ - saÌ khyaá¹ - tÄnaÌ - juhÅtiÌ  - paÃ±chaÌdaÅa cha) (a. 2)</b></p>
<p>á¹Ì -khsÄÌ mÄ vai dÄÌ vÄbhyÅÌ yaÌ jÃ±ÄyÄ-'tiÌá¹£á¹­hamÄnÄÌ  ká¹á¹£á¹ÅÌ rÅ«Ì pa-á¹ká¹Ì tvÄ- 'paÌ kramyÄÌtiá¹£á¹­hatÄÌ -ntÄÌ-'manyantaÌ  yaá¹ vÄ iÌ mÄ uÌpÄvaÌ rthsyataÌ -ssa iÌ da-mbhaÌviá¹£yaÌ tÄ«tiÌ  tÄ upÄÌmantrayantaÌ  tÄ aÌhÅrÄÌ trayÅÌ-rmahiÌ mÄnaÌ-mapaniÌ dhÄyaÌ dÄÌ vÄnuÌ pÄvaÌrtÄtÄmÄÌ á¹£a vÄ á¹Ì chÅ vará¹ÅÌ  yachChuÌ kla-á¹ká¹Ìá¹£á¹ÄjiÌ nasyaiÌ á¹£a sÄmnÅÌ  ya-tká¹Ì á¹£á¹amá¹ÌkhsÄÌ mayÅÌ -ÅÅilpÄÌ sthaÌ  ityÄÌharkhsÄÌ mÄ ÄÌ vÄ-'vaÌ rundha ÄÌ á¹£a [ÄÌ vÄ-'vaÌ rundha ÄÌ á¹£aá¸¥, vÄ ahnÅÌ ] 17</p>
<p>vÄ ahnÅÌ  vará¹ÅÌ  yachChuÌ kla-á¹ká¹Ìá¹£á¹ÄjiÌ nasyaiÌ á¹£a rÄtriÌyÄÌ  ya-tká¹Ì á¹£á¹aá¹ yadÄÌ vainaÌyÅÌ statraÌ  nyaÌktaÌ -ntadÄÌ vÄvaÌ rundhÄ ká¹á¹£á¹ÄjiÌ nÄnaÌ dÄ«ká¹£ayatiÌ  brahmaÌá¹ÅÌ  vÄ ÄÌ ta-drÅ«Ì paá¹ ya-tká¹Ìá¹£á¹ÄjiÌ na-mbrahmaÌá¹aiÌ vainaÌ-ndÄ«ká¹£ayatÄ«Ì mÄ-ndhiyaÌ gá¹Ì  Åiká¹£aÌmÄá¹asya dÄÌ vÄtyÄÌha yathÄyaÌ jurÄÌ vaita-dgarbhÅÌ  vÄ ÄÌ á¹£a ya-ddÄ«Ìká¹£iÌ ta ulbaÌ á¹ vÄsaÌ á¸¥ prÅrá¹uÌtÄÌ  tasmÄÌ - [tasmÄÌt, garbhÄÌ á¸¥ prÄvá¹ÌtÄ] 18</p>
<p>-dgarbhÄÌ á¸¥ prÄvá¹ÌtÄ jÄyantÄÌ  na puÌ rÄ sÅmaÌsya kraÌ yÄdapÅÌrá¹vÄ«taÌ  ya-tpuÌ rÄ sÅmaÌsya kraÌ yÄdaÌpÅrá¹vÄ«Ì ta garbhÄÌá¸¥ praÌ jÄnÄÌ-mparÄÌ pÄtuÌkÄ-ssyuá¸¥ krÄ«Ì tÄ sÅmÄ-'pÅÌrá¹utÄÌ  jÄyaÌta ÄÌ va tadathÅÌ  yathÄÌ  vasÄ«ÌyÄgá¹ sa-mpratyapÅrá¹uÌ tÄ tÄÌ dá¹gÄÌ va tadaá¹giÌrasa-ssuvaÌ rgaá¹ lÅÌ kaá¹ yantaÌ  Å«rjaÌ á¹ vyaÌbhajantaÌ  tatÅÌ  yadaÌ tyaÅiÌá¹£yataÌ  tÄ ÅaÌ rÄ aÌbhavaÌ nnÅ«rgvai ÅaÌ rÄ yachChaÌraÌ mayÄ«Ì  [yachChaÌraÌ mayÄ«Ì, mÄkhaÌlÄÌ ] 19</p>
<p>mÄkhaÌlÄÌ  bhavaÌ tyÅ«rjaÌmÄÌ vÄvaÌ rundhÄ maddhyaÌ ta-ssannaÌhyati maddhyaÌ ta ÄÌ vÄsmÄÌ  Å«rjaÌ-ndadhÄtiÌ  tasmÄÌnmaddhyaÌ ta Å«Ì rjÄ bhuÌÃ±jata Å«Ì rdhvaá¹ vai puruÌá¹£asyaÌ  nÄbhyaiÌ  mÄddhyaÌ-mavÄÌ chÄ«naÌ-mamÄÌ ddhyaá¹ yanmaÌddhyaÌ ta-ssaÌ naá¹hyaÌtiÌ  mÄddhyaÌ-Ã±chaiÌ vÄsyÄÌmÄÌ ddhya-Ã±chaÌ  vyÄvaÌrtayaÌ tÄ«ndrÅÌ vá¹Ì trÄyaÌ  vajraÌ -mprÄhaÌraÌ -thsa trÄÌ dhÄ vyaÌbhavaÌ -thsphyastá¹tÄ«ÌyaÌ gá¹Ì  rathaÌ stá¹tÄ«ÌyaÌ á¹ yÅ«paÌ stá¹tÄ«ÌyaÌ á¹- [-yÅ«paÌ stá¹tÄ«ÌyaÌ m, yÄÌ-'nta-ÅÅaÌ rÄ] 20</p>
<p>-à¤yÄÌ-'nta-ÅÅaÌ rÄ aÅÄ«ÌryantaÌ  tÄ ÅaÌ rÄ aÌbhavaÌ -ntachChaÌ rÄá¹Ägá¹Ì ÅaraÌ tvaá¹ vajrÅÌ  vai ÅaÌ rÄá¸¥, ká¹£u-tkhaluÌ  vai maÌnuÌ á¹£yaÌsyaÌ  bhrÄtá¹ÌvyÅÌ  yachChaÌraÌ mayÄ«Ì  mÄkhaÌlÄÌ  bhavaÌtiÌ  vajrÄÌá¹aiÌ va sÄÌ ká¹£Ä-tká¹£udhaÌ -mbhrÄtá¹Ìvya-mmaddhyaÌ tÅ-'paÌ hatÄ triÌ vá¹-dbhaÌvati triÌ vá¹dvai prÄÌ á¹astriÌ vá¹taÌmÄÌ va prÄÌ á¹a-mmaÌddhyaÌ tÅ yajaÌmÄnÄ dadhÄti pá¹Ì thvÄ« bhaÌvatiÌ  rajjÅ«ÌnÄÌ á¹ vyÄvá¹ÌtyaiÌ  mÄkhaÌlayÄÌ  yajaÌmÄna-ndÄ«ká¹£ayatiÌ  yÅktrÄÌá¹aÌ  patnÄ«Ì-mmithunaÌ tvÄyaÌ [  ] 21</p>
<p>yaÌ jÃ±Å daká¹£iÌá¹ÄmaÌ bhyaÌddhyÄyaÌ -ttÄgá¹ samaÌbhavaÌ -ttadindrÅÌ-'chÄyaÌ -thsÅÌ-'manyataÌ  yÅ vÄ iÌ tÅ jaÌniÌ á¹£yatÄÌ  sa iÌ da-mbhaÌviá¹£yaÌ tÄ«tiÌ  tÄ-mprÄviÌÅaÌ -ttasyÄÌ  indraÌ ÄÌ vÄjÄÌyataÌ  sÅÌ-'manyataÌ  yÅ vai madiÌ tÅ 'paÌrÅ janiÌ á¹£yatÄÌ  sa iÌ da-mbhaÌviá¹£yaÌ tÄ«tiÌ  tasyÄÌ anuÌ má¹ÅyaÌ  yÅniÌ mÄ-'chChiÌnaÌ -thsÄ sÅ«Ì tavaÌÅÄ-'bhavaÌ -tta-thsÅ«Ì tavaÌÅÄyaiÌ  janmaÌ  [janmaÌ, tÄgá¹ hastÄÌ  nyaÌvÄá¹£á¹­ayataÌ ] 22</p>
<p>tÄgá¹ hastÄÌ  nyaÌvÄá¹£á¹­ayataÌ  tÄ-mmá¹Ì gÄá¹£uÌ  nyaÌdadhÄÌ -thsÄ ká¹Ìá¹£á¹aviá¹£ÄÌ á¹Ä- 'bhaÌvaÌ dindraÌsyaÌ  yÅniÌrasiÌ  mÄ mÄÌ higá¹sÄ«Ì ritiÌ ká¹á¹£á¹aviá¹£ÄÌ á¹Ä-mpra yaÌchChatiÌ  sayÅÌnimÄÌ va yaÌ jÃ±a-á¹kaÌrÅtiÌ  sayÅÌniÌ -ndaká¹£iÌá¹ÄÌ gá¹Ì  sayÅÌniÌ mindragá¹Ì sayÅniÌ tvÄyaÌ ká¹Ì á¹£yai tvÄÌ susaÌ syÄyÄÌ  ityÄÌhaÌ  tasmÄÌdaká¹á¹£á¹­apaÌ chyÄ Åá¹£aÌdhayaá¸¥ pachyantÄ supippaÌ lÄbhyaÌ -stvauá¹£aÌdhÄ«bhyaÌ  ityÄÌhaÌ  tasmÄÌ dÅá¹£aÌdhayaÌ á¸¥ phalaÌ-á¹gá¹há¹antiÌ  yaddhastÄÌna [yaddhastÄÌna, kaÌ á¹á¸Å«Ì yÄtaÌ] 23</p>
<p>kaá¹á¸Å«Ì yÄtaÌ pÄmanaÌ -mbhÄvuÌkÄá¸¥ praÌ jÄ-ssyuÌ rya-thsmayÄÌta nagnaÌ -mbhÄvuÌkÄá¸¥ ká¹á¹£á¹aviá¹£ÄÌ á¹ayÄÌ kaá¹á¸Å«yatÄ-'piÌ gá¹hyaÌ smayatÄ praÌ jÄnÄÌ-á¹gÅpÄ«Ì thÄyaÌ  na puÌ rÄ daká¹£iÌá¹ÄbhyÅÌ  nÄtÅÌá¸¥ ká¹á¹£á¹aviá¹£ÄÌ á¹ÄmavaÌ chá¹tÄÌ dya-tpuÌ rÄ daká¹£iÌá¹ÄbhyÅÌ  nÄtÅÌá¸¥ ká¹á¹£á¹aviá¹£ÄÌ á¹Ä-maÌvachá¹Ì tÄ-dyÅniÌá¸¥ praÌ jÄnÄÌ-mparÄÌ pÄtuÌkÄ syÄnnÄ«Ì tÄsuÌ  daká¹£iÌá¹ÄsuÌ  chÄtvÄÌlÄ ká¹á¹£á¹aviá¹£ÄÌ á¹Ä-mprÄsyaÌtiÌ  yÅniÌ rvai yaÌ jÃ±asyaÌ  chÄtvÄÌlaÌ á¹ yÅniÌá¸¥ ká¹á¹£á¹aviá¹£ÄÌ á¹Ä yÅnÄÌvÄÌ va yÅniÌ-ndadhÄti yaÌ jÃ±asyaÌ sayÅniÌ tvÄyaÌ à¥¥ 24 à¥¥<br/>
<b>(ruÌ ndhaÌ  ÄÌ á¹£a - tasmÄÌ - chCharaÌ mayÄ«Ì  - yÅ«paÌ stá¹tÄ«Ìyaá¹ - mithunaÌ tvÄyaÌ  - janmaÌ  - hastÄÌnÄÌ  - 'á¹£á¹­ÄchaÌtvÄrigá¹Åachcha) (a. 3)</b></p>
<p>vÄgvai dÄÌ vÄbhyÅ 'pÄÌkrÄma-dyaÌ jÃ±ÄyÄtiÌá¹£á¹­hamÄnÄÌ  sÄ vanaÌ spatÄ«Ì -nprÄviÌÅaÌ -thsaiá¹£Ä vÄgvanaÌ spatiÌá¹£u vadatiÌ  yÄ duÌnduÌ bhau yÄ tÅ«á¹aÌvÄÌ  yÄ vÄ«á¹ÄÌyÄÌ á¹ ya-ddÄ«Ìká¹£itadaÌ á¹á¸a-mpraÌ yachChaÌtiÌ  vÄchaÌmÄÌ vÄvaÌ rundhaÌ  auduÌbaá¹rÅ bhavaÌ tyÅ«rgvÄ uÌduÌ baá¹raÌ  Å«rjaÌmÄÌ vÄvaÌ rundhÄÌ  mukhÄÌnaÌ  sammiÌtÅ bhavati mukhaÌ ta ÄÌ vÄsmÄÌ  Å«rjaÌ-ndadhÄtiÌ  tasmÄÌ-nmukhaÌ ta Å«Ì rjÄ bhuÌÃ±jatÄ [  ] 25</p>
<p>krÄ«Ì tÄ sÅmÄÌ maitrÄvaruÌ á¹ÄyaÌ daÌ á¹á¸a-mpra yaÌchChati maitrÄvaruÌ á¹Å hi puÌ rastÄÌ-dá¹Ì tvigbhyÅÌ  vÄchaÌá¹ viÌ bhajaÌtiÌ  tÄmá¹Ì tvijÅÌ  yajaÌmÄnÄÌ  pratiÌ á¹£á¹­hÄpayantiÌ  svÄhÄÌ yaÌ jÃ±a-mmanaÌ sÄtyÄÌhaÌ  manaÌsÄÌ  hi puruÌá¹£Å yaÌ jÃ±amaÌbhiÌ gachChaÌtiÌ  svÄhÄÌ  dyÄvÄÌpá¹thiÌ vÄ«bhyÄÌ  -mityÄÌhaÌ  dyÄvÄÌpá¹thiÌ vyÅrâhi yaÌ jÃ±a-ssvÄhÅÌ rÅraÌ -ntariÌká¹£ÄÌ  -dityÄÌhÄÌ ntariÌká¹£ÄÌ  hi yaÌ jÃ±a-ssvÄhÄÌ yaÌ jÃ±aá¹ vÄtÄÌ dÄ raÌbhaÌ  ityÄÌhÄÌ -'yaá¹- [ityÄÌhÄÌ -'yam, vÄva yaá¸¥ pavaÌtÄÌ ] 26</p>
<p>-à¤vÄva yaá¸¥ pavaÌtÄÌ  sa yaÌ jÃ±astamÄÌ va sÄÌ ká¹£ÄdÄ raÌbhatÄ muÌ á¹£á¹­Ä« kaÌrÅtiÌ  vÄchaÌá¹ yachChati yaÌ jÃ±asyaÌ  dhá¹tyÄÌ  adÄ«Ìká¹£iá¹£á¹­ÄÌ ya-mbrÄÌhmaÌ á¹a itiÌ  triruÌpÄÌ gÌ ÅvÄÌha dÄÌ vÄbhyaÌ ÄÌ vainaÌ -mprÄ-''haÌ  triruÌ chchairuÌ bhayÄÌbhya ÄÌ vainaÌ-ndÄvamanuÌ á¹£yÄbhyaÌ á¸¥ prÄ-''haÌ  na puÌ rÄ naká¹£aÌtrÄbhyÅÌ  vÄchaÌ á¹ vi sá¹ÌjÄÌ -dyatpuÌ rÄ naká¹£aÌtrÄbhyÅÌ  vÄchaÌá¹ visá¹Ì jÄ-dyaÌ jÃ±aá¹ vichChiÌndyÄÌ - [-à¤vichChiÌndyÄt, udiÌtÄá¹£uÌ ] 27</p>
<p>-dudiÌtÄá¹£uÌ  naká¹£aÌtrÄá¹£u vraÌ ta-á¹ká¹Ìá¹uÌ tÄtiÌ  vÄchaÌ á¹ vi sá¹Ìjati yaÌ jÃ±avraÌtÅÌ  vai dÄ«Ìká¹£iÌ tÅ yaÌ jÃ±amÄÌ vÄbhi vÄchaÌ á¹ vi sá¹ÌjatiÌ  yadiÌ visá¹Ì jÄ-dvaiÌá¹£á¹aÌ vÄ«má¹chaÌ manuÌ brÅ«yÄ-dyaÌ jÃ±Å vai viá¹£á¹uÌryaÌ jÃ±ÄnaiÌ va yaÌ jÃ±agá¹ sa-ntaÌnÅtiÌ  daivÄ«Ì -ndhiyaÌ-mmanÄmahaÌ  ityÄÌha yaÌ jÃ±amÄÌ va tanmraÌdayati supÄÌ rÄ nÅÌ asaÌ dvaÅaÌ  ityÄÌhaÌ  vyuÌá¹£á¹­imÄÌ vÄvaÌ rundhÄ [rundhÄ, braÌ hmaÌ vÄÌ dinÅÌ vadanti] 28</p>
<p>brahmavÄÌ dinÅÌ vadanti hÅtaÌ vyaÌ-ndÄ«ká¹£iÌ tasyaÌ gá¹Ì hÄ(3) i na hÅÌtaÌ vyÄ(3)mitiÌ haÌ virvai dÄ«Ìká¹£iÌ tÅ yajjuÌhuÌ yÄ-dyajaÌmÄnasyÄvaÌ dÄyaÌ juhuyÄÌ -dyanna juÌhuÌ yÄ-dyaÌjÃ±apaÌ ruraÌ ntariÌyÄÌ dyÄ dÄÌ vÄ manÅÌjÄtÄ manÅÌ yujaÌ  ityÄÌha prÄÌ á¹Ä vai dÄÌ vÄ manÅÌjÄtÄ manÅÌ yujaÌ stÄá¹£vÄÌ va paÌ rÅká¹£aÌ-Ã±juhÅtiÌ  tannÄvaÌ huÌ ta-nnÄvÄhuÌtaggâ svaÌ pantaÌ á¹ vai dÄ«Ìká¹£iÌ tagá¹ raká¹£Ägá¹Ìsi jighÄgá¹santyaÌ gniá¸¥ - [jighÄgá¹santyaÌ gniá¸¥, khaluÌ  vai] 29</p>
<p>khaluÌ  vai raÌká¹£ÅÌ hÄ-'gnÄÌ  tvagá¹ su jÄÌgá¹hi vaÌ yagá¹ su maÌndiá¹£Ä«maÌ hÄ«tyÄÌhÄÌ gni-mÄÌ vÄdhiÌ pÄ-á¹ká¹Ì tvÄ svaÌpitiÌ  raká¹£aÌsÄÌ mapaÌhatyÄ avraÌ tyamiÌvaÌ  vÄ ÄÌ á¹£a kaÌrÅtiÌ  yÅ dÄ«Ìká¹£iÌ ta-ssvapiÌtiÌ  tvamaÌgnÄ vrataÌ pÄ aÌ sÄ«tyÄÌhÄÌ gnirvai dÄÌ vÄnÄÌá¹ vraÌ tapaÌtiÌ -ssa ÄÌ vainaÌá¹ vraÌ tamÄ laÌbhaá¹yati dÄÌ va Ä martyÄÌ á¹£vÄtyÄÌha dÄÌ vÅ [dÄÌ vaá¸¥, hyÄÌá¹£a sa-nmartyÄÌá¹£uÌ ] 30</p>
<p>hyÄÌá¹£a sa-nmartyÄÌá¹£uÌ  tvaá¹ yaÌ jÃ±Äá¹£vÄ«á¸yaÌ  ityÄÌhaiÌ tagá¹ hi yaÌ jÃ±Äá¹£vÄ«á¸aÌ tÄ-'paÌ  vai dÄ«Ìká¹£iÌ tÄ-thsuÌá¹£uÌ puá¹£aÌ indriÌ ya-ndÄÌ vatÄÌá¸¥ krÄmantiÌ  viÅvÄÌ dÄÌ vÄ aÌ bhi mÄmÄ-'vaÌvá¹traÌ -nnityÄÌ-hÄndriÌ yÄá¹aiÌ vainaÌ-ndÄÌ vatÄÌbhiÌ -ssa-nnaÌyatiÌ  yadÄÌ ta-dyajuÌ rna brÅ«Ì yÄ-dyÄvaÌta ÄÌ va paÌ ÅÅ«naÌ bhi dÄ«ká¹£ÄÌtaÌ  tÄvaÌntÅ-'sya paÌ ÅavaÌ-ssyÅ«Ì  rÄsvÄyaÌ- [paÌ ÅavaÌ-ssyÅ«Ì  rÄsvÄyaÌt, sÅÌ mÄ-'' bhÅ«yÅÌ] 31</p>
<p>-thsÅÌ mÄ-'' bhÅ«yÅÌ bhaÌ rÄtyÄÌ hÄ-paÌrimitÄnÄÌ va paÌ ÅÅ«navaÌ rundhÄ chaÌ ndramaÌsiÌ  mamaÌ  bhÅgÄÌya bhaÌ vÄtyÄÌha yathÄdÄvaÌ tamÄÌ vainÄÌ á¸¥ pratiÌ gá¹há¹Äti vÄÌ yavÄÌ tvÄÌ  varuÌá¹ÄyaÌ  tvÄtiÌ  yadÄÌ vamÄÌ tÄ nÄnuÌdiÌ ÅÄdayaÌthÄdÄvataÌ -ndaká¹£iÌá¹Ä gamayÄÌ dÄ dÄÌ vatÄÌbhyÅ vá¹ÅchyÄtaÌ  yadÄÌ vamÄÌ tÄ aÌnudiÌ ÅatiÌ yathÄdÄvaÌ tamÄÌ va daká¹£iÌá¹Ä gamayatiÌ  na dÄÌ vatÄÌbhyaÌ  Ä [na dÄÌ vatÄÌbhyaÌ  Ä, vá¹Ì ÅchyaÌ tÄÌ  dÄvÄ«ÌrÄpÅ] 32 </p>
<p>vá¹ÌÅchyatÄÌ  dÄvÄ«ÌrÄpÅ apÄ-nnapÄÌ dityÄÌhaÌ  yadvÅÌ  mÄddhyaÌá¹ yaÌ jÃ±iyaÌ gá¹Ì  sadÄÌvaÌ -ntadvÅÌ  mÄ-'vaÌ kramiá¹£aÌ mitiÌ  vÄvaitadÄÌ hÄchChiÌnnaÌ -ntantuÌ-mpá¹thiÌ vyÄ anuÌ gÄá¹£aÌ mityÄÌhaÌ  sÄtuÌmÄÌ va ká¹Ì tvÄ-'tyÄÌti à¥¥ 33 à¥¥<br/>
<b>(bhuÌ Ã±jaÌ tÄÌ  - 'yaá¹ - ChiÌndyÄ-d- rundhÄÌ  - 'gni - rÄÌha dÄÌ va - iyaÌ-d- dÄÌ vatÄÌbhyaÌ  Ä - trayaÌstrigá¹Åachcha) (a. 4)</b></p>
<p>dÄÌ vÄ vai dÄÌvaÌ yajaÌna-maddhyavaÌ sÄyaÌ  diÅÅÌ  na prÄjÄÌnaÌ -ntÄÌ(1Ì )-'nyÅÌ-'nyamupÄÌdhÄvaÌ -ntvayÄÌ  pra jÄÌnÄmaÌ  tvayÄtiÌ  tÄ-'diÌtyÄÌ gá¹Ì  samaÌddhrayantaÌ  tvayÄÌ  pra jÄÌnÄÌ mÄtiÌ  sÄ-'braÌvÄ«Ì -dvaraÌá¹ vá¹á¹aiÌ  matprÄÌyaá¹Ä ÄÌ va vÅÌ yaÌ jÃ±Ä maduÌdayanÄ asaÌ nnitiÌ  tasmÄÌdÄdiÌ tyaá¸¥ prÄÌyaÌ á¹Ä«yÅÌ yaÌ jÃ±ÄnÄÌmÄdiÌ tya uÌdayaÌ nÄ«yaÌ á¸¥ paÃ±chaÌ dÄÌ vatÄÌ yajatiÌ  paÃ±chaÌ  diÅÅÌ diÌ ÅÄ-mprajÃ±ÄÌtyÄÌ  [diÌ ÅÄ-mprajÃ±ÄÌtyai, athÅÌ  paÃ±chÄÌká¹£arÄ] 34</p>
<p>athÅÌ  paÃ±chÄÌká¹£arÄ paÌ á¹ktiá¸¥ pÄá¹ktÅÌ yaÌ jÃ±Å yaÌ jÃ±amÄÌ vÄvaÌ rundhÄÌ  pathyÄgÌ svaÌ stimaÌyajaÌ -nprÄchÄ«ÌmÄÌ va tayÄÌ  diÅaÌ -mprÄjÄÌnannaÌ gninÄÌ daká¹£iÌ á¹Ä sÅmÄÌna praÌ tÄ«chÄ«gá¹Ì saviÌ trÅdÄ«ÌchÄ«Ì -madiÌtyÅÌ rdhvÄ-mpathyÄgÌ svaÌ stiá¹ à¤yaÌjatiÌ  prÄchÄ«ÌmÄÌ va tayÄÌ  diÅaÌ -mpra jÄÌnÄtiÌ  pathyÄgÌ svaÌ stimiÌ á¹£á¹­vÄ-'gnÄ«á¹£ÅmauÌ yajatiÌ  chaká¹£uÌá¹£Ä«Ì  vÄ ÄÌ tÄ yaÌ jÃ±asyaÌ  yadaÌ gnÄ«á¹£ÅmauÌ  tÄbhyÄÌmÄÌ vÄnuÌ paÅya- [paÅyati, aÌ gnÄ«á¹£ÅmÄÌ-viÌ á¹£á¹­vÄ] 35</p>
<p>-tyaÌ gnÄ«á¹£ÅmÄÌ-viÌ á¹£á¹­vÄ saÌviÌ tÄraÌá¹ yajati saviÌ tá¹praÌsÅ«ta ÄÌ vÄnuÌ paÅyati saviÌ tÄraÌmiÌ á¹£á¹­vÄ-'diÌtiá¹ yajatÄ«Ì yaá¹ vÄ adiÌtiraÌ syÄmÄÌ va praÌtiÌ á¹£á¹­hÄyÄnuÌ paÅyaÌ tyadiÌtimiÌ á¹£á¹­vÄ mÄÌruÌ tÄ«má¹chaÌ manvÄÌha maÌ rutÅÌ  vai dÄÌ vÄnÄÌ á¹ viÅÅÌ dÄvaviÌ Åa-á¹khaluÌ  vai kalpaÌmÄna-mmanuá¹£yaviÌ ÅamanuÌ kalpatÄÌ  ya-nmÄÌruÌ tÄ«má¹chaÌmaÌ nvÄhaÌ viÌ ÅÄ-á¹kLâiptyaiÌ brahmavÄÌ dinÅÌ vadanti prayÄÌ javaÌdananÅ«yÄÌ ja-mprÄÌyaÌ á¹Ä«yaÌ-á¹kÄÌ ryaÌ-manÅ«yÄÌ javaÌ- [-manÅ«yÄÌ javaÌt, aÌ praÌ yÄÌ ja-muÌdayaÌ nÄ«yaÌ ] 36</p>
<p>-daprayÄÌ ja-muÌdayaÌ nÄ«yaÌ -mitÄ«Ì mÄ vai praÌyÄÌ jÄ aÌ mÄ« aÌnÅ«yÄÌ jÄ-ssaiva sÄ yaÌ jÃ±asyaÌ  santaÌtiÌ sta-ttathÄÌ  na kÄÌ ryaÌmÄÌ tmÄ vai praÌyÄÌ jÄá¸¥ praÌ jÄ-'nÅ«ÌyÄÌ jÄ ya-tpraÌyÄÌ jÄ-naÌntariÌ yÄdÄÌ tmÄnaÌmaÌ -ntariÌyÄÌ -dyadaÌnÅ«yÄÌ jÄ-naÌntariÌ yÄ-tpraÌ jÄmaÌ ntariÌyÄÌ dyataÌ á¸¥ khaluÌ  vai yaÌ jÃ±asyaÌ  vitaÌtasyaÌ  na kriÌ yatÄÌ  tadanuÌ yaÌ jÃ±aá¸¥ parÄÌ bhavati yaÌ jÃ±a-mpaÌrÄÌ bhavaÌntaÌ á¹ yajaÌmÄÌ nÅ-'nuÌ  [-à¤yajaÌmÄÌ nÅ-'nuÌ, parÄÌ bhavati] 37</p>
<p>parÄÌ bhavati prayÄÌ javaÌdÄÌ vÄ-nÅ«ÌyÄÌ javaÌ-tprÄyaÌ á¹Ä«yaÌ-á¹kÄÌ ryaÌ-mprayÄÌ javaÌdanÅ«yÄÌ javaÌ-dudayaÌ nÄ«yaÌ -nnÄ-''tmÄnaÌmantaÌ rÄtiÌ  na praÌ jÄ-nna yaÌ jÃ±aá¸¥ paÌrÄÌ bhavaÌtiÌ  na yajaÌmÄnaá¸¥ prÄyaÌ á¹Ä«yaÌsya niá¹£kÄÌ sa uÌdayaÌ nÄ«yaÌmaÌ bhi nirvaÌpatiÌ  saiva sÄ yaÌ jÃ±asyaÌ  santaÌtiÌ ryÄá¸¥ prÄÌyaÌ á¹Ä«yaÌsya yÄÌ jyÄÌ ya-ttÄ uÌdayaÌ nÄ«yaÌsya yÄÌ jyÄÌá¸¥ kuÌ ryÄ-tparÄÌá¹aÌ muá¹ lÅÌ kamÄ rÅÌhÄ-tpraÌ mÄyuÌka-ssyÄÌ dyÄá¸¥ prÄÌyaÌ á¹Ä«yaÌsya purÅ-'nuvÄÌ kyÄÌstÄ uÌdayaÌ nÄ«yaÌsya yÄÌ jyÄÌá¸¥ karÅtyaÌ sminnÄÌ va lÅÌ kÄ pratiÌ tiá¹£á¹­hati à¥¥ 38 à¥¥<br/>
<b>(prajÃ±ÄÌtyai - paÅyatya - nÅ«yÄÌ javaÌ  - dyajaÌmÄÌ nÅ-'nuÌ - purÅnuvÄÌ kyÄÌstÄ - aÌ á¹£á¹­au chaÌ) (a. 5)</b></p>
<p>kaÌ drÅ«ÅchaÌ  vai suÌpaÌ rá¹Ä« chÄÌ-''tmarÅ«Ì payÅÌraspardhÄtÄÌ gá¹Ì  sÄ kaÌ drÅ«-ssuÌpaÌ rá¹Ä«maÌjayaÌ -thsÄ-'braÌvÄ«-ttá¹Ì tÄ«yaÌsyÄmiÌ tÅ diÌ vi sÅmaÌ stamÄ haÌraÌ  tÄnÄÌ -''tmÄnaÌ -nniá¹£krÄ«Ìá¹Ä«Ì á¹£vÄtÄ«Ì yaá¹ vai kaÌ drÅ«raÌ sau suÌpaÌ rá¹Ä« ChandÄgá¹Ìsi saupará¹ÄÌ yÄ-ssÄbraÌvÄ«daÌ smai vai piÌ tarauÌ puÌ trÄ-nbiÌbhá¹ta-stá¹Ì tÄ«yaÌsyÄmiÌ tÅ diÌ vi sÅmaÌ stamÄ haÌraÌ  tÄnÄÌ -''tmÄnaÌ -nniá¹£krÄ«Ìá¹Ä«Ì á¹£vÄ- [niá¹£krÄ«Ìá¹Ä«Ì á¹£va, itiÌ mÄ] 39</p>
<p>-tiÌ mÄ kaÌ drÅ«raÌvÅchaÌ ditiÌ  jagaÌ tyudaÌpataÌ -chchatuÌrdaÅÄká¹£arÄ saÌ tÄ« sÄ 'prÄÌpyaÌ  nyaÌvartataÌ  tasyaiÌ  dvÄ aÌ ká¹£arÄÌ amÄ«yÄtÄÌ gá¹Ì  sÄ paÌ ÅubhiÌÅcha dÄ«Ì ká¹£ayÄÌ  chÄ-'gaÌchChaÌ -ttasmÄÌ jjagaÌtÄ«Ì  ChandaÌsÄ-mpaÅaÌ vyaÌtamÄÌ  tasmÄÌ-tpaÅuÌ mantaÌ-ndÄ«Ì ká¹£ÅpaÌ namati triÌ á¹£á¹­ugudaÌpataÌ -ttrayÅÌdaÅÄká¹£arÄ saÌ tÄ« sÄ 'prÄÌpyaÌ  nyaÌvartataÌ  tasyaiÌ  dvÄ aÌ ká¹£arÄÌ amÄ«yÄtÄÌ gá¹Ì  sÄ daká¹£iÌá¹ÄbhiÅchaÌ  [daká¹£iÌá¹ÄbhiÅcha, tapaÌsÄÌ ] 40</p>
<p>tapaÌsÄÌ  chÄ-'gaÌchChaÌ -ttasmÄÌ-ttriÌ á¹£á¹­ubhÅÌ lÅÌ kÄ mÄddhyaÌndinÄÌ  savaÌnÄÌ  daká¹£iÌá¹Ä nÄ«yanta ÄÌ ta-tkhaluÌ  vÄva tapaÌ  ityÄÌhuÌ rya-ssva-ndadÄÌ tÄ«tiÌ gÄyaÌ tryudaÌpataÌ chchatuÌraká¹£arÄ saÌ tyaÌjayÄÌ  jyÅtiÌá¹£ÄÌ  tamaÌsyÄ aÌ jÄ-'bhyaÌrundhaÌ  tadaÌ jÄyÄÌ ajaÌ tvagá¹ sÄ sÅmaÌ -Ã±chÄ-''haÌrachchaÌ tvÄriÌ chÄÌ ká¹£arÄÌá¹iÌ  sÄ-'á¹£á¹­Äká¹£aÌrÄÌ  samaÌpadyata brahmavÄÌ dinÅÌ vadantiÌ  [brahmavÄÌ dinÅÌ vadanti, kasmÄÌ-thsaÌ tyÄ-] 41</p>
<p>kasmÄÌ-thsaÌ tyÄ-dgÄÌyaÌ trÄ« kaniÌá¹£á¹­hÄÌ  ChandaÌsÄgá¹ saÌ tÄ« yaÌjÃ±amuÌ kha-mparÄ«ÌyÄÌ yÄtiÌ  yadÄÌ vÄda-ssÅmaÌ mÄ-'haÌraÌ -ttasmÄÌ-dyajÃ±amuÌ kha-mparyaiÌ -ttasmÄÌ-ttÄjaÌ svinÄ«ÌtamÄ paÌ dbhyÄ-ndvÄ savaÌnÄ saÌ magá¹Ìhá¹ÄÌ -nmukhÄÌ naikaÌ á¹ yanmukhÄÌna saÌ magá¹Ìhá¹ÄÌ -ttadaÌdhayaÌ -ttasmÄÌ -ddvÄ savaÌnÄ ÅuÌ kraÌvatÄ« prÄtassavaÌ na-Ã±chaÌ  mÄddhyaÌndina-Ã±chaÌ  tasmÄÌ-ttá¹tÄ«ya savaÌ na á¹ÌjÄ«Ì á¹£amaÌ bhi á¹£uÌá¹vanti dhÄ«Ì tamiÌvaÌ  hi manyaÌnta [hi manyaÌntÄ, ÄÌ ÅiraÌ mavaÌ nayati] 42</p>
<p>ÄÌ ÅiraÌ mavaÌ nayati saÅukraÌ tvÄyÄthÅÌ  sa-mbhaÌratyÄÌ vainaÌ -ttagá¹ sÅmaÌ-mÄhriÌ yamÄÌá¹a-á¹gandhaÌ rvÅ viÌ ÅvÄvaÌsaÌ á¸¥ paryaÌmuá¹£á¹ÄÌ -thsa tiÌ srÅ rÄtrÄ«Ì á¸¥ pariÌmuá¹£itÅ-'vasaÌ -ttasmÄÌ-ttiÌ srÅ rÄtrÄ«Ìá¸¥ krÄ«Ì ta-ssÅmÅÌ vasatiÌ  tÄ dÄÌ vÄ aÌbruvaÌ n-thstrÄ«kÄÌmÄÌ  vai gaÌndhaÌ rvÄ sstriÌ yÄ niá¹£krÄ«Ìá¹ÄÌ mÄtiÌ  tÄ vÄchaÌ ggÌ  striyaÌ mÄkaÌhÄyanÄ«-á¹ká¹Ì tvÄ tayÄÌ  niraÌkrÄ«á¹aÌ n-thsÄ rÅÌ hi-drÅ«Ì pa-á¹ká¹Ì tvÄ gaÌndhaÌ rvÄbhyÅÌ- [gaÌndhaÌ rvÄbhyaÌá¸¥, aÌ paÌ kramyÄÌtiá¹£á¹­haÌ -tta-drÅÌ hitÅÌ ] 43</p>
<p>-'paÌ kramyÄÌtiá¹£á¹­haÌ -tta-drÅÌ hitÅÌ  janmaÌ  tÄ dÄÌ vÄ aÌbruvaÌ nnapaÌ yuÌ á¹£madakraÌmÄ«Ì -nnÄsmÄnuÌ -pÄvaÌrtatÄÌ  vi hvaÌyÄmahÄÌ  itiÌ  brahmaÌ gandhaÌ rvÄ avaÌdaÌ nnagÄÌya-ndÄÌ vÄ-ssÄ dÄÌ vÄ-ngÄyaÌta uÌ pÄvaÌrtataÌ  tasmÄÌ -dgÄyaÌntaÌ ggÌ  striyaÌá¸¥ kÄmayantÄÌ  kÄmuÌkÄ ÄnaÌ ggÌ  striyÅÌ bhavantiÌ  ya ÄÌ vaá¹ vÄdÄthÅÌ  ya ÄÌ vaá¹ viÌ dvÄnapiÌ  janyÄÌá¹£uÌ  bhavaÌtiÌ  tÄbhyaÌ ÄÌ va daÌdatyuÌ ta ya-dbaÌ hutaÌyÄÌ  [ya-dbaÌ hutaÌyÄá¸¥, bhavaÌ ntyÄkaÌhÄyanyÄ] 44</p>
<p>bhavaÌ ntyÄkaÌhÄyanyÄ krÄ«á¹Äti vÄÌ chaivainaÌ gá¹Ì  sarvaÌyÄ krÄ«á¹ÄtiÌ  tasmÄÌ dÄkaÌhÄyanÄ manuÌ á¹£yÄÌ vÄchaÌá¹ vadaÌ ntyakÅ«Ìá¹­aÌ yÄ 'kaÌrá¹aÌ yÄ-' kÄÌá¹aÌ yÄÅlÅÌá¹aÌ yÄ 'saÌptaÅaphayÄ krÄ«á¹ÄtiÌ  sarvaÌyaiÌ vainaÌ-á¹krÄ«á¹ÄtiÌ  yachChvÄÌ tayÄÌ krÄ«á¹Ä«Ì yÄ-dduÌ ÅcharmÄÌ  yajaÌmÄna-ssyÄÌ dya-tká¹Ì á¹£á¹ayÄÌ-'nuÌ staraÌá¹Ä« syÄ-tpraÌ mÄyuÌkÅÌ  yajaÌmÄna-ssyÄÌ dya-ddviÌrÅ«Ì payÄÌ  vÄrtraÌghnÄ« syÄÌ -thsa vÄÌ -'nya-Ã±jiÌnÄ«Ì yÄ-ttaá¹ vÄÌ -'nyÅ jiÌnÄ«yÄdaruÌ á¹ayÄÌ piá¹gÄÌ ká¹£yÄ krÄ«Ìá¹ÄtyÄÌ tadvai sÅmaÌsya rÅ«Ì paggâ svayaiÌ vainaÌ-ndÄÌ vataÌyÄ krÄ«á¹Äti à¥¥ 45 à¥¥<br/>
<b>(niá¹£krÄ«Ìá¹Ä«á¹£vaÌ  - daká¹£iÌá¹ÄbhiÅcha - vadantiÌ  - manyaÌntÄ-gandhaÌ rvÄbhyÅÌ-baÌ hutaÌyÄá¸¥-piá¹gÄÌ ká¹£yÄ-daÅaÌ cha ) (a. 6)</b></p>
<p>taddhiraÌá¹yamabhavaÌ -ttasmÄÌdaÌ dbhyÅ hiraÌá¹ya-mpunanti brahmavÄÌ dinÅÌ vadantiÌ  kasmÄÌ-thsaÌ tyÄdaÌnaÌ sthikÄÌna praÌ jÄá¸¥ praÌ vÄ«yaÌntÄ 'sthaÌ nvatÄ«ÌrjÄyantaÌ  itiÌ  yaddhiraÌá¹ya-á¹ghá¹Ì tÄÌ-'vaÌ dhÄyaÌ juÌ hÅtiÌ  tasmÄÌdanaÌ sthikÄÌna praÌ jÄá¸¥ pra vÄ«ÌyantÄ 'sthaÌ nvatÄ«ÌrjÄyanta ÄÌ tadvÄ aÌ gnÄá¸¥ priÌ ya-ndhÄmaÌ  ya-dghá¹Ì ta-ntÄjÅÌ  hiraÌá¹yamiÌ yantÄÌ Åukra taÌ nÅ«riÌ daá¹ varchaÌ  ityÄÌhaÌ  satÄÌjasamÄÌ vainaÌ gá¹Ì  sataÌnu- [sataÌnum, kaÌ rÅÌ tyathÅÌ ] 46</p>
<p>-á¹karÅÌ tyathÅÌ  sa-mbhaÌratyÄÌ vainaÌ á¹ yadabaÌddhama-vadaÌ ddhyÄ-dgarbhÄÌá¸¥ praÌ jÄnÄÌ-mparÄÌ pÄtuÌkÄ-ssyurbaÌ ddhamavaÌ dadhÄtiÌ  garbhÄÌá¹ÄÌ -ndhá¹tyaiÌ niá¹£á¹­aÌ rkyaÌ-mbaddhnÄti praÌ jÄnÄÌ-mpraÌ janaÌnÄyaÌ  vÄgvÄ ÄÌ á¹£Ä ya-thsÅÌmaÌ krayaÌá¹Ä«Ì  jÅ«raÌ sÄ«tyÄÌhaÌ  yaddhi manaÌsÄÌ  javaÌtÄÌ  ta-dvÄÌ chÄ vadaÌti dhá¹Ì tÄ manaÌ sÄtyÄÌhaÌ  manaÌsÄÌ  hi vÄgdhá¹Ì tÄ juá¹£á¹­ÄÌ  viá¹£á¹aÌvaÌ  ityÄÌha [  ] 47</p>
<p>yaÌ jÃ±Å vai viá¹£á¹uÌ ryaÌ jÃ±ÄyaiÌ vainÄÌ -Ã±juá¹£á¹­ÄÌ-á¹karÅtiÌ  tasyÄÌstÄ saÌ tyasaÌvasaá¸¥ prasaÌ va ityÄÌha saviÌ tá¹-praÌsÅ«tÄmÄÌ va vÄchaÌ mavaÌ rundhÄÌ  kÄá¹á¸ÄÌkÄá¹á¸ÄÌ  vai kriÌ yamÄÌá¹Ä yaÌ jÃ±agá¹ raká¹£Ägá¹Ìsi jighÄgá¹santyÄÌ á¹£a khaluÌ  vÄ araÌká¹£ÅhataÌ á¸¥ panthÄÌ  yÅÌ-'gnÄÅchaÌ  sÅ«ryaÌsya chaÌ  sÅ«ryaÌsyaÌ  chaká¹£uÌ rÄ-'ruÌhamaÌ gnÄraÌ ká¹£á¹aá¸¥ kaÌ nÄ«niÌkÄÌ mityÄÌhaÌ  ya ÄÌ vÄraÌká¹£ÅhataÌ á¸¥ panthÄÌ stagá¹ saÌ mÄrÅÌhatiÌ  [saÌ mÄrÅÌhati, vÄgvÄ ÄÌ á¹£Ä] 48</p>
<p>vÄgvÄ ÄÌ á¹£Ä ya-thsÅÌmaÌ krayaÌá¹Ä«Ì  chidaÌsi maÌ nÄ-'sÄ«tyÄÌhaÌ  ÅÄstyÄÌ vainÄÌmÄÌ ta-ttasmÄÌchChiÌ á¹£á¹­Äá¸¥ praÌ jÄ jÄÌyantÄÌ  chidaÌ sÄ«tyÄÌhaÌ  yaddhi manaÌsÄ chÄÌ tayaÌtÄÌ  ta-dvÄÌ chÄ vadaÌti maÌ nÄ-'sÄ«tyÄÌhaÌ  yaddhi manaÌsÄ-'bhiÌ gachChaÌtiÌ  ta-tkaÌ rÅtiÌ  dhÄ«raÌ sÄ«tyÄÌhaÌ  yaddhi manaÌsÄÌ  dhyÄyaÌtiÌ  ta-dvÄÌ chÄ [  ] 49</p>
<p>vadaÌtiÌ  daká¹£iÌá¹ÄÌ -'sÄ«tyÄÌhaÌ  daká¹£iÌá¹ÄÌ  hyÄÌá¹£Ä yaÌ jÃ±iyÄÌ -'sÄ«tyÄÌha yaÌ jÃ±iyÄÌmÄÌ vainÄÌ-á¹karÅti ká¹£aÌ triyÄÌ sÄ«tyÄÌha ká¹£aÌ triyÄÌ  hyÄÌá¹£Ä 'diÌtirasyubhaÌ yataÌÅÅÄ«Ì râá¹£á¹Ä«tyÄÌhaÌ  yadÄÌ vÄ-''diÌ tyaá¸¥ prÄÌyaÌ á¹Ä«yÅÌ yaÌ jÃ±ÄnÄÌmÄdiÌ tya uÌdayaÌ nÄ«yaÌ -stasmÄÌdÄÌ vamÄÌhaÌ  yadabaÌddhÄÌ  syÄdayaÌtÄ syÄÌ dya-tpaÌdibaÌ ddhÄ-'nuÌ staraÌá¹Ä« syÄ-tpraÌ mÄyuÌkÅÌ  yajaÌmÄna-ssyÄÌ - [yajaÌmÄna-ssyÄt, ya-tkaÌrá¹agá¹hÄ«Ì tÄ] 50</p>
<p>-dya-tkaÌrá¹agá¹hÄ«Ì tÄ vÄrtraÌghnÄ« syÄÌ -thsa vÄÌ -'nya-Ã±jiÌnÄ«Ì yÄ-ttaá¹ vÄÌ -'nyÅ jiÌnÄ«yÄnmiÌ trastvÄÌ paÌ di baÌddhnÄÌ tvityÄÌha miÌ trÅ vai ÅiÌ vÅ dÄÌ vÄnÄÌ -ntÄnaiÌ vainÄÌ-mpaÌ di baÌddhnÄti pÅ«Ì á¹£Ä-'ddhvaÌnaá¸¥ pÄÌ tvityÄÌhÄÌ yaá¹ vai pÅ«Ì á¹£ÄmÄmÄÌ vÄsyÄÌ adhiÌ pÄmaÌkaÌ -ssamaÌá¹£á¹­yÄÌ  indrÄÌ yÄ-ddhyaÌká¹£ÄÌ yÄtyÄÌ hÄndraÌmÄÌ vÄsyÄÌ  addhyaÌká¹£a-á¹karÅÌ - [addhyaÌká¹£a-á¹karÅti, anuÌ tvÄ mÄÌ tÄ] 51</p>
<p>-tyanuÌ tvÄ mÄÌ tÄ maÌnyatÄÌ manuÌ piÌ tÄtyÄÌ hÄ-nuÌmatayaiÌ vainaÌyÄ krÄ«á¹ÄtiÌ  sÄ dÄÌvi dÄÌ vamachChÄÌ hÄ«tyÄÌha dÄÌ vÄ« hyÄÌá¹£Ä dÄÌ va-ssÅmaÌ  indrÄÌyaÌ  sÅmaÌ mityÄÌ hÄndrÄÌyaÌ  hi sÅmaÌ ÄhriÌ yatÄÌ  yadÄÌ ta-dyajuÌ rna brÅ«Ì yÄ-tparÄÌchyÄÌ va sÅÌmaÌ krayaÌá¹Ä«yÄ-druÌ drastvÄ-'' vaÌrtayaÌ tvityÄÌha ruÌ drÅ vai krÅ«Ì rÅ [ruÌ drÅ vai krÅ«Ì raá¸¥, dÄÌ vÄnÄÌ -ntamÄÌ vÄsyaiÌ] 52</p>
<p>dÄÌ vÄnÄÌ -ntamÄÌ vÄsyaiÌ paÌ rastÄÌ-ddadhÄÌ tyÄvá¹Ìttyai krÅ«Ì ramiÌvaÌ  vÄ ÄÌ ta-tkaÌrÅtiÌ  ya-druÌ drasyaÌ kÄ«Ì rtayaÌti miÌ trasyaÌ paÌ thÄtyÄÌhaÌ  ÅÄntyaiÌ vÄÌ chÄ vÄ ÄÌ á¹£a vi krÄ«Ìá¹Ä«tÄÌ  ya-ssÅÌmaÌ krayaÌá¹yÄ svaÌ sti sÅmaÌsakhÄÌ  punaÌ rÄhiÌ saÌ ha raÌ yyÄtyÄÌha vÄÌ chaiva viÌ krÄ«yaÌ  punaÌrÄÌ tman vÄchaÌ-ndhaÌ ttÄ-'nuÌpadÄsukÄ-'syaÌ  vÄgbhaÌvatiÌ  ya ÄÌ vaá¹ vÄdaÌ à¥¥ 53 à¥¥<br/>
<b>(sataÌnuÌ á¹ - à¤viá¹£á¹aÌvaÌ  ityÄÌha - saÌ mÄrÅÌhatiÌ  - dhyÄyaÌtiÌ  ta-dvÄÌ chÄ - yajaÌmÄna-ssyÄt - karÅti - krÅ«Ì rÅ - vÄdaÌ) (a. 7)</b></p>
<p>á¹£aá¹­ paÌ dÄnyanuÌ  ni krÄÌmati á¹£aá¸aÌ haá¹ vÄnnÄtiÌ vadatyuÌ ta saÌá¹vathsaÌ rasyÄyaÌnÄÌ  yÄvaÌtyÄÌ va vÄktÄmavaÌ rundhÄ saptaÌ mÄ paÌ dÄ juÌhÅti saÌ ptapaÌdÄÌ  ÅakvaÌrÄ« paÌ ÅavaÌ -ÅÅakvaÌrÄ« paÌ ÅÅ«nÄÌ vÄvaÌ rundhÄ saÌ pta grÄÌ myÄá¸¥ paÌ ÅavaÌ-ssaÌ ptÄ-''raÌ á¹yÄ-ssaÌ pta ChandÄgÌ-syuÌ bhayaÌ syÄ-vaÌruddhyaiÌ  vasvyaÌsi ruÌ drÄ-'sÄ«tyÄÌha rÅ«Ì pamÄÌ vÄsyÄÌ ÄÌ ta-nmaÌhiÌ mÄnaÌ á¹- [ÄÌ ta-nmaÌhiÌ mÄnaÌm, vyÄchaÌá¹£á¹­ÄÌ  bá¹haÌ spatiÌstvÄ] 54</p>
<p>-à¤vyÄchaÌá¹£á¹­ÄÌ  bá¹haÌ spatiÌstvÄ suÌ mnÄ raÌá¹vaÌ tvityÄÌhaÌ  brahmaÌ  vai dÄÌ vÄnÄÌ -mbá¹haÌ spatiÌ -rbrahmaÌá¹aiÌ vÄsmaiÌ paÌ ÅÅ«navaÌ rundhÄ ruÌ drÅ vasuÌbhiÌ rÄ chiÌkÄÌ tvityÄÌ hÄ-''vá¹Ìttyai pá¹thiÌ vyÄstvÄÌ mÅ«Ì rdhannÄ jiÌgharmi dÄvaÌ yajaÌnaÌ  ityÄÌha pá¹thiÌ vyÄ hyÄÌá¹£a mÅ«Ì rdhÄ ya-ddÄÌvaÌ yajaÌnaÌ miá¸ÄÌyÄá¸¥ paÌ da ityÄÌ hÄá¸ÄÌyaiÌ  hyÄÌta-tpaÌ daá¹ ya-thsÅÌmaÌ krayaÌá¹yai ghá¹Ì tavaÌtiÌ  svÄhÄ- [svÄhÄÌ, ityÄÌhaÌ ] 55</p>
<p>-tyÄÌhaÌ  yadÄÌ vÄsyaiÌ paÌ dÄ-dghá¹Ì tamapÄ«Ìá¸yataÌ  tasmÄÌdÄÌ vamÄÌhaÌ  yadaÌddhvaÌ ryuraÌnaÌ gnÄvÄhuÌti-Ã±juhuÌ yÄdaÌ ndhÅÌ-'ddhvaÌ ryu-ssyÄÌ -draká¹£Ägá¹Ìsi yaÌ jÃ±agá¹ haÌnyuÌ rÌ hiraÌá¹yamuÌ pÄsyaÌ juhÅtyagniÌ vatyÄÌ va juÌhÅtiÌ  nÄndhÅÌ-'ddhvaÌ ryu rbhavaÌtiÌ  na yaÌ jÃ±agá¹ raká¹£Ägá¹Ìsi ghnantiÌ  kÄá¹á¸ÄÌkÄá¹á¸ÄÌ  vai kriÌ yamÄÌá¹Ä yaÌ jÃ±agá¹ raká¹£Ägá¹Ìsi jighÄgá¹santiÌ  pariÌlikhitaÌ gá¹Ì  raká¹£aÌ á¸¥ pariÌlikhitÄÌ  arÄÌtayaÌ  ityÄÌhaÌ  raká¹£aÌsÄÌ -mapaÌhatyÄ [raká¹£aÌsÄÌ -mapaÌhatyai, iÌ damaÌ hagá¹] 56</p>
<p>iÌ damaÌ hagá¹ raká¹£aÌsÅ grÄ«Ì vÄ apiÌ ká¹ntÄmiÌ  yÅÌ-'smÄ-ndvÄá¹£á¹­iÌ  ya-Ã±chaÌ vaÌ ya-ndviÌ á¹£ma ityÄÌhaÌ  dvau vÄva puruÌá¹£auÌ  ya-Ã±chaiÌ va dvÄá¹£á¹­iÌ  yaÅchaiÌnaÌ -ndvÄá¹£á¹­iÌ  tayÅÌ-rÄÌ vÄ-'naÌntarÄya-á¹grÄ«Ì vÄá¸¥ ká¹Ìntati paÌ ÅavÅÌ  vai sÅÌmaÌ krayaÌá¹yai paÌ daá¹ yÄÌvattmÅ«Ì tagá¹ saá¹ vaÌpati paÌ ÅÅ«nÄÌ vÄvaÌ rundhÄÌ -'smÄ rÄyaÌ  itiÌ  saá¹ à¤vaÌpatyÄÌ tmÄnaÌ-mÄÌ vÄddhvaÌ ryuá¸¥ -[-mÄÌ vÄddhvaÌ ryuá¸¥, paÌ ÅubhyÅÌ ] 57</p>
<p>paÌ ÅubhyÅÌ  nÄntarÄÌtiÌ  tvÄ rÄyaÌ  itiÌ  yajaÌmÄnÄyaÌ  pra yaÌchChatiÌ  yajaÌmÄna ÄÌ va raÌ yi-ndaÌdhÄtiÌ  tÅtÄÌ  rÄyaÌ  itiÌ  patniÌyÄ aÌ rdhÅ vÄ ÄÌ á¹£a ÄÌ tmanÅÌ  ya-tpatnÄ«Ì  yathÄÌ gá¹Ì hÄá¹£uÌ nidhaÌ ttÄ tÄÌ dá¹gÄÌ va ta-ttvaá¹£á¹­Ä«ÌmatÄ« tÄ sapÄÌ yÄtyÄÌhaÌ  tvaá¹£á¹­ÄÌ  vai paÌÅÅ«Ì nÄ-mmiÌthuÌ nÄnÄgá¹Ì rÅ«paÌ ká¹-drÅ«Ì pamÄÌ va paÌ Åuá¹£uÌ dadhÄtyaÌ smai vai lÅÌ kÄyaÌ  gÄrâhaÌpatyaÌ  Ä dhÄ«ÌyatÄÌ  'muá¹£mÄÌ ÄhavaÌ nÄ«yÅÌ  ya-dgÄrâhaÌpatya upaÌ vapÄÌdaÌ smin à¤lÅÌ kÄ paÌÅaÌ mÄn-thsyÄÌ -dyadÄÌhavaÌ nÄ«yÄÌ  'muá¹£miÌn à¤lÅÌ kÄ paÌÅuÌ mÄn-thsyÄÌduÌ bhayÅÌ rupaÌ vapatyuÌ bhayÅÌrÄÌ vainaÌá¹ lÅÌ kayÅÌá¸¥ paÅuÌ mantaÌ-á¹karÅti à¥¥ 58 à¥¥<br/>
<b>(maÌ hiÌ mÄnaÌ ggÌ  - svÄhÄ - 'paÌhatyÄ - adhvaÌ ryu - dhÄ«ÌyatÄÌ  - chatuÌrvigá¹ÅatiÅcha) (a. 8)</b></p>
<p>braÌ hmaÌ vÄÌ dinÅÌ vadanti viÌ chityaÌ -ssÅmÄ(3) na viÌ chityÄ(3) itiÌ  sÅmÅÌ  vÄ Åá¹£aÌdhÄ«nÄÌ gá¹Ì  rÄjÄÌ  tasmiÌ nÌ . yadÄpaÌnna-á¹grasiÌ tamÄÌ vÄsyaÌ  ta-dya-dviÌchinuÌ yÄ-dyathÄÌ  ''syÄÌdgrasiÌ ta-nniÌá¹£khiÌ datiÌ tÄÌ dá¹gÄÌ va tadyanna viÌchinuÌ yÄ-dyathÄÌ  'ká¹£annÄpaÌnnaá¹ viÌ dhÄvaÌti tÄÌ dá¹gÄÌ va ta-tká¹£ÅdhuÌkÅ 'ddhvaÌ ryu-ssyÄ-tká¹£ÅdhuÌkÅÌ  yajaÌmÄnaÌ -ssÅmaÌvikrayiÌ n-thsÅmagá¹Ì ÅÅdhaÌ yÄtyÄÌ va brÅ«ÌyÄÌ -dyadÄ«taÌraÌ á¹- [brÅ«ÌyÄÌ -dyadÄ«taÌram, yadÄ«taÌra-] 59</p>
<p>-à¤yadÄ«taÌra-muÌ bhayÄÌnaiÌ va sÅÌmavikraÌ yiá¹aÌ-marpayatiÌ  tasmÄÌ-thsÅmavikraÌ yÄ« ká¹£ÅdhuÌkÅ 'ruÌ á¹Å haÌ smÄÌ -''haupaÌvÄÅi-ssÅmaÌ krayaÌá¹a ÄÌ vÄha-ntá¹ÌtÄ«ya savaÌ namavaÌ rundhaÌ  itiÌ paÅÅ«Ì nÄ-Ã±charmaÌ-nmimÄ«tÄ paÌ ÅÅ«nÄÌ vÄvaÌ rundhÄ paÌ ÅavÅÌ  hi tá¹Ì tÄ«yaÌ gá¹Ì  savaÌnaÌ á¹ ya-á¹kÄÌ mayÄÌtÄpaÌ Åu-ssyÄÌ -dityá¹Ìká¹£aÌ ta-stasyaÌ mimÄ«taÌ rká¹£aá¹ vÄ aÌpaÅaÌ vya-maÌpaÌ ÅurÄÌ va bhaÌvatiÌ  ya-á¹kÄÌ mayÄÌta paÅuÌ mÄn-thsyÄÌ  - [  ] 60</p>
<p>-ditiÌ lÅmaÌ tastasyaÌ mimÄ«taiÌ tadvai paÌÅÅ«Ì nÄgá¹ rÅ«Ì pagá¹ rÅ«Ì pÄá¹aiÌ vÄ-'smaiÌ paÌ ÅÅ«navaÌ rundhÄ paÅuÌ mÄnÄÌ va bhaÌvatyaÌ pÄmantÄÌ krÄ«á¹ÄtiÌ  saraÌsamÄÌ vainaÌ-á¹krÄ«á¹ÄtyaÌ -mÄtyÅÌ -'sÄ«tyÄÌhÄÌ -'maivainaÌ-á¹kurutÄ ÅuÌ krastÄÌ  grahaÌ  ityÄÌha ÅuÌ krÅ hyaÌsyaÌ  grahÅ 'naÌ sÄ-'chChaÌ yÄti mahiÌ mÄnaÌ-mÄÌ vÄsyÄchChaÌ yÄÌ tyanaÌ sÄ- [yÄÌ tyanaÌ sÄ, achChaÌ] 61</p>
<p>-'chChaÌ yÄtiÌ  tasmÄÌ-danÅvÄÌ hyagá¹Ì saÌ mÄ jÄ«vaÌnaÌ á¹ yatraÌ  khaluÌ  vÄ ÄÌ tagá¹ ÅÄ«Ì râá¹£á¹Ä haraÌntiÌ  tasmÄÌchChÄ«râá¹£ahÄÌ ryaÌ-á¹giÌ rau jÄ«vaÌnamaÌ bhi tya-ndÄÌ vagá¹ saÌviÌ tÄraÌ mityatiÌ-chChandasaÌ rchÄ miÌmÄ«Ì tÄ 'tiÌchChandÄÌ  vai sarvÄÌá¹iÌ  ChandÄgá¹ÌsiÌ  sarvÄÌbhirÄÌ vainaÌ -Ã±ChandÅÌbhirmimÄ«tÄÌ  varâá¹£maÌ  vÄ ÄÌ á¹£Ä ChandaÌsÄÌ á¹ yadatiÌchChandÄÌ  yadatiÌchChandasaÌ rchÄ mimÄ«ÌtÄÌ  varâá¹£maiÌ vainagá¹Ì samÄÌ nÄnÄÌ-á¹karÅÌ tyÄkaÌyaikayÅÌ -thsargaÌ- [-á¹karÅÌ tyÄkaÌyaikayÅÌ -thsargaÌm, miÌ mÄ«Ì tÄ] 62</p>
<p>-mmimÄ«Ì tÄ 'yÄÌtayÄmniyÄyÄtayÄmniyaiÌ vainaÌ-mmimÄ«tÄÌ  tasmÄÌ nnÄnÄÌvÄ«ryÄ aÌ á¹gulaÌyaÌ -ssarvÄÌsvaá¹guÌ á¹£á¹­hamupaÌ  ni gá¹Ìhá¹ÄtiÌ  tasmÄÌ-thsaÌ mÄvaÌdvÄ«ryÅÌ -'nyÄbhiÌ-raÌ á¹guliÌbhiÌ stasmÄÌ -thsarvÄÌ  anuÌ  sa-Ã±chaÌratiÌ  ya-thsaÌ ha sarvÄÌbhiÌ rmimÄ«ÌtaÌ  saggâÅliÌá¹£á¹­Ä aÌ á¹gulaÌyÅ jÄyÄraÌ -nnÄkaÌyaikayÅÌ -thsargaÌ-mmimÄ«tÄÌ  tasmÄÌ -dvibhaÌktÄ jÄyantÄÌ  paÃ±chaÌ  ká¹tvÅÌ  yajuÌá¹£Ä mimÄ«tÄÌ  paÃ±chÄÌká¹£arÄ paÌ á¹ktiá¸¥ pÄá¹ktÅÌ yaÌ jÃ±Å yaÌ jÃ±amÄÌ vÄvaÌ rundhÄÌ  paÃ±chaÌ  ká¹tvaÌ-stÅ«Ì á¹£á¹Ä«- [ká¹tvaÌ-stÅ«Ì á¹£á¹Ä«m, daÅaÌ  sa-mpaÌdyantÄÌ ] 63</p>
<p>-ndaÅaÌ  sa-mpaÌdyantÄÌ  daÅÄÌká¹£arÄ viÌ rÄá¸annaÌá¹ viÌ rÄ-á¸viÌ rÄjaiÌ vÄnnÄdyaÌ mavaÌ rundhÄÌ  ya-dyajuÌá¹£ÄÌ  mimÄ«ÌtÄ bhÅ«Ì tamÄÌ vÄvaÌ rundhÄÌ  ya-ttÅ«Ì á¹£á¹Ä«-mbhaÌviÌ á¹£ya-dya-dvai tÄvÄÌnÄÌ va sÅmaÌ -ssyÄ-dyÄvaÌntaÌ -mmimÄ«ÌtÄÌ  yajaÌmÄnasyaiÌ va syÄÌ nnÄpiÌ sadaÌ syÄÌnÄ-mpraÌ jÄbhyaÌ stvÄtyupaÌ  samÅ«Ìhati sadaÌ syÄÌnÄÌ vÄnvÄ bhaÌjatiÌ  vÄsaÌ sÅpaÌ nahyati sarvadÄvaÌ tyaÌá¹ vai [  ] 64</p>
<p>vÄsaÌ -ssarvÄÌbhirÄÌ vainaÌ-ndÄÌ vatÄÌbhiÌ -ssamaÌrdhayati paÌ ÅavÅÌ  vai sÅmaÌá¸¥ prÄÌ á¹ÄyaÌ  tvÄtyupaÌ nahyati prÄÌ á¹amÄÌ va paÌ Åuá¹£uÌ dadhÄti vyÄÌ nÄyaÌ  tvÄtyanuÌ Åá¹nthati vyÄÌ namÄÌ va paÌ Åuá¹£uÌ dadhÄtiÌ  tasmÄÌ-thsvaÌ pantaÌ-mprÄÌ á¹Ä na jaÌhati à¥¥ 65 à¥¥<br/>
<b>(itaÌraá¹ - paÅuÌ mÄn-thsyÄÌ--dyÄÌ tyanaÌsÅÌ  - thsargaÌá¹ - tÅ«Ì á¹£á¹Ä«gá¹ - saÌrvadÄvaÌ tyaÌá¹ vai - trayaÌstrigá¹Åachcha) (a. 9)</b></p>
<p>ya-tkaÌ layÄÌ tÄ ÅaÌ phÄnaÌ tÄ krÄ«á¹ÄÌ nÄ«tiÌ  paá¹ÄÌ tÄgÅÌarghaÌ gá¹Ì  sÅmaÌ-á¹kuÌ ryÄdagÅÌarghaÌ á¹ yajaÌmÄnaÌ -magÅÌarghamaddhvaÌ ryu-á¹gÅstu maÌhiÌ mÄnaÌ -nnÄvaÌ tirÄÌ -dgavÄÌ tÄ krÄ«á¹ÄÌ nÄ«tyÄÌ va brÅ«ÌyÄ-dgÅaÌ rghamÄÌ va sÅmaÌ-á¹kaÌ rÅtiÌ gÅaÌ rghaá¹ yajaÌmÄna-á¹gÅaÌ rghamaÌddhvaÌ ryu-nna gÅrmaÌhiÌ mÄnaÌ mavaÌ tiratyaÌ jayÄÌ krÄ«á¹ÄtiÌ  sataÌpasamÄÌ vainaÌ-á¹krÄ«á¹ÄtiÌ  hiraÌá¹yÄna krÄ«á¹ÄtiÌ  saÅuÌkramÄÌ vai- [saÅuÌkramÄÌ va, ÄÌ naÌ -á¹krÄ«Ì á¹ÄÌ tiÌ  dhÄÌ nvÄ krÄ«Ìá¹ÄtiÌ ] 66</p>
<p>-naÌ-á¹krÄ«á¹Äti dhÄÌ nvÄ krÄ«Ìá¹ÄtiÌ  sÄÅiÌramÄÌ vainaÌ-á¹krÄ«á¹Ätyá¹á¹£aÌ bhÄá¹aÌ krÄ«á¹ÄtiÌ  sÄndraÌmÄÌ vainaÌ-á¹krÄ«á¹ÄtyanaÌ á¸uhÄÌ krÄ«á¹ÄtiÌ  vahniÌ rvÄ aÌnaÌ á¸vÄn. vahniÌnaiÌ va vahniÌ yaÌ jÃ±asyaÌ krÄ«á¹Äti mithuÌ nÄbhyÄÌ-á¹krÄ«á¹Äti mithuÌ nasyÄvaÌ-ruddhyaiÌ  vÄsaÌsÄ krÄ«á¹Äti sarvadÄvaÌ tyaÌá¹ vai vÄÌ sa-ssarvÄÌbhya ÄÌ vainaÌ-ndÄÌ vatÄÌbhyaá¸¥ krÄ«á¹ÄtiÌ  daÅaÌ  sa-mpaÌdyantÄÌ  daÅÄÌká¹£arÄ viÌ rÄá¸annaÌá¹ viÌ rÄ-á¸viÌ rÄjaiÌ vÄnnÄdyaÌ mavaÌ rundhÄÌ  [rundhÄ, tapaÌsa-staÌ nÅ«raÌsi] 67</p>
<p>tapaÌsa-staÌ nÅ«raÌsi praÌ jÄpaÌtÄÌ -rvará¹aÌ  ityÄÌha paÌ ÅubhyaÌ ÄÌ va tadaÌddhvaÌ -ryurni hnuÌta ÄÌ tmanÅ-'nÄÌvraskÄyaÌ  gachChaÌtiÌ  ÅriyaÌ -mpra paÌ ÅÅ«nÄÌpnÅtiÌ  ya ÄÌ vaá¹ vÄdaÌ ÅuÌ kra-ntÄÌ ÅuÌ krÄá¹aÌ krÄ«á¹ÄÌ mÄ«tyÄÌha yathÄ yaÌ jurÄÌ vaita-ddÄÌ vÄ vai yÄnaÌ  hiraÌá¹yÄnaÌ  sÅmaÌ makrÄ«Ìá¹aÌ -ntadaÌbhÄ«Ì á¹£ahÄÌ  punaÌ rÄ-'daÌdataÌ  kÅ hi tÄjaÌsÄ vikrÄÌ á¹£yataÌ  itiÌ  yÄnaÌ  hiraÌá¹yÄnaÌ  [hiraÌá¹yÄna, sÅmaÌ-] 68</p>
<p>sÅmaÌ-á¹krÄ«á¹Ä«Ì yÄ-ttadaÌbhÄ«Ì á¹£ahÄÌ  punaÌ rÄ daÌdÄ«taÌ  tÄjaÌ ÄÌ vÄ-''tma-ndhaÌttÄÌ -'smÄ jyÅtiÌ-ssÅmavikraÌ yiá¹iÌ  tamaÌ  ityÄÌhaÌ  jyÅtiÌrÄÌ va yajaÌmÄnÄ dadhÄtiÌ  tamaÌsÄ sÅmavikraÌ yiá¹aÌmarpayatiÌ  yadanuÌpagrathya haÌ nyÄ-ddaÌndaÌ ÅÅ«kÄÌ stÄgá¹ samÄgá¹Ì saÌ rpÄ-ssyuÌriÌ damaÌ hagá¹ saÌ rpÄá¹ÄÌ-ndandaÌ ÅÅ«kÄÌnÄ-á¹grÄ«Ì vÄ upaÌ grathnÄÌ mÄ«tyÄÌ hÄ-daÌndaÅÅ«kÄÌ stÄgá¹ samÄgá¹Ì saÌ rpÄ bhaÌvantiÌ  tamaÌsÄ sÅmavikraÌ yiá¹aÌá¹ viddhyatiÌ  svÄnaÌ  [svÄnaÌ, bhrÄjÄtyÄÌhaiÌ tÄ] 69</p>
<p>bhrÄjÄtyÄÌhaiÌ tÄ vÄ aÌ muá¹£miÌn à¤lÅÌ kÄ sÅmaÌmaraká¹£aÌ -ntÄbhyÅ-'dhiÌ  sÅmaÌ mÄ-'haÌraÌ nÌ . yadÄÌ tÄbhyaÌ-ssÅmaÌ krayaÌá¹ÄÌ -nnÄnuÌdiÌ ÅÄdakrÄ«ÌtÅ-'syaÌ  sÅmaÌ-ssyÄÌ nnÄsyaiÌ tÄÌ 'muá¹£miÌn à¤lÅÌ kÄ sÅmagá¹Ì raká¹£ÄyuÌ ryadÄÌ tÄbhyaÌ-ssÅmaÌ krayaÌá¹ÄnanudiÌ ÅatiÌ krÄ«Ì tÅÌ-'syaÌ  sÅmÅÌ bhavatyÄÌ tÄÌ-'syÄÌ muá¹£miÌn à¤lÅÌ kÄ sÅmagá¹Ì raká¹£anti à¥¥ 70 à¥¥<br/>
<b>(saÅuÌkramÄÌ va - ruÌndhaÌ  - itiÌ  yÄnaÌ  hiraÌá¹yÄnaÌ  - svÄnaÌ  - chatuÌÅchatvÄrigá¹Åachcha) (a. 10)</b></p>
<p>vÄÌ ruÌ á¹Å vai krÄ«Ì ta-ssÅmaÌ  upaÌnaddhÅ miÌ trÅ naÌ  ÄhiÌ  sumiÌtradhÄÌ  ityÄÌhaÌ  ÅÄntyÄÌ  indraÌsyÅÌ rumÄ viÌÅaÌ  daká¹£iÌá¹aÌ mityÄÌha dÄÌ vÄ vai yagá¹ sÅmaÌ makrÄ«Ìá¹a-ntamindraÌsyÅÌ rau daká¹£iÌá¹aÌ  Ä 'sÄÌdayannÄÌ á¹£a khaluÌ  vÄ ÄÌ tarâhÄ«ndrÅÌ  yÅ yajaÌtÄÌ  tasmÄÌdÄÌ vamÄÌ hÅdÄyuÌá¹£Ä svÄÌ yuá¹£ÄtyÄÌha dÄÌ vatÄÌ ÄÌ vÄ-nvÄÌ rabhyÅ- [ÄÌ vÄ-nvÄÌ rabhyÅt, tiÌ á¹£á¹­haÌ tyuÌ -rvaÌntariÌká¹£aÌ -] 71</p>
<p>-ttiÌá¹£á¹­hatyuÌ -rvaÌntariÌká¹£aÌ -manviÌ hÄ«tyÄÌhÄ-ntariká¹£adÄvaÌ tyÅÌ(1Ì ) hyÄÌtarâhiÌ  sÅmÅ-'diÌtyÄÌ -ssadÅÌ -'syadiÌtyÄÌ -ssadaÌ  Ä sÄ«Ì dÄtyÄÌha yathÄyaÌ jurÄÌ vaita-dvi vÄ ÄÌnamÄÌ tadaÌrdhayatiÌ  ya-dvÄÌruÌ á¹agá¹ santaÌ-mmaiÌ tra-á¹kaÌ rÅtiÌ vÄruÌ á¹yarchÄ-'' sÄÌdayatiÌ  svayaiÌ vainaÌ-ndÄÌ vataÌyÄÌ  samaÌrdhayatiÌ  vÄsaÌsÄ paÌ ryÄnaÌhyati sarvadÄvaÌ tyaÌá¹ vai vÄsaÌ -ssarvÄÌbhirÄÌ vai- [vÄsaÌ -ssarvÄÌbhirÄÌ va, ÄÌ naÌ -ndÄÌ vatÄÌbhiÌ -] 72</p>
<p>-naÌ-ndÄÌ vatÄÌbhiÌ -ssamaÌrdhayaÌ tyathÅÌ  raká¹£aÌsÄÌ mapaÌhatyaiÌ  vanÄÌá¹£uÌ  vyaÌntariÌká¹£a-ntatÄÌ nÄtyÄÌhaÌ  vanÄÌá¹£uÌ  hi vyaÌntariÌká¹£a-ntaÌ tÄnaÌ  vÄjaÌ marvaÌ thsvityÄÌhaÌ  vÄjaÌ ggÌ  hyarvaÌthsuÌ  payÅÌ aghniÌ yÄsvityÄÌhaÌ  payÅÌ  hyaÌghniÌ yÄsuÌ há¹Ì thsu kratuÌ mityÄÌha há¹Ì thsu hi kratuÌ á¹ varuÌá¹Å viÌ ká¹£vaÌgnimityÄÌhaÌ  varuÌá¹ÅÌ  hi viÌ ká¹£vaÌgni-ndiÌ vi sÅ«ryaÌ - [sÅ«ryaÌm, ityÄÌha diÌ vi hi] 73</p>
<p>-mityÄÌha diÌ vi hi sÅ«ryaÌ gá¹Ì  sÅmaÌ madrÄÌ vityÄÌhaÌ  grÄvÄÌá¹ÅÌ  vÄ adraÌyaÌ stÄá¹£uÌ  vÄ ÄÌ á¹£a sÅmaÌ-ndadhÄtiÌ  yÅ yajaÌtÄÌ  tasmÄÌdÄÌ vamÄÌ hÅduÌ  tya-Ã±jÄÌ tavÄÌdasaÌ mitiÌ sauÌ ryarchÄ ká¹Ìá¹£á¹ÄjiÌ na-mpraÌ tyÄnaÌhyatiÌ  raká¹£aÌsÄÌ mapaÌhatyÄÌ  usrÄÌ vÄtaÌ-ndhÅ«râá¹£ÄhÄÌ vityÄÌha yathÄyaÌ jurÄÌ vaita-tpra chyaÌvasva bhuvaspataÌ  ityÄÌha bhÅ«Ì tÄnÄÌ gÌ  hyÄÌ [bhÅ«Ì tÄnÄÌ gÌ á¹ hi, ÄÌ á¹£a patiÌ -rviÅvÄÌnyaÌ bhi] 74</p>
<p>-á¹£a patiÌ -rviÅvÄÌnyaÌ bhi dhÄmÄÌ nÄ«tyÄÌhaÌ  viÅvÄÌniÌ  hyÄÌ(1Ì ) á¹£ÅÌ-'bhi dhÄmÄÌni praÌ chyavaÌtÄÌ  mÄ tvÄÌ paripaÌ rÄ« viÌdaÌ dityÄÌhaÌ  yadÄÌ vÄda-ssÅmaÌmÄhriÌ yamÄÌá¹a-á¹gandhaÌ rvÅ viÌ ÅvÄvaÌsuá¸¥ paÌ ryamuÌá¹£á¹ÄÌ -ttasmÄÌ-dÄÌ vamÄÌ hÄpaÌrimÅá¹£ÄyaÌ  yajaÌmÄnasya svaÌ styayaÌnyaÌ sÄ«tyÄÌhaÌ  yajaÌmÄnasyaiÌ vaiá¹£a yaÌ jÃ±asyÄÌnvÄraÌ bhÅá¹ 'naÌvachChittyaiÌ  varuÌá¹ÅÌ  vÄ ÄÌ á¹£a yajaÌmÄnamaÌ bhyaitiÌ  ya- [yat, krÄ«Ì ta-ssÅmaÌ  upaÌnaddhÅÌ  namÅÌ] 75</p>
<p>-tkrÄ«Ì ta-ssÅmaÌ  upaÌnaddhÅÌ  namÅÌ miÌ trasyaÌ  varuÌá¹asyaÌ  chaká¹£aÌsaÌ  ityÄÌhaÌ  ÅÄntyÄÌ  Ä sÅmaÌ á¹ vahaÌntyaÌ gninÄÌ  pratiÌ tiá¹£á¹­hatÄÌ  tau saÌ bhaá¹vaÌntauÌ  yajaÌmÄnamaÌ bhi sa-mbhaÌvataá¸¥ puÌ rÄ khaluÌ  vÄvaiá¹£a mÄdhÄÌyÄÌ -''tmÄnaÌmÄÌ rabhyaÌ charatiÌ  yÅ dÄ«Ìká¹£iÌ tÅ yadaÌgnÄ«á¹£ÅÌ mÄ«yaÌ-mpaÌ ÅumÄÌ labhaÌta ÄtmaniÌ á¹£krayaÌá¹a ÄÌ vÄsyaÌ  sa tasmÄÌ -ttasyaÌ  nÄ-''ÅyaÌ-mpuruá¹£aniÌ á¹£krayaÌá¹a ivaÌ  hyathÅÌ  khalvÄÌhu raÌ gnÄ«á¹£ÅmÄÌbhyÄÌ á¹ vÄ indrÅÌ vá¹Ì tramaÌhaÌ nnitiÌ  yadaÌgnÄ«á¹£ÅÌ mÄ«yaÌ-mpaÌ ÅumÄÌ labhaÌtaÌ  vÄrtraÌghna ÄÌ vÄsyaÌ  sa tasmÄÌ-dvÄÌ ÅyaÌá¹ vÄruÌ á¹yarchÄ pariÌ charatiÌ  svayaiÌ vainaÌ-ndÄÌ vataÌyÄÌ  pariÌ charati à¥¥ 76 à¥¥<br/>
<b>(aÌ nvÄÌ rabhyÅth - sarvÄÌbhirÄÌ va - sÅ«ryaÌá¹ - bhÅ«Ì tÄnÄÌ gÌ  hyÄÌ - tiÌ  ya - dÄÌhuá¸¥ - saÌ ptavigá¹ÌÅatiÅcha) (a. 11)</b></p>
<p><i>(prÄÌ chÄ«naÌvagá¹ÅaÌ á¹ -à¤yÄvaÌnta - á¹khsÄÌ mÄ - vÄgvai dÄÌ vÄbhyÅÌ - dÄÌ vÄ vai dÄÌvaÌ yajaÌnaá¹ - kaÌ drÅ«ÅchaÌ  - taddhiraÌá¹yaÌ gá¹Ì  - á¹£aá¹­ paÌ dÄniÌ - brahmavÄÌ dinÅÌ viÌ chityÅÌ  - ya-tkaÌ layÄÌ tÄ - vÄruÌ á¹Å vai krÄ«Ì ta-ssÅmaÌ  - ÄkÄÌdaÅa)</i></p>
<p><i>(prÄÌ chÄ«naÌvagá¹ÅaÌ ggÌ  - svÄhÄtyÄÌhaÌ  - yÄÌ-'nta-ÅÅaÌ rÄ - hyÄÌá¹£a saá¹ - tapaÌsÄ chaÌ  - yatkaÌrá¹agá¹hÄ«Ì  - tÄtiÌ lÅmaÌ tÅ - vÄÌruÌ á¹aá¸¥ - á¹£aá¹­-thsaÌptatiá¸¥ )</i></p>
<p><b>(prÄÌ chÄ«naÌvagá¹ ÅaÌ , mpariÌ charati)</b></p>
<p>à¥¥ hariÌá¸¥ Åm à¥¥</p>
<p>à¥¥ ká¹á¹£á¹a yajurvÄdÄ«ya taittirÄ«ya saá¹hitÄyÄá¹ á¹£aá¹£á¹­hakÄá¹á¸Ä prathamaá¸¥ praÅna-ssamÄptaá¸¥ à¥¥<br/>
</p></span> <br/><br/><br/>
<p class="relatedCategories">Browse Related Categories:</p>
<ul class="aqtree3clickable">
<li><img height="30" src="../images/cats/tags/001.jpg" width="30"/><a class="link1" href="https://vignanam.org">Krishna Yajurveda Taittiriya Samhita (88)</a>
<ul>
<li><a class="link4" href="kyts-1.1-ishe-tvorje-tva-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.1 Ishe Tvorje Tva - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.2-apa-undantu-jivase-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.2 Apa Undantu Jivase - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.3-devasya-tva-savitu-prasave-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.3 Devasya Tva Savitu Prasave - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.4-a-dade-graavaa-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.4 A Dade Graavaa - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.5-devasurah-samyatta-aasann-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.5 Devasurah Samyatta Aasann - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.6-santva-sinchami-yajusha-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.6 Santva Sinchami Yajusha - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.7-pakayagnam-va-anvahitagne-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.7 Pakayagnam Va Anvahitagne - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.8-anumatyai-purodaasamashtakapalam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.8 Anumatyai Purodaasamashtakapalam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.1-vayavyagg-sveta-maa-labheta-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.1 Vayavyagg Sveta Maa Labheta - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.3-adityebhyo-bhuvadvadbhyascharum-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.3 Adityebhyo BhuvadvadbhyaScharum - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.4-deva-manushyah-pitarah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.4 Deva Manushyah Pitarah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.5-visvaroopo-vai-tvaashtrah-krishna-taittiriya-yajurveda-samhita-patha.html">KYTS 2.5 Visvaroopo Vai Tvaashtrah - Krishna Taittiriya Yajurveda Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.6-samidho-yajati-vasantam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.6 Samidho Yajati Vasantam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.1-prajapatirakaamayata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.1 Prajapatirakaamayata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.2-yo-vai-pavamanaanaam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.2 Yo Vai Pavamanaanaam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.3-agne-tejasvintejasvee-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.3 Agne Tejasvintejasvee - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.4-vi-vaa-etasya-yagnah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.4 Vi Vaa Etasya Yagnah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.5-purna-paschaaduta-purna-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.5 Purna Paschaaduta Purna - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.1-yunjanah-prathamam-manah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.1 Yunjanah Prathamam Manah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.2-vishnoh-kramosyabhimaatihaa-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.2 Vishnoh Kramosyabhimaatihaa - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.3-apaan-tvemanthsaadayaami-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.3 Apaan Tvemanthsaadayaami - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.4-rasmirasi-kshayaaya-tvaa-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.4 Rasmirasi Kshayaaya Tvaa - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.5-namaste-rudra-manyava-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.5 Namaste Rudra Manyava - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.6-asmannoorjam-parvate-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.6 Asmannoorjam Parvate - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.7-agnavishnoo-sajoshasemaa-vardhantu-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.7 Agnavishnoo Sajoshasemaa Vardhantu - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.1-savitraani-juhoti-prasootyai-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.1 Savitraani Juhoti Prasootyai - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.2-vishnumukhaa-vai-devaah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.2 Vishnumukhaa Vai Devaah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.3-uthsannayagno-vaa-esha-yadagnih-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.3 Uthsannayagno Vaa Esha Yadagnih - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.4-devasuraa-samyattaa-aasann-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.4 Devasuraa Samyattaa Aasann - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.5-yadekena-saggsthaapayati-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.5 Yadekena Saggsthaapayati - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.6-hirnyavarnaah-suchayah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.6 Hirnyavarnaah Suchayah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.7-yo-vaa-ayathaa-devatam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.7 Yo Vaa Ayathaa Devatam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.2-yadubhau-vimuchyaatithyam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.2 Yadubhau Vimuchyaatithyam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.3-chaatvaalaad-dhishniyaanupavapati-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.3 Chaatvaalaad Dhishniyaanupavapati - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.4-yagnena-vai-prajaapatih-prajaa-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.4 Yagnena Vai Prajaapatih Prajaa Asrujata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.5-indro-vrutraaya-vajramudayacchat-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.5 Indro Vrutraaya Vajramudayacchat - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.6-suvargaaya-vaa-etaani-lokaaya-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.6 Suvargaaya Vaa Etaani Lokaaya - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.1-prajananam-jyothiragnih-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.1 Prajananam Jyothiragnih - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.2-saadhyaa-vai-devaah-suvargakaamaah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.2 Saadhyaa Vai Devaah Suvargakaamaah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.3-prajavam-vaa-etena-yanti-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.3 Prajavam Vaa Etena Yanti - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.4-bruhaspati-rakaamayata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.4 Bruhaspati Rakaamayata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.5-gaavo-vaa-etathsatramaasata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.5 Gaavo Vaa Etathsatramaasata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-jata-1.1-ishe-tvorje-tva-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.1 Ishe Tvorje Tva - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.2-apa-undantu-jivase-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.2 Apa Undantu Jivase - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.3-devasya-tva-savitu-prasave-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.3 Devasya Tva Savitu Prasave - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.4-a-dade-graavaa-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.4 A Dade Graavaa - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.5-devasurah-samyatta-aasann-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.5 Devasurah Samyatta Aasann - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.6-santva-sinchami-yajusha-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.6 Santva Sinchami Yajusha - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.7-pakayagnam-va-anvahitagne-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.7 Pakayagnam Va Anvahitagne - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kys-jata-1.8-anumatyai-purodaasamashtakapalam-krishna-yajurveda-taittiriya-samhita.html">KYS Jata 1.8 Anumatyai Purodaasamashtakapalam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.1-vayavyagg-sveta-maa-labheta-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.1 Vayavyagg Sveta Maa Labheta - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.3-adityebhyo-bhuvadvadbhyascharum-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.3 Adityebhyo BhuvadvadbhyaScharum - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.4-deva-manushyah-pitarah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.4 Deva Manushyah Pitarah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.5-visvaroopo-vai-tvaashtrah-krishna-taittiriya-yajurveda-samhita.html">KYTS Jata 2.5 Visvaroopo Vai Tvaashtrah - Krishna Taittiriya Yajurveda Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.6-samidho-yajati-vasantam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.6 Samidho Yajati Vasantam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.1-prajapatirakaamayata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.1 Prajapatirakaamayata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.2-yo-vai-pavamanaanaam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.2 Yo Vai Pavamanaanaam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.3-agne-tejasvintejasvee-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.3 Agne Tejasvintejasvee - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.4-vi-vaa-etasya-yagnah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.4 Vi Vaa Etasya Yagnah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.5-purna-paschaaduta-purna-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.5 Purna Paschaaduta Purna - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.1-yunjanah-prathamam-manah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.1 Yunjanah Prathamam Manah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.2-vishnoh-kramosyabhimaatihaa-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.2 Vishnoh Kramosyabhimaatihaa - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.3-apaan-tvemanthsaadayaami-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.3 Apaan Tvemanthsaadayaami - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.4-rasmirasi-kshayaaya-tvaa-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.4 Rasmirasi Kshayaaya Tvaa - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.5-namaste-rudra-manyava-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.5 Namaste Rudra Manyava - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.6-asmannoorjam-parvate-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.6 Asmannoorjam Parvate - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.7-agnavishnoo-sajoshasemaa-vardhantu-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.7 Agnavishnoo Sajoshasemaa Vardhantu - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.1-savitraani-juhoti-prasootyai-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.1 Savitraani Juhoti Prasootyai - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.2-vishnumukhaa-vai-devaah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.2 Vishnumukhaa Vai Devaah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.3-uthsannayagno-vaa-esha-yadagnih-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.3 Uthsannayagno Vaa Esha Yadagnih - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.4-devasuraa-samyattaa-aasann-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.4 Devasuraa Samyattaa Aasann - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.5-yadekena-saggsthaapayati-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.5 Yadekena Saggsthaapayati - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.6-hirnyavarnaah-suchayah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.6 Hirnyavarnaah Suchayah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.7-yo-vaa-ayathaa-devatam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.7 Yo Vaa Ayathaa Devatam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.2-yadubhau-vimuchyaatithyam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.2 Yadubhau Vimuchyaatithyam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.3-chaatvaalaad-dhishniyaanupavapati-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.3 Chaatvaalaad Dhishniyaanupavapati - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.4-yagnena-vai-prajaapatih-prajaa-asrujata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.4 Yagnena Vai Prajaapatih Prajaa Asrujata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.5-indro-vrutraaya-vajramudayacchat-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.5 Indro Vrutraaya Vajramudayacchat - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.6-suvargaaya-vaa-etaani-lokaaya-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.6 Suvargaaya Vaa Etaani Lokaaya - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.1-prajananam-jyothiragnih-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.1 Prajananam Jyothiragnih - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.2-saadhyaa-vai-devaah-suvargakaamaah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.2 Saadhyaa Vai Devaah Suvargakaamaah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.3-prajavam-vaa-etena-yanti-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.3 Prajavam Vaa Etena Yanti - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.4-bruhaspati-rakaamayata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.4 Bruhaspati Rakaamayata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.5-gaavo-vaa-etathsatramaasata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.5 Gaavo Vaa Etathsatramaasata - Krishna Yajurveda Taittiriya Samhita</a></li>
</ul>
</li>
<li><img height="30" src="../images/cats/tags/001.jpg" width="30"/><a class="link1" href="https://vignanam.org">Kanda 6 - Krishna Yajurveda Taittiriya Samhita (12)</a>
<ul>
<li><a class="link4" href="kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.2-yadubhau-vimuchyaatithyam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.2 Yadubhau Vimuchyaatithyam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.3-chaatvaalaad-dhishniyaanupavapati-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.3 Chaatvaalaad Dhishniyaanupavapati - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.4-yagnena-vai-prajaapatih-prajaa-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.4 Yagnena Vai Prajaapatih Prajaa Asrujata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.5-indro-vrutraaya-vajramudayacchat-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.5 Indro Vrutraaya Vajramudayacchat - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.6-suvargaaya-vaa-etaani-lokaaya-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.6 Suvargaaya Vaa Etaani Lokaaya - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-jata-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.2-yadubhau-vimuchyaatithyam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.2 Yadubhau Vimuchyaatithyam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.3-chaatvaalaad-dhishniyaanupavapati-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.3 Chaatvaalaad Dhishniyaanupavapati - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.4-yagnena-vai-prajaapatih-prajaa-asrujata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.4 Yagnena Vai Prajaapatih Prajaa Asrujata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.5-indro-vrutraaya-vajramudayacchat-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.5 Indro Vrutraaya Vajramudayacchat - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.6-suvargaaya-vaa-etaani-lokaaya-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.6 Suvargaaya Vaa Etaani Lokaaya - Krishna Yajurveda Taittiriya Samhita</a></li>
</ul>
</li>
<li><img height="30" src="../images/cats/festivals/047.jpg" width="30"/><a class="link1" href="https://vignanam.org">Upakarma (114)</a>
<ul>
<li><a class="link4" href="gayatri-mantram-ghanapatham.html">Gayatri Mantram Ghanapatham</a></li>
<li><a class="link4" href="nitya-sandhya-vandanam-krishna-yajurvediya.html">Nitya Sandhya Vandanam (Krishna Yajurvediya)</a></li>
<li><a class="link4" href="gayatri-ashtottara-sata-namavali.html">Gayatri Ashtottara Sata Namavali</a></li>
<li><a class="link4" href="gayatri-kavacham.html">Gayatri Kavacham</a></li>
<li><a class="link4" href="sri-gayatri-sahasra-nama-stotram.html">Sri Gayatri Sahasra Nama Stotram</a></li>
<li><a class="link4" href="yagnopavita-dharana.html">Yagnopavita Dharana</a></li>
<li><a class="link4" href="sarva-devata-gayatri-mantras.html">Sarva Devata Gayatri Mantras</a></li>
<li><a class="link4" href="gayatri-ashtottara-sata-nama-stotram.html">Gayatri Ashtottara Sata Nama Stotram</a></li>
<li><a class="link4" href="kyts-1.1-ishe-tvorje-tva-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.1 Ishe Tvorje Tva - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.2-apa-undantu-jivase-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.2 Apa Undantu Jivase - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.3-devasya-tva-savitu-prasave-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.3 Devasya Tva Savitu Prasave - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.4-a-dade-graavaa-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.4 A Dade Graavaa - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.5-devasurah-samyatta-aasann-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.5 Devasurah Samyatta Aasann - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.6-santva-sinchami-yajusha-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.6 Santva Sinchami Yajusha - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.7-pakayagnam-va-anvahitagne-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.7 Pakayagnam Va Anvahitagne - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-1.8-anumatyai-purodaasamashtakapalam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 1.8 Anumatyai Purodaasamashtakapalam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.1-vayavyagg-sveta-maa-labheta-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.1 Vayavyagg Sveta Maa Labheta - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.3-adityebhyo-bhuvadvadbhyascharum-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.3 Adityebhyo BhuvadvadbhyaScharum - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.4-deva-manushyah-pitarah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.4 Deva Manushyah Pitarah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.5-visvaroopo-vai-tvaashtrah-krishna-taittiriya-yajurveda-samhita-patha.html">KYTS 2.5 Visvaroopo Vai Tvaashtrah - Krishna Taittiriya Yajurveda Samhita Patha</a></li>
<li><a class="link4" href="kyts-2.6-samidho-yajati-vasantam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 2.6 Samidho Yajati Vasantam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.1-prajapatirakaamayata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.1 Prajapatirakaamayata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.2-yo-vai-pavamanaanaam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.2 Yo Vai Pavamanaanaam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.3-agne-tejasvintejasvee-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.3 Agne Tejasvintejasvee - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.4-vi-vaa-etasya-yagnah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.4 Vi Vaa Etasya Yagnah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-3.5-purna-paschaaduta-purna-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 3.5 Purna Paschaaduta Purna - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.1-yunjanah-prathamam-manah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.1 Yunjanah Prathamam Manah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.2-vishnoh-kramosyabhimaatihaa-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.2 Vishnoh Kramosyabhimaatihaa - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.3-apaan-tvemanthsaadayaami-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.3 Apaan Tvemanthsaadayaami - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.4-rasmirasi-kshayaaya-tvaa-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.4 Rasmirasi Kshayaaya Tvaa - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.5-namaste-rudra-manyava-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.5 Namaste Rudra Manyava - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.6-asmannoorjam-parvate-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.6 Asmannoorjam Parvate - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-4.7-agnavishnoo-sajoshasemaa-vardhantu-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 4.7 Agnavishnoo Sajoshasemaa Vardhantu - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.1-savitraani-juhoti-prasootyai-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.1 Savitraani Juhoti Prasootyai - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.2-vishnumukhaa-vai-devaah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.2 Vishnumukhaa Vai Devaah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.3-uthsannayagno-vaa-esha-yadagnih-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.3 Uthsannayagno Vaa Esha Yadagnih - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.4-devasuraa-samyattaa-aasann-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.4 Devasuraa Samyattaa Aasann - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.5-yadekena-saggsthaapayati-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.5 Yadekena Saggsthaapayati - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.6-hirnyavarnaah-suchayah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.6 Hirnyavarnaah Suchayah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-5.7-yo-vaa-ayathaa-devatam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 5.7 Yo Vaa Ayathaa Devatam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.2-yadubhau-vimuchyaatithyam-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.2 Yadubhau Vimuchyaatithyam - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.3-chaatvaalaad-dhishniyaanupavapati-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.3 Chaatvaalaad Dhishniyaanupavapati - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.4-yagnena-vai-prajaapatih-prajaa-asrujata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.4 Yagnena Vai Prajaapatih Prajaa Asrujata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.5-indro-vrutraaya-vajramudayacchat-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.5 Indro Vrutraaya Vajramudayacchat - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-6.6-suvargaaya-vaa-etaani-lokaaya-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 6.6 Suvargaaya Vaa Etaani Lokaaya - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.1-prajananam-jyothiragnih-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.1 Prajananam Jyothiragnih - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.2-saadhyaa-vai-devaah-suvargakaamaah-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.2 Saadhyaa Vai Devaah Suvargakaamaah - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.3-prajavam-vaa-etena-yanti-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.3 Prajavam Vaa Etena Yanti - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.4-bruhaspati-rakaamayata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.4 Bruhaspati Rakaamayata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="kyts-7.5-gaavo-vaa-etathsatramaasata-krishna-yajurveda-taittiriya-samhita-patha.html">KYTS 7.5 Gaavo Vaa Etathsatramaasata - Krishna Yajurveda Taittiriya Samhita Patha</a></li>
<li><a class="link4" href="saraswati-suktam.html">Saraswati Suktam</a></li>
<li><a class="link4" href="bhagya-suktam.html">Bhagya Suktam</a></li>
<li><a class="link4" href="pavamana-suktam.html">Pavamana Suktam</a></li>
<li><a class="link4" href="nasadiya-suktam.html">Nasadiya Suktam</a></li>
<li><a class="link4" href="navagraha-suktam.html">Navagraha Suktam</a></li>
<li><a class="link4" href="pitru-suktam.html">Pitru Suktam</a></li>
<li><a class="link4" href="ratri-suktam.html">Ratri Suktam</a></li>
<li><a class="link4" href="sarpa-suktam.html">Sarpa Suktam</a></li>
<li><a class="link4" href="hiranya-garbha-suktam.html">Hiranya Garbha Suktam</a></li>
<li><a class="link4" href="sanusvara-prasna-sunnala-pannam.html">Sanusvara Prasna (Sunnala Pannam)</a></li>
<li><a class="link4" href="go-suktam.html">Go Suktam</a></li>
<li><a class="link4" href="trisuparnam.html">Trisuparnam</a></li>
<li><a class="link4" href="chitti-pannam.html">Chitti Pannam</a></li>
<li><a class="link4" href="aghamarshana-suktam.html">Aghamarshana Suktam</a></li>
<li><a class="link4" href="ayushya-suktam.html">Ayushya Suktam</a></li>
<li><a class="link4" href="shraddha-suktam.html">Shraddha Suktam</a></li>
<li><a class="link4" href="kyts-jata-1.1-ishe-tvorje-tva-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.1 Ishe Tvorje Tva - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.2-apa-undantu-jivase-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.2 Apa Undantu Jivase - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.3-devasya-tva-savitu-prasave-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.3 Devasya Tva Savitu Prasave - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.4-a-dade-graavaa-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.4 A Dade Graavaa - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.5-devasurah-samyatta-aasann-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.5 Devasurah Samyatta Aasann - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.6-santva-sinchami-yajusha-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.6 Santva Sinchami Yajusha - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-1.7-pakayagnam-va-anvahitagne-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 1.7 Pakayagnam Va Anvahitagne - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kys-jata-1.8-anumatyai-purodaasamashtakapalam-krishna-yajurveda-taittiriya-samhita.html">KYS Jata 1.8 Anumatyai Purodaasamashtakapalam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.1-vayavyagg-sveta-maa-labheta-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.1 Vayavyagg Sveta Maa Labheta - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.2-prajapatih-praja-asrujata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.2 Prajapatih Praja Asrujata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.3-adityebhyo-bhuvadvadbhyascharum-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.3 Adityebhyo BhuvadvadbhyaScharum - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.4-deva-manushyah-pitarah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.4 Deva Manushyah Pitarah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.5-visvaroopo-vai-tvaashtrah-krishna-taittiriya-yajurveda-samhita.html">KYTS Jata 2.5 Visvaroopo Vai Tvaashtrah - Krishna Taittiriya Yajurveda Samhita</a></li>
<li><a class="link4" href="kyts-jata-2.6-samidho-yajati-vasantam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 2.6 Samidho Yajati Vasantam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.1-prajapatirakaamayata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.1 Prajapatirakaamayata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.2-yo-vai-pavamanaanaam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.2 Yo Vai Pavamanaanaam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.3-agne-tejasvintejasvee-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.3 Agne Tejasvintejasvee - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.4-vi-vaa-etasya-yagnah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.4 Vi Vaa Etasya Yagnah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-3.5-purna-paschaaduta-purna-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 3.5 Purna Paschaaduta Purna - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.1-yunjanah-prathamam-manah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.1 Yunjanah Prathamam Manah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.2-vishnoh-kramosyabhimaatihaa-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.2 Vishnoh Kramosyabhimaatihaa - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.3-apaan-tvemanthsaadayaami-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.3 Apaan Tvemanthsaadayaami - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.4-rasmirasi-kshayaaya-tvaa-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.4 Rasmirasi Kshayaaya Tvaa - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.5-namaste-rudra-manyava-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.5 Namaste Rudra Manyava - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.6-asmannoorjam-parvate-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.6 Asmannoorjam Parvate - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-4.7-agnavishnoo-sajoshasemaa-vardhantu-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 4.7 Agnavishnoo Sajoshasemaa Vardhantu - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.1-savitraani-juhoti-prasootyai-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.1 Savitraani Juhoti Prasootyai - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.2-vishnumukhaa-vai-devaah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.2 Vishnumukhaa Vai Devaah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.3-uthsannayagno-vaa-esha-yadagnih-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.3 Uthsannayagno Vaa Esha Yadagnih - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.4-devasuraa-samyattaa-aasann-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.4 Devasuraa Samyattaa Aasann - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.5-yadekena-saggsthaapayati-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.5 Yadekena Saggsthaapayati - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.6-hirnyavarnaah-suchayah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.6 Hirnyavarnaah Suchayah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-5.7-yo-vaa-ayathaa-devatam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 5.7 Yo Vaa Ayathaa Devatam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.1-praacheenavagm-sankaroti-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.1 Praacheenavagm Sankaroti - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.2-yadubhau-vimuchyaatithyam-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.2 Yadubhau Vimuchyaatithyam - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.3-chaatvaalaad-dhishniyaanupavapati-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.3 Chaatvaalaad Dhishniyaanupavapati - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.4-yagnena-vai-prajaapatih-prajaa-asrujata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.4 Yagnena Vai Prajaapatih Prajaa Asrujata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.5-indro-vrutraaya-vajramudayacchat-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.5 Indro Vrutraaya Vajramudayacchat - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-6.6-suvargaaya-vaa-etaani-lokaaya-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 6.6 Suvargaaya Vaa Etaani Lokaaya - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.1-prajananam-jyothiragnih-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.1 Prajananam Jyothiragnih - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.2-saadhyaa-vai-devaah-suvargakaamaah-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.2 Saadhyaa Vai Devaah Suvargakaamaah - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.3-prajavam-vaa-etena-yanti-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.3 Prajavam Vaa Etena Yanti - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.4-bruhaspati-rakaamayata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.4 Bruhaspati Rakaamayata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="kyts-jata-7.5-gaavo-vaa-etathsatramaasata-krishna-yajurveda-taittiriya-samhita.html">KYTS Jata 7.5 Gaavo Vaa Etathsatramaasata - Krishna Yajurveda Taittiriya Samhita</a></li>
<li><a class="link4" href="shukla-yajurveda-sandhya-vandanam.html">Shukla Yajurveda Sandhya Vandanam</a></li>
<li><a class="link4" href="rigveda-sandhya-vandanam.html">Rigveda Sandhya Vandanam</a></li>
</ul>
</li>
</ul>

</span>
</div>
<!-- <br /><br /><br /><br /> -->
<!-- <br /><br /><br /><br /><br /><br />	-->
</div>
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td>
<div class="footer-space"> </div>
</td>
</tr>
</tfoot>
</table>
</div>
<footer class="deepLinkFooter">
<a class="deepLinkRef" href="https://vignanam.page.link/87a9">Open In Vignanam Mobile App</a>
</footer>

    </article>
    
    <!-- Ad Promotion Template: For my Website -->
    <div class="promo mt-5 mb-5">
        <?php include "../includes/promo1-devotional.php"; ?>
    </div>
</div>
</section>
</main>

<?php include "../includes/footer.php"; ?>
