<?php
// Meta Tags
$meta_title = "Others Stotras in English - ClickVedicAstro";
$meta_description = "Collection of Others devotional stotras and slokas in English with meaning and lyrics.";
$meta_keywords = "Others Stotras, English Stotras, Others Slokas, Hindu Devotional Hymns"; 
$meta_url = "https://www.clickvedicastro.com/en/others-stotras.php";

// Include Header
include "../includes/header.php";
?>

<main id="content" role="main" class="main-content pt-0 pb-0">
<!-- breadcrumb -->
<div class="page-breadcrumb bg-white py-0">
    <div class="container">
        <div class="my-3">
            <ul class="list">
                <li><a href="<?php echo $base_url; ?>/index.php">Home</a></li>
                <li><a href="<?php echo $base_url; ?>/en/" title="Stotras in English">Stotras in English</a></li>
                <li>Others Stotras</li>
            </ul>
        </div>
    </div>
</div>

    <!-- Ad Promotion Template: For my Website -->
    <div class="mt-5 mb-5">
    <?php include "../includes/ad-promotion1.php"; ?>
    </div>

<section class="devotional-content pt-5">
<div class="container">
    <h1 class="category-title">Others Stotras in English</h1>
    <p>Collection of Others devotional stotras and slokas in English with meaning and lyrics.</p>

    <ul class="stotra-list">
  <li><a href="aadya-kalika-ashtottara-sata-namavali-english">Aadya Kalika Ashtottara Sata Namavali</a></li>
  <li><a href="achyutashtakam-english">Achyutashtakam</a></li>
  <li><a href="adigo-bhadradri-english">Adigo Bhadradri</a></li>
  <li><a href="amba-pancharatnam-english">Amba Pancharatnam</a></li>
  <li><a href="amba-stavam-english">Amba Stavam</a></li>
  <li><a href="ananda-lahari-english">Ananda Lahari</a></li>
  <li><a href="anantha-padmanabha-swamy-ashtottara-sata-namavali-english">Anantha Padmanabha Swamy Ashtottara Sata Namavali</a></li>
  <li><a href="angaraka-ashtottara-sata-namavali-english">Angaraka Ashtottara Sata Namavali</a></li>
  <li><a href="angaraka-ashtottara-sata-nama-stotram-english">Angaraka Ashtottara Sata Nama Stotram</a></li>
  <li><a href="angaraka-kavacham-angaraka-kavacham-english">Angaraka Kavacham (Angaraka Kavacham)</a></li>
  <li><a href="aparadha-kshamapana-stotram-devi-english">Aparadha Kshamapana Stotram (Devi)</a></li>
  <li><a href="ardha-naareeswara-ashtakam-english">Ardha Naareeswara Ashtakam</a></li>
  <li><a href="ardha-nareeswara-stotram-english">Ardha Nareeswara Stotram</a></li>
  <li><a href="arunachala-akshara-mani-mala-stotram-english">Arunachala Akshara Mani Mala Stotram</a></li>
  <li><a href="arunachala-ashtakam-english">Arunachala Ashtakam</a></li>
  <li><a href="aruna-prasna-english">Aruna Prasna</a></li>
  <li><a href="ashtaadasa-shaktipeetha-stotram-english">Ashtaadasa Shaktipeetha Stotram</a></li>
  <li><a href="avanitalam-punaravatirna-syat-english">Avanitalam Punaravatirna Syat</a></li>
  <li><a href="bala-mukundashtakam-english">Bala Mukundashtakam</a></li>
  <li><a href="bhaja-govindam-moha-mudagaram-english">Bhaja Govindam (Moha Mudagaram)</a></li>
  <li><a href="bhavani-ashtakam-english">Bhavani Ashtakam</a></li>
  <li><a href="bhavani-bhujanga-prayata-stotram-english">Bhavani Bhujanga Prayata Stotram</a></li>
  <li><a href="bhramarambika-ashtakam-english">Bhramarambika Ashtakam</a></li>
  <li><a href="bilvaashtakam-english">Bilvaashtakam</a></li>
  <li><a href="brahma-gnanavali-mala-english">Brahma Gnanavali Mala</a></li>
  <li><a href="brahma-samhita-english">Brahma Samhita</a></li>
  <li><a href="bruhaspati-ashtottara-sata-namavali-english">Bruhaspati Ashtottara Sata Namavali</a></li>
  <li><a href="bruhaspati-ashtottara-sata-nama-stotram-english">Bruhaspati Ashtottara Sata Nama Stotram</a></li>
  <li><a href="bruhaspati-kavacham-guru-kavacham-english">Bruhaspati Kavacham (Guru Kavacham)</a></li>
  <li><a href="budha-ashtottara-sata-namavali-english">Budha Ashtottara Sata Namavali</a></li>
  <li><a href="budha-ashtottara-sata-nama-stotram-english">Budha Ashtottara Sata Nama Stotram</a></li>
  <li><a href="budha-kavacham-english">Budha Kavacham</a></li>
  <li><a href="chakshushopanishad-chakshushmati-vidya-english">Chakshushopanishad (Chakshushmati Vidya)</a></li>
  <li><a href="chandrasekhara-ashtakam-english">Chandrasekhara Ashtakam</a></li>
  <li><a href="chandra-ashtottara-sata-namavali-english">Chandra Ashtottara Sata Namavali</a></li>
  <li><a href="chandra-ashtottara-sata-nama-stotram-english">Chandra Ashtottara Sata Nama Stotram</a></li>
  <li><a href="chandra-kavacham-english">Chandra Kavacham</a></li>
  <li><a href="charcha-stavam-english">Charcha Stavam</a></li>
  <li><a href="chaurashtakam-sri-chauragraganya-purushashtakam-english">Chaurashtakam (Sri Chauragraganya Purushashtakam)</a></li>
  <li><a href="chintamani-shatpadi-english">Chintamani Shatpadi</a></li>
  <li><a href="chitti-pannam-english">Chitti Pannam</a></li>
  <li><a href="dakshina-murthy-stotram-english">Dakshina Murthy Stotram</a></li>
  <li><a href="damodara-ashtakam-english">Damodara Ashtakam</a></li>
  <li><a href="daridrya-dahana-ganapati-stotram-english">Daridrya Dahana Ganapati Stotram</a></li>
  <li><a href="dasarathi-satakam-english">Dasarathi Satakam</a></li>
  <li><a href="dashavatara-stotram-vedantacharya-krutam-english">Dashavatara Stotram (Vedantacharya Krutam)</a></li>
  <li><a href="dashavatara-stuti-english">Dashavatara Stuti</a></li>
  <li><a href="datta-shodasi-english">Datta Shodasi</a></li>
  <li><a href="desamunu-preminchumanna-english">Desamunu Preminchumanna</a></li>
  <li><a href="devavanim-vedavanim-mataram-vandamahe-english">Devavanim Vedavanim Mataram Vandamahe</a></li>
  <li><a href="devi-aparadha-kshamapana-stotram-english">Devi Aparadha Kshamapana Stotram</a></li>
  <li><a href="devi-aparajita-stotram-english">Devi Aparajita Stotram</a></li>
  <li><a href="devi-aswadhati-amba-stuti-english">Devi Aswadhati (Amba Stuti)</a></li>
  <li><a href="devi-bhujanga-stotram-english">Devi Bhujanga Stotram</a></li>
  <li><a href="devi-mahatmyam-aparaadha-kshamapana-stotram-english">Devi Mahatmyam Aparaadha Kshamapana Stotram</a></li>
  <li><a href="devi-mahatmyam-argala-stotram-english">Devi Mahatmyam Argala Stotram</a></li>
  <li><a href="devi-mahatmyam-chamundeswari-mangalam-english">Devi Mahatmyam Chamundeswari Mangalam</a></li>
  <li><a href="devi-mahatmyam-devi-kavacham-english">Devi Mahatmyam Devi Kavacham</a></li>
  <li><a href="devi-mahatmyam-keelaka-stotram-english">Devi Mahatmyam Keelaka Stotram</a></li>
  <li><a href="devi-mahatmyam-mangala-neerajanam-english">Devi Mahatmyam Mangala Neerajanam</a></li>
  <li><a href="devi-mahatmyam-navaavarna-vidhi-english">Devi Mahatmyam Navaavarna Vidhi</a></li>
  <li><a href="devi-vaibhava-ashcharya-ashtottara-sata-namaavali-english">Devi Vaibhava Ashcharya Ashtottara Sata Namaavali</a></li>
  <li><a href="devi-vaibhava-ashcharya-ashtottara-sata-nama-stotram-english">Devi Vaibhava Ashcharya Ashtottara Sata Nama Stotram</a></li>
  <li><a href="dhanvantari-mantra-english">Dhanvantari Mantra</a></li>
  <li><a href="dhanyashtakam-english">Dhanyashtakam</a></li>
  <li><a href="dhundhiraja-bhujanga-prayata-stotram-english">Dhundhiraja Bhujanga Prayata Stotram</a></li>
  <li><a href="dhyeya-pathika-sadhaka-english">Dhyeya Pathika Sadhaka</a></li>
  <li><a href="dvadasha-jyothirlinga-stotram-english">Dvadasha Jyothirlinga Stotram</a></li>
  <li><a href="dwadasa-arya-stuti-english">Dwadasa Arya Stuti</a></li>
  <li><a href="dwadasa-jyotirlinga-stotram-english">Dwadasa Jyotirlinga Stotram</a></li>
  <li><a href="eesavasyopanishad-ishopanishad-english">Eesavasyopanishad (Ishopanishad)</a></li>
  <li><a href="evarani-nirnayinchirira-english">Evarani Nirnayinchirira</a></li>
  <li><a href="e-desamegina-english">E Desamegina</a></li>
  <li><a href="ganamurte-sri-krushnavenu-english">Ganamurte Sri Krushnavenu</a></li>
  <li><a href="ganapati-atharva-sheersham-english">Ganapati Atharva Sheersham</a></li>
  <li><a href="ganapati-gakara-ashtottara-satanama-stotram-english">Ganapati Gakara Ashtottara Satanama Stotram</a></li>
  <li><a href="ganapati-gakara-ashtottara-sata-namavali-english">Ganapati Gakara Ashtottara Sata Namavali</a></li>
  <li><a href="ganapati-prarthana-ghanapatham-english">Ganapati Prarthana Ghanapatham</a></li>
  <li><a href="ganga-ashtakam-english">Ganga Ashtakam</a></li>
  <li><a href="ganga-stotram-english">Ganga Stotram</a></li>
  <li><a href="gauri-dasakam-english">Gauri Dasakam</a></li>
  <li><a href="ghantasala-bhagavad-gita-english">Ghantasala Bhagavad Gita</a></li>
  <li><a href="ghata-stavam-english">Ghata Stavam</a></li>
  <li><a href="goda-devi-ashtottara-sata-namavali-english">Goda Devi Ashtottara Sata Namavali</a></li>
  <li><a href="goda-devi-ashtottara-sata-nama-stotram-english">Goda Devi Ashtottara Sata Nama Stotram</a></li>
  <li><a href="gokula-ashtakam-english">Gokula Ashtakam</a></li>
  <li><a href="gopala-ashtottara-sata-namavali-english">Gopala Ashtottara Sata Namavali</a></li>
  <li><a href="gopika-geetha-bhagavatha-purana-english">Gopika Geetha (Bhagavatha Purana)</a></li>
  <li><a href="govindashtakam-english">Govindashtakam</a></li>
  <li><a href="govinda-damodara-stotram-english">Govinda Damodara Stotram</a></li>
  <li><a href="govinda-damodara-stotram-selected-verses-english">Govinda Damodara Stotram (Selected Verses)</a></li>
  <li><a href="govinda-namaavali-english">Govinda Namaavali</a></li>
  <li><a href="guru-paduka-stotram-english">Guru Paduka Stotram</a></li>
  <li><a href="gurvashtakam-english">Gurvashtakam</a></li>
  <li><a href="harivarasanam-hariharatmaja-ashtakam-english">Harivarasanam (Hariharatmaja Ashtakam)</a></li>
  <li><a href="indrakshi-stotram-english">Indrakshi Stotram</a></li>
  <li><a href="jagannatha-ashtakam-english">Jagannatha Ashtakam</a></li>
  <li><a href="jana-gana-mana-english">Jana Gana Mana</a></li>
  <li><a href="janmadinamidam-happy-birthday-in-samskritam-english">Janmadinamidam (Happy Birthday in Samskritam)</a></li>
  <li><a href="jatiki-oopiri-swatantryam-english">Jatiki Oopiri Swatantryam</a></li>
  <li><a href="jaya-jaya-jaya-priya-bharata-english">Jaya Jaya Jaya Priya Bharata</a></li>
  <li><a href="kalabhairava-ashtakam-english">Kalabhairava Ashtakam</a></li>
  <li><a href="kalyana-vrishti-stavam-english">Kalyana Vrishti Stavam</a></li>
  <li><a href="kamasika-ashtakam-english">Kamasika Ashtakam</a></li>
  <li><a href="kanakadhara-stotram-english">Kanakadhara Stotram</a></li>
  <li><a href="kanda-shashti-kavacham-tamil-english">Kanda Shashti Kavacham (Tamil)</a></li>
  <li><a href="kashi-panchakam-english">Kashi Panchakam</a></li>
  <li><a href="kasi-vishwanathashtakam-english">Kasi Vishwanathashtakam</a></li>
  <li><a href="katyayani-mantra-english">Katyayani Mantra</a></li>
  <li><a href="kena-upanishad-part-1-english">Kena Upanishad - Part 1</a></li>
  <li><a href="kena-upanishad-part-2-english">Kena Upanishad - Part 2</a></li>
  <li><a href="kena-upanishad-part-3-english">Kena Upanishad - Part 3</a></li>
  <li><a href="kena-upanishad-part-4-english">Kena Upanishad - Part 4</a></li>
  <li><a href="ketu-ashtottara-sata-namavali-english">Ketu Ashtottara Sata Namavali</a></li>
  <li><a href="ketu-ashtottara-sata-nama-stotram-english">Ketu Ashtottara Sata Nama Stotram</a></li>
  <li><a href="ketu-kavacham-english">Ketu Kavacham</a></li>
  <li><a href="kritva-nava-dhrudha-sankalpam-english">Kritva Nava Dhrudha Sankalpam</a></li>
  <li><a href="kriyasiddhih-sattve-bhavati-english">Kriyasiddhih Sattve Bhavati</a></li>
  <li><a href="laghu-stavam-english">Laghu Stavam</a></li>
  <li><a href="lalitha-ashtottara-sata-namaavali-english">Lalitha Ashtottara Sata Namaavali</a></li>
  <li><a href="lalitha-pancha-ratnam-english">Lalitha Pancha Ratnam</a></li>
  <li><a href="lingashtakam-english">Lingashtakam</a></li>
  <li><a href="maa-telugu-talliki-malle-poodanda-english">Maa Telugu Talliki Malle Poodanda</a></li>
  <li><a href="madhurashtakam-english">Madhurashtakam</a></li>
  <li><a href="mahaganapatim-manasa-smarami-english">Mahaganapatim Manasa Smarami</a></li>
  <li><a href="mahanyasam-english">Mahanyasam</a></li>
  <li><a href="maha-mrutyunjaya-stotram-rudram-pasupatim-english">Maha Mrutyunjaya Stotram (Rudram Pasupatim)</a></li>
  <li><a href="maha-narayana-upanishad-english">Maha Narayana Upanishad</a></li>
  <li><a href="maha-saura-mantram-english">Maha Saura Mantram</a></li>
  <li><a href="maitrim-bhajata-english">Maitrim Bhajata</a></li>
  <li><a href="manasa-satatam-smaraniyam-english">Manasa Satatam Smaraniyam</a></li>
  <li><a href="mana-swatantrya-bharata-english">Mana Swatantrya Bharata</a></li>
  <li><a href="manidweepa-varnanam-telugu-english">Manidweepa Varnanam (Telugu)</a></li>
  <li><a href="manidweepa-varnana-1-devi-bhagavatham-english">Manidweepa Varnana - 1 (Devi Bhagavatham)</a></li>
  <li><a href="manidweepa-varnana-2-devi-bhagavatham-english">Manidweepa Varnana - 2 (Devi Bhagavatham)</a></li>
  <li><a href="manidweepa-varnana-3-devi-bhagavatham-english">Manidweepa Varnana - 3 (Devi Bhagavatham)</a></li>
  <li><a href="manisha-panchakam-english">Manisha Panchakam</a></li>
  <li><a href="mani-karnika-ashtakam-english">Mani Karnika Ashtakam</a></li>
  <li><a href="mantra-matruka-pushpa-mala-stava-english">Mantra Matruka Pushpa Mala Stava</a></li>
  <li><a href="mantra-pushpam-english">Mantra Pushpam</a></li>
  <li><a href="maya-panchakam-english">Maya Panchakam</a></li>
  <li><a href="meenakshi-pancha-ratna-stotram-english">Meenakshi Pancha Ratna Stotram</a></li>
  <li><a href="mooka-pancha-sathi-1-arya-satakam-english">Mooka Pancha Sathi 1 - Arya Satakam</a></li>
  <li><a href="mooka-pancha-sathi-2-padaravinda-satakam-english">Mooka Pancha Sathi 2 - Padaravinda Satakam</a></li>
  <li><a href="mooka-pancha-sathi-3-stuti-satakam-english">Mooka Pancha Sathi 3 - Stuti Satakam</a></li>
  <li><a href="mooka-pancha-sathi-4-kataakshya-satakam-english">Mooka Pancha Sathi 4 - Kataakshya Satakam</a></li>
  <li><a href="mooka-pancha-sathi-5-mandasmitha-satakam-english">Mooka Pancha Sathi 5 - Mandasmitha Satakam</a></li>
  <li><a href="mrudapi-cha-chandanam-english">Mrudapi Cha Chandanam</a></li>
  <li><a href="mukunda-mala-stotram-english">Mukunda Mala Stotram</a></li>
  <li><a href="mundaka-upanishad-mundaka-1-section-1-english">Mundaka Upanishad - Mundaka 1, Section 1</a></li>
  <li><a href="mundaka-upanishad-mundaka-1-section-2-english">Mundaka Upanishad - Mundaka 1, Section 2</a></li>
  <li><a href="mundaka-upanishad-mundaka-2-section-1-english">Mundaka Upanishad - Mundaka 2, Section 1</a></li>
  <li><a href="mundaka-upanishad-mundaka-2-section-2-english">Mundaka Upanishad - Mundaka 2, Section 2</a></li>
  <li><a href="mundaka-upanishad-mundaka-3-section-1-english">Mundaka Upanishad - Mundaka 3, Section 1</a></li>
  <li><a href="mundaka-upanishad-mundaka-3-section-2-english">Mundaka Upanishad - Mundaka 3, Section 2</a></li>
  <li><a href="murari-pancha-ratna-stotram-english">Murari Pancha Ratna Stotram</a></li>
  <li><a href="nama-ramayanam-english">Nama Ramayanam</a></li>
  <li><a href="nanda-kumara-ashtakam-english">Nanda Kumara Ashtakam</a></li>
  <li><a href="nandikeshwara-ashtottara-sata-namavali-english">Nandikeshwara Ashtottara Sata Namavali</a></li>
  <li><a href="nanu-palima-nadachi-vachchitivo-english">Nanu Palima Nadachi Vachchitivo</a></li>
  <li><a href="narayana-kavacham-english">Narayana Kavacham</a></li>
  <li><a href="narayana-stotram-english">Narayana Stotram</a></li>
  <li><a href="narayana-upanishad-english">Narayana Upanishad</a></li>
  <li><a href="nataraja-stotram-patanjali-krutam-english">Nataraja Stotram (Patanjali Krutam)</a></li>
  <li><a href="navaratna-malika-stotram-english">Navaratna Malika Stotram</a></li>
  <li><a href="nirguna-manasa-puja-english">Nirguna Manasa Puja</a></li>
  <li><a href="nirvaana-dasakam-english">Nirvaana Dasakam</a></li>
  <li><a href="nirvana-shatkam-english">Nirvana Shatkam</a></li>
  <li><a href="nitya-parayana-slokas-english">Nitya Parayana Slokas</a></li>
  <li><a href="om-jaya-jagdish-hare-english">Om Jaya Jagdish Hare</a></li>
  <li><a href="padmavathi-stotram-english">Padmavathi Stotram</a></li>
  <li><a href="pahi-ramaprabho-english">Pahi Ramaprabho</a></li>
  <li><a href="pandava-gita-english">Pandava Gita</a></li>
  <li><a href="panduranga-ashtakam-english">Panduranga Ashtakam</a></li>
  <li><a href="paramatmudu-velige-english">Paramatmudu Velige</a></li>
  <li><a href="parvati-vallabha-ashtakam-english">Parvati Vallabha Ashtakam</a></li>
  <li><a href="pashupati-ashtakam-english">Pashupati Ashtakam</a></li>
  <li><a href="patanjali-yoga-sutras-1-samadhi-pada-english">Patanjali Yoga Sutras - 1 (Samadhi Pada)</a></li>
  <li><a href="patanjali-yoga-sutras-2-sadhana-pada-english">Patanjali Yoga Sutras - 2 (Sadhana Pada)</a></li>
  <li><a href="patanjali-yoga-sutras-3-vibhuti-pada-english">Patanjali Yoga Sutras - 3 (Vibhuti Pada)</a></li>
  <li><a href="patanjali-yoga-sutras-4-kaivalya-pada-english">Patanjali Yoga Sutras - 4 (Kaivalya Pada)</a></li>
  <li><a href="pathata-samskritam-vadata-samskritam-english">Pathata Samskritam Vadata Samskritam</a></li>
  <li><a href="pratasmarana-stotram-english">Pratasmarana Stotram</a></li>
  <li><a href="priyam-bharatam-english">Priyam Bharatam</a></li>
  <li><a href="rachayema-samskrita-bhavanam-grame-nagare-samasta-rashtre-english">Rachayema Samskrita Bhavanam (Grame Nagare Samasta Rashtre)</a></li>
  <li><a href="raghavendra-ashtottara-sata-namavali-english">Raghavendra Ashtottara Sata Namavali</a></li>
  <li><a href="rahu-ashtottara-sata-namavali-english">Rahu Ashtottara Sata Namavali</a></li>
  <li><a href="rahu-ashtottara-sata-nama-stotram-english">Rahu Ashtottara Sata Nama Stotram</a></li>
  <li><a href="rahu-kavacham-english">Rahu Kavacham</a></li>
  <li><a href="ramachandraya-janaka-mangalam-english">Ramachandraya Janaka (Mangalam)</a></li>
  <li><a href="ramadasu-keerthanas-e-teeruga-nanu-daya-choochedavo-english">Ramadasu Keerthanas E Teeruga Nanu Daya Choochedavo</a></li>
  <li><a href="ramadasu-keerthanas-ikshvaku-kula-tilaka-english">Ramadasu Keerthanas Ikshvaku Kula Tilaka</a></li>
  <li><a href="ramadasu-keerthanas-pahi-rama-prabho-english">Ramadasu Keerthanas Pahi Rama Prabho</a></li>
  <li><a href="ramadasu-keerthanas-paluke-bangaaramaayena-english">Ramadasu Keerthanas Paluke Bangaaramaayena</a></li>
  <li><a href="ramayana-chaupayee-english">Ramayana Chaupayee</a></li>
  <li><a href="ramayana-jaya-mantram-english">Ramayana Jaya Mantram</a></li>
  <li><a href="rama-laali-meghashyama-laali-english">Rama Laali Meghashyama Laali</a></li>
  <li><a href="rama-raksha-stotram-english">Rama Raksha Stotram</a></li>
  <li><a href="rama-sabha-english">Rama Sabha</a></li>
  <li><a href="ranganatha-ashtakam-english">Ranganatha Ashtakam</a></li>
  <li><a href="rudrashtakam-english">Rudrashtakam</a></li>
  <li><a href="runa-vimochana-angaraka-stotram-english">Runa Vimochana Angaraka Stotram</a></li>
  <li><a href="sadguru-stavam-english">Sadguru Stavam</a></li>
  <li><a href="sakala-janani-stavam-english">Sakala Janani Stavam</a></li>
  <li><a href="sampurna-visva-ratnam-saare-jahan-se-accha-in-samskritam-english">Sampurna Visva Ratnam (Saare Jahan Se Accha in Samskritam)</a></li>
  <li><a href="sani-ashtottara-sata-namavali-english">Sani Ashtottara Sata Namavali</a></li>
  <li><a href="sani-ashtottara-sata-nama-stotram-english">Sani Ashtottara Sata Nama Stotram</a></li>
  <li><a href="sankshepa-ramayanam-english">Sankshepa Ramayanam</a></li>
  <li><a href="santana-gopala-stotram-english">Santana Gopala Stotram</a></li>
  <li><a href="santhana-ganapathi-stotram-english">Santhana Ganapathi Stotram</a></li>
  <li><a href="sanusvara-prasna-sunnala-pannam-english">Sanusvara Prasna (Sunnala Pannam)</a></li>
  <li><a href="sare-jahan-se-accha-english">Sare Jahan Se Accha</a></li>
  <li><a href="sata-rudreeyam-english">Sata Rudreeyam</a></li>
  <li><a href="shani-stotram-dasaratha-krutam-english">Shani Stotram Dasaratha Krutam</a></li>
  <li><a href="shani-vajrapanjara-kavacham-english">Shani Vajrapanjara Kavacham</a></li>
  <li><a href="shanti-mantram-dasha-shanti-mantram-english">Shanti Mantram (Dasha Shanti Mantram)</a></li>
  <li><a href="sharabhesha-ashtakam-english">Sharabhesha Ashtakam</a></li>
  <li><a href="sharada-bhujanga-prayata-ashtakam-english">Sharada Bhujanga Prayata Ashtakam</a></li>
  <li><a href="sharada-prarthana-english">Sharada Prarthana</a></li>
  <li><a href="shuddhosi-buddhosi-english">Shuddhosi Buddhosi</a></li>
  <li><a href="shukra-kavacham-english">Shukra Kavacham</a></li>
  <li><a href="shyamala-dandakam-english">Shyamala Dandakam</a></li>
  <li><a href="siddha-kunjika-stotram-english">Siddha Kunjika Stotram</a></li>
  <li><a href="soundarya-lahari-english">Soundarya Lahari</a></li>
  <li><a href="sree-annapurna-stotram-english">Sree Annapurna Stotram</a></li>
  <li><a href="sree-bhu-varaha-stotram-english">Sree Bhu Varaha Stotram</a></li>
  <li><a href="sree-kaala-hastiswara-satakam-english">Sree Kaala Hastiswara Satakam</a></li>
  <li><a href="sree-lalitha-sahasra-namavali-english">Sree Lalitha Sahasra Namavali</a></li>
  <li><a href="sree-lalitha-sahasra-nama-stotram-english">Sree Lalitha Sahasra Nama Stotram</a></li>
  <li><a href="sree-mallikarjuna-mangalasasanam-english">Sree Mallikarjuna Mangalasasanam</a></li>
  <li><a href="sree-purushottama-sahasra-nama-stotram-english">Sree Purushottama Sahasra Nama Stotram</a></li>
  <li><a href="sree-ramaashtottara-sata-nama-stotram-english">Sree Ramaashtottara Sata Nama Stotram</a></li>
  <li><a href="sree-tulasi-ashtottara-satanaama-stotram-english">Sree Tulasi Ashtottara Satanaama Stotram</a></li>
  <li><a href="sree-vaastu-ashtothara-sata-namavali-english">Sree Vaastu Ashtothara Sata Namavali</a></li>
  <li><a href="sree-vasavi-kanyaka-paramesvari-ashtottara-sata-naamaavali-english">Sree Vasavi Kanyaka Paramesvari Ashtottara Sata Naamaavali</a></li>
  <li><a href="srisaila-ragada-telugu-english">Srisaila Ragada (Telugu)</a></li>
  <li><a href="sri-aadya-kali-stotram-english">Sri Aadya Kali Stotram</a></li>
  <li><a href="sri-ananta-padmanabha-ashtottara-sata-namavali-english">Sri Ananta Padmanabha Ashtottara Sata Namavali</a></li>
  <li><a href="sri-annapurna-ashtottara-satanama-stotram-english">Sri Annapurna Ashtottara Satanama Stotram</a></li>
  <li><a href="sri-annapurna-ashtottara-sata-namavali-english">Sri Annapurna Ashtottara Sata Namavali</a></li>
  <li><a href="sri-bhadrakali-ashtottara-satanama-stotram-english">Sri Bhadrakali Ashtottara Satanama Stotram</a></li>
  <li><a href="sri-bhadrakali-ashtottara-sata-namavali-english">Sri Bhadrakali Ashtottara Sata Namavali</a></li>
  <li><a href="sri-dakshina-kali-kadgamala-stotram-english">Sri Dakshina Kali Kadgamala Stotram</a></li>
  <li><a href="sri-datta-bhavani-english">Sri Datta Bhavani</a></li>
  <li><a href="sri-datta-mala-mantra-english">Sri Datta Mala Mantra</a></li>
  <li><a href="sri-datta-stavam-english">Sri Datta Stavam</a></li>
  <li><a href="sri-devi-atharva-sheersham-english">Sri Devi Atharva Sheersham</a></li>
  <li><a href="sri-devi-khadgamala-stotram-english">Sri Devi Khadgamala Stotram</a></li>
  <li><a href="sri-gananatham-bhajamyaham-english">Sri Gananatham Bhajamyaham</a></li>
  <li><a href="sri-ganapathi-stavam-english">Sri Ganapathi Stavam</a></li>
  <li><a href="sri-ganapathi-talam-english">Sri Ganapathi Talam</a></li>
  <li><a href="sri-govindashtakam-govinda-ashtakam-english">Sri Govindashtakam (Govinda Ashtakam)</a></li>
  <li><a href="sri-gurugita-chapter-1-english">Sri Gurugita Chapter 1</a></li>
  <li><a href="sri-gurugita-chapter-2-english">Sri Gurugita Chapter 2</a></li>
  <li><a href="sri-gurugita-chapter-3-english">Sri Gurugita Chapter 3</a></li>
  <li><a href="sri-guru-stotram-guru-vandanam-english">Sri Guru Stotram (Guru Vandanam)</a></li>
  <li><a href="sri-hari-ashtakam-prahlada-krutam-english">Sri Hari Ashtakam (Prahlada Krutam)</a></li>
  <li><a href="sri-hari-stotram-jagajjalapalam-english">Sri Hari Stotram (Jagajjalapalam)</a></li>
  <li><a href="sri-hari-vayu-stuti-english">Sri Hari Vayu Stuti</a></li>
  <li><a href="sri-hayagriva-sampada-stotram-english">Sri Hayagriva Sampada Stotram</a></li>
  <li><a href="sri-hayagriva-stotram-english">Sri Hayagriva Stotram</a></li>
  <li><a href="sri-kala-bhairava-stotram-english">Sri Kala Bhairava Stotram</a></li>
  <li><a href="sri-kali-chalisa-english">Sri Kali Chalisa</a></li>
  <li><a href="sri-kamakhya-stotram-english">Sri Kamakhya Stotram</a></li>
  <li><a href="sri-kamakshi-stotram-english">Sri Kamakshi Stotram</a></li>
  <li><a href="sri-kashi-visvanatha-stotram-english">Sri Kashi Visvanatha Stotram</a></li>
  <li><a href="sri-kumara-kavacham-english">Sri Kumara Kavacham</a></li>
  <li><a href="sri-lalitha-chalisa-english">Sri Lalitha Chalisa</a></li>
  <li><a href="sri-lalitha-hrudayam-english">Sri Lalitha Hrudayam</a></li>
  <li><a href="sri-lalitha-trishati-namavali-english">Sri Lalitha Trishati Namavali</a></li>
  <li><a href="sri-lalitha-trishati-stotram-english">Sri Lalitha Trishati Stotram</a></li>
  <li><a href="sri-maha-kali-stotram-english">Sri Maha Kali Stotram</a></li>
  <li><a href="sri-mahishasura-mardini-stotram-ayigiri-nandini-english">Sri Mahishasura Mardini Stotram (Ayigiri Nandini)</a></li>
  <li><a href="sri-manasa-devi-stotram-mahendra-kritam-english">Sri Manasa Devi Stotram (Mahendra Kritam)</a></li>
  <li><a href="sri-mangala-gowri-ashtottara-sata-namavali-english">Sri Mangala Gowri Ashtottara Sata Namavali</a></li>
  <li><a href="sri-meenakshi-stotram-english">Sri Meenakshi Stotram</a></li>
  <li><a href="sri-narayana-hrudaya-stotram-english">Sri Narayana Hrudaya Stotram</a></li>
  <li><a href="sri-nrusimha-sarasvathi-ashtakam-english">Sri Nrusimha Sarasvathi Ashtakam</a></li>
  <li><a href="sri-pada-sri-vallabha-siddha-mangala-stotram-english">Sri Pada Sri Vallabha Siddha Mangala Stotram</a></li>
  <li><a href="sri-panchayudha-stotram-english">Sri Panchayudha Stotram</a></li>
  <li><a href="sri-pratyangira-ashtottara-sata-namavali-english">Sri Pratyangira Ashtottara Sata Namavali</a></li>
  <li><a href="sri-radha-kripa-kataksha-stotram-english">Sri Radha Kripa Kataksha Stotram</a></li>
  <li><a href="sri-raghuveera-gadyam-sri-mahaveera-vaibhavam-english">Sri Raghuveera Gadyam (Sri Mahaveera Vaibhavam)</a></li>
  <li><a href="sri-raja-rajeswarai-ashtakam-english">Sri Raja Rajeswarai Ashtakam</a></li>
  <li><a href="sri-ramachandra-krupalu-english">Sri Ramachandra Krupalu</a></li>
  <li><a href="sri-ramanujashtakam-english">Sri Ramanujashtakam</a></li>
  <li><a href="sri-rama-apaduddharaka-stotram-english">Sri Rama Apaduddharaka Stotram</a></li>
  <li><a href="sri-rama-ashtottara-sata-naama-stotram-english">Sri Rama Ashtottara Sata Naama Stotram</a></li>
  <li><a href="sri-rama-ashtottara-sata-namaavali-english">Sri Rama Ashtottara Sata Namaavali</a></li>
  <li><a href="sri-rama-bhujanga-prayaata-stotram-english">Sri Rama Bhujanga Prayaata Stotram</a></li>
  <li><a href="sri-rama-charita-manasa-aranya-kanda-english">Sri Rama Charita Manasa - Aranya Kanda</a></li>
  <li><a href="sri-rama-charita-manasa-ayodhya-kanda-english">Sri Rama Charita Manasa - Ayodhya Kanda</a></li>
  <li><a href="sri-rama-charita-manasa-bala-kanda-english">Sri Rama Charita Manasa - Bala Kanda</a></li>
  <li><a href="sri-rama-charita-manasa-kishkindha-kanda-english">Sri Rama Charita Manasa - Kishkindha Kanda</a></li>
  <li><a href="sri-rama-charita-manasa-lanka-kanda-english">Sri Rama Charita Manasa - Lanka Kanda</a></li>
  <li><a href="sri-rama-charita-manasa-sundara-kanda-english">Sri Rama Charita Manasa - Sundara Kanda</a></li>
  <li><a href="sri-rama-charita-manasa-uttara-kanda-english">Sri Rama Charita Manasa - Uttara Kanda</a></li>
  <li><a href="sri-rama-hrudayam-english">Sri Rama Hrudayam</a></li>
  <li><a href="sri-rama-karnamrutam-english">Sri Rama Karnamrutam</a></li>
  <li><a href="sri-rama-kavacham-english">Sri Rama Kavacham</a></li>
  <li><a href="sri-rama-mangalasasanam-prapatti-mangalam-english">Sri Rama Mangalasasanam (Prapatti & Mangalam)</a></li>
  <li><a href="sri-rama-paadama-english">Sri Rama Paadama</a></li>
  <li><a href="sri-rama-pancha-ratna-stotram-english">Sri Rama Pancha Ratna Stotram</a></li>
  <li><a href="sri-rama-sahasra-nama-stotram-english">Sri Rama Sahasra Nama Stotram</a></li>
  <li><a href="sri-ranganatha-ashtottara-sata-namavali-english">Sri Ranganatha Ashtottara Sata Namavali</a></li>
  <li><a href="sri-ranganatha-ashtottara-sata-nama-stotram-english">Sri Ranganatha Ashtottara Sata Nama Stotram</a></li>
  <li><a href="sri-rudram-chamakam-english">Sri Rudram Chamakam</a></li>
  <li><a href="sri-rudram-laghunyasam-english">Sri Rudram Laghunyasam</a></li>
  <li><a href="sri-rudram-namakam-english">Sri Rudram Namakam</a></li>
  <li><a href="sri-sankaracharya-varyam-english">Sri Sankaracharya Varyam</a></li>
  <li><a href="sri-satyanarayana-ashtottara-sata-namavali-english">Sri Satyanarayana Ashtottara Sata Namavali</a></li>
  <li><a href="sri-shankaracharya-ashtottara-sata-namavali-english">Sri Shankaracharya Ashtottara Sata Namavali</a></li>
  <li><a href="sri-shanmukha-dandakam-english">Sri Shanmukha Dandakam</a></li>
  <li><a href="sri-shanmukha-pancharatna-stuti-english">Sri Shanmukha Pancharatna Stuti</a></li>
  <li><a href="sri-shanmukha-shatkam-english">Sri Shanmukha Shatkam</a></li>
  <li><a href="sri-shashti-devi-stotram-english">Sri Shashti Devi Stotram</a></li>
  <li><a href="sri-shiridi-sai-chalisa-english">Sri Shiridi Sai Chalisa</a></li>
  <li><a href="sri-sita-rama-stotram-english">Sri Sita Rama Stotram</a></li>
  <li><a href="sri-srinivasa-gadyam-english">Sri Srinivasa Gadyam</a></li>
  <li><a href="sri-swaminatha-panchakam-english">Sri Swaminatha Panchakam</a></li>
  <li><a href="sri-swarna-akarshana-bhairava-ashtottara-sata-namavali-english">Sri Swarna Akarshana Bhairava Ashtottara Sata Namavali</a></li>
  <li><a href="sri-veda-vyasa-stuti-english">Sri Veda Vyasa Stuti</a></li>
  <li><a href="sri-veerabhadra-ashtottara-sata-namavali-english">Sri Veerabhadra Ashtottara Sata Namavali</a></li>
  <li><a href="sri-vengamambas-mangala-harathi-english">Sri Vengamamba's Mangala Harathi</a></li>
  <li><a href="sri-vighnesvara-ashtottara-sata-namavali-english">Sri Vighnesvara Ashtottara Sata Namavali</a></li>
  <li><a href="sudarshana-ashtakam-vedantacharya-krutam-english">Sudarshana Ashtakam (Vedantacharya Krutam)</a></li>
  <li><a href="sudarshana-ashtottara-sata-namavali-english">Sudarshana Ashtottara Sata Namavali</a></li>
  <li><a href="sudarshana-ashtottara-sata-nama-stotram-english">Sudarshana Ashtottara Sata Nama Stotram</a></li>
  <li><a href="sudarshana-sahasra-namavali-english">Sudarshana Sahasra Namavali</a></li>
  <li><a href="sudarshana-sahasra-nama-stotram-english">Sudarshana Sahasra Nama Stotram</a></li>
  <li><a href="sudarshana-shatkam-english">Sudarshana Shatkam</a></li>
  <li><a href="sukra-ashtottara-sata-namavali-english">Sukra Ashtottara Sata Namavali</a></li>
  <li><a href="sukra-ashtottara-sata-nama-stotram-english">Sukra Ashtottara Sata Nama Stotram</a></li>
  <li><a href="sumati-satakam-english">Sumati Satakam</a></li>
  <li><a href="surasa-subodha-naiva-klishta-na-cha-kathina-english">Surasa Subodha (Naiva Klishta Na Cha Kathina)</a></li>
  <li><a href="suvarnamala-stuti-english">Suvarnamala Stuti</a></li>
  <li><a href="taittiriya-upanishad-ananda-valli-english">Taittiriya Upanishad - Ananda Valli</a></li>
  <li><a href="taittiriya-upanishad-bhrugu-valli-english">Taittiriya Upanishad - Bhrugu Valli</a></li>
  <li><a href="taittiriya-upanishad-shiksha-valli-english">Taittiriya Upanishad - Shiksha Valli</a></li>
  <li><a href="takkuvemi-manaku-english">Takkuvemi Manaku</a></li>
  <li><a href="taraka-mantramu-english">Taraka Mantramu</a></li>
  <li><a href="tiruppavai-english">Tiruppavai</a></li>
  <li><a href="totakashtakam-english">Totakashtakam</a></li>
  <li><a href="tripura-sundari-ashtakam-english">Tripura Sundari Ashtakam</a></li>
  <li><a href="trisuparnam-english">Trisuparnam</a></li>
  <li><a href="uma-maheswara-stotram-english">Uma Maheswara Stotram</a></li>
  <li><a href="upadesha-saram-ramana-maharshi-english">Upadesha Saram (Ramana Maharshi)</a></li>
  <li><a href="vaidyanatha-ashtakam-english">Vaidyanatha Ashtakam</a></li>
  <li><a href="vandanamu-raghunandana-english">Vandanamu Raghunandana</a></li>
  <li><a href="vande-bharata-mataram-vada-bharata-english">Vande Bharata Mataram Vada Bharata</a></li>
  <li><a href="vande-mataram-english">Vande Mataram</a></li>
  <li><a href="varahi-ashtottara-sata-namavali-english">Varahi Ashtottara Sata Namavali</a></li>
  <li><a href="varahi-kavacham-english">Varahi Kavacham</a></li>
  <li><a href="varahi-sahasra-namavali-english">Varahi Sahasra Namavali</a></li>
  <li><a href="varahi-sahasra-nama-stotram-english">Varahi Sahasra Nama Stotram</a></li>
  <li><a href="vasudeva-stotram-mahabharatam-english">Vasudeva Stotram (Mahabharatam)</a></li>
  <li><a href="vatapi-ganapatim-bhajeham-english">Vatapi Ganapatim Bhajeham</a></li>
  <li><a href="vedanta-dindima-english">Vedanta Dindima</a></li>
  <li><a href="veda-asheervachanam-english">Veda Asheervachanam</a></li>
  <li><a href="veda-svasti-vachanam-english">Veda Svasti Vachanam</a></li>
  <li><a href="vel-maaral-tamil-english">Vel Maaral (Tamil)</a></li>
  <li><a href="vemana-satakam-english">Vemana Satakam</a></li>
  <li><a href="venu-gopala-ashtakam-english">Venu Gopala Ashtakam</a></li>
  <li><a href="vidura-neethi-udyoga-parvam-chapter-33-english">Vidura Neethi - Udyoga Parvam Chapter 33</a></li>
  <li><a href="vidura-neethi-udyoga-parvam-chapter-34-english">Vidura Neethi - Udyoga Parvam Chapter 34</a></li>
  <li><a href="vidura-neethi-udyoga-parvam-chapter-35-english">Vidura Neethi - Udyoga Parvam Chapter 35</a></li>
  <li><a href="vidura-neethi-udyoga-parvam-chapter-36-english">Vidura Neethi - Udyoga Parvam Chapter 36</a></li>
  <li><a href="vidura-neethi-udyoga-parvam-chapter-37-english">Vidura Neethi - Udyoga Parvam Chapter 37</a></li>
  <li><a href="vidura-neethi-udyoga-parvam-chapter-38-english">Vidura Neethi - Udyoga Parvam Chapter 38</a></li>
  <li><a href="vidura-neethi-udyoga-parvam-chapter-39-english">Vidura Neethi - Udyoga Parvam Chapter 39</a></li>
  <li><a href="vidura-neethi-udyoga-parvam-chapter-40-english">Vidura Neethi - Udyoga Parvam Chapter 40</a></li>
  <li><a href="vighnesvara-ashtottara-sata-nama-stotram-english">Vighnesvara Ashtottara Sata Nama Stotram</a></li>
  <li><a href="vijayee-viswa-tiranga-pyaara-english">Vijayee Viswa Tiranga Pyaara</a></li>
  <li><a href="vishvambhari-stuti-english">Vishvambhari Stuti</a></li>
  <li><a href="viswa-bhasha-samskritam-english">Viswa Bhasha Samskritam</a></li>
  <li><a href="viveka-chudamani-english">Viveka Chudamani</a></li>
  <li><a href="yagnopavita-dharana-english">Yagnopavita Dharana</a></li>
  <li><a href="yama-ashtakam-english">Yama Ashtakam</a></li>
    </ul>
</div>
</section>
</main>

<?php include "../includes/footer.php"; ?>
